//
//  ImportantAnnouncementsInteractor.swift
//  PremierInn
//
//
//  Created Freddie Parks on 17/03/2020.
//  Copyright © 2020 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import Foundation

class ImportantAnnouncementsInteractor {
    private var message: NotificationsMessage?

    init(with message: NotificationsMessage) {
        self.message = message
    }
}

extension ImportantAnnouncementsInteractor: ImportantAnnouncementsInteractorProtocol {
    private struct ViewModel: ImportantAnnouncementsViewModel {
        let title: String
        let body: String
        let ctaTitle: String
    }

    var viewModel: ImportantAnnouncementsViewModel? {
        guard let message = message else { return nil }
        return ViewModel(title: message.title, body: message.message, ctaTitle: message.ctaTitle)
    }

    func finishedViewingMessage() {
        guard let messageID = message?.id else { return }
        UserDefaults.standard.set(
            messageID,
            forKey: Constants.ImportantAnnouncements.lastImportantAnnouncementMessageReadIdKey
        )
    }
}
