//
//  ImportantAnnouncementsPresenter.swift
//  PremierInn
//
//
//  Created Freddie Parks on 17/03/2020.
//  Copyright © 2020 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import Foundation

class ImportantAnnouncementsPresenter {
    weak var view: ImportantAnnouncementsViewProtocol?

    var interactor: ImportantAnnouncementsInteractorProtocol?
    var router: ImportantAnnouncementsRouterProtocol?
}

extension ImportantAnnouncementsPresenter: ImportantAnnouncementsViewEventHandler {
    func viewIsReady() {
        guard let viewModel = interactor?.viewModel else { return }
        view?.update(with: viewModel)
    }

    func ctaButtonDidTap() {
        interactor?.finishedViewingMessage()
        router?.finishedViewingMessage()
    }
}
