//
//  ImportantAnnouncementsView.swift
//  PremierInn
//
//  V is for "View" 🌁, and "Vote" 🙋‍♂️
//
//  Created Freddie Parks on 17/03/2020.
//  Copyright © 2020 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit

class ImportantAnnouncementsView: UIViewController {
    var eventHandler: ImportantAnnouncementsViewEventHandler?

	@IBOutlet weak var messageTitle: UILabel! {
		didSet {
			messageTitle.font = UIFont.LargeTitle()
		}
	}
	@IBOutlet weak var messageText: UITextView! {
		didSet {
			messageText.font = UIFont.Body()
		}
	}
	@IBOutlet weak var cta: RoundedCornersButton! {
		didSet {
			cta.titleLabel?.font = UIFont.Button1()
            cta.setTitleColor(.BaseWhite, for: .normal)
            cta.backgroundColor = .Tint1
		   }
	   }

    init() {
        super.init(nibName: "ImportantAnnouncementsView", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        configureModalNavigationBar()
        eventHandler?.viewIsReady()
    }

    @IBAction func ctaButtonDidTap(_ sender: Any) {
        eventHandler?.ctaButtonDidTap()
    }
}

extension ImportantAnnouncementsView: ImportantAnnouncementsViewProtocol {
    func update(with viewModel: ImportantAnnouncementsViewModel) {
        messageTitle.text = viewModel.title
        messageText.text = viewModel.body
        cta.setTitle(viewModel.ctaTitle, for: .normal)
        cta.accessibilityIdentifier = AccessibilityIdentifiers.ImportantAnnouncements.ctaButton
    }
}
