//
//  ImportantAnnouncementsRouter.swift
//  PremierInn
//
//  R is for "Router" 🚦, and "Rancid" 😷
//
//  Created Freddie Parks on 17/03/2020.
//  Copyright © 2020 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit

class ImportantAnnouncementsRouter {
    var view: UIViewController?
}

extension ImportantAnnouncementsRouter: ImportantAnnouncementsRouterProtocol {
    func finishedViewingMessage() {
        view?.dismiss(animated: true)
    }
}
