//
//  ImportantAnnouncementsModule.swift
//  PremierInn
//
//  Created Freddie Parks on 17/03/2020.
//  Copyright © 2020 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit

enum ImportantAnnouncementsModule {
    static func build(with message: NotificationsMessage) -> UIViewController {
        let controller = ImportantAnnouncementsView()
        controller.modalPresentationStyle = .fullScreen

        controller.eventHandler = {
            let presenter = ImportantAnnouncementsPresenter()

            let router = ImportantAnnouncementsRouter()
            router.view = controller

            let interactor = ImportantAnnouncementsInteractor(with: message)

            presenter.view = controller
            presenter.interactor = interactor
            presenter.router = router

            return presenter
        }()

        return controller
    }
}

protocol ImportantAnnouncementsViewModel {
    var title: String { get }
    var body: String { get }
    var ctaTitle: String { get }
}

protocol ImportantAnnouncementsViewProtocol: AnyObject {
    func update(with viewModel: ImportantAnnouncementsViewModel)
}

protocol ImportantAnnouncementsViewEventHandler {
    func viewIsReady()
    func ctaButtonDidTap()
}

protocol ImportantAnnouncementsInteractorProtocol {
    var viewModel: ImportantAnnouncementsViewModel? { get }

    func finishedViewingMessage()
}

protocol ImportantAnnouncementsRouterProtocol {
    func finishedViewingMessage()
}
