@startuml
entity "Reservation Entity Service" as A
entity "PMS Adapter Service" as PMS
entity "OHIP Adapter Service" as OHIP
entity OPERA

A -> PMS: GET /adp/reservations/cancel?hotelId={hotelId}&reservationIds={reservationIds}&userDateTime={userDateTime}
PMS -> OHIP: GET /ohip/reservations/cancel?hotelId={hotelId}&reservationIds={reservationIds}&userDateTime={userDateTime}
OHIP -> OPERA: GET /rsv/v0/hotels/{hotelId}/reservations/{reservationId}/policies
OHIP <- OPERA: CancelInformationDto
PMS <- OHIP: CancelInformationDto
A <- PMS: CancelInformationDto
@enduml