@startuml
entity "PMS Adapter Service" as PMS
participant PackageController as Controller
participant PackagesInPort as InboundPort
participant PackagesOutPort as OutboundPort
participant OhipPackagesClient as OhipClient
participant OhipRestaurantsClient as OhipRestaurantsClient
entity OPERA

PMS -> Controller: GET /ohip/hotels/{hotelId}/packages?\nstartDate={{startDate}}\n&endDate={{endDate}}\n&adults={{adults}}\n&children={{children}}\n&nrNights={{nrNights}}
Controller -> InboundPort: getPackages
InboundPort -> OutboundPort: getPackages
OutboundPort -> OhipClient: getPackages
OhipRestaurantsClient -> OPERA: GET {host}/ent/config/v1/hotels/{{hotelId}}?\nfetchInstructions=Dining
OhipRestaurantsClient <- OPERA : Restaurants Info
OhipClient -> OPERA: GET {host}/rtp/v1/packages?\nincludeGroup=true\n&sellSeparate=true\n&fetchInstructions=Header\n&fetchInstructions=CalculatedPrice\n&fetchInstructions=Items\n&startDate={{startDate}}\n&endDate={{endDate}}\n&children={{children}}\n&adults={{adults}}\n&hotelId={{hotelId}}

OhipClient <- OPERA: Packages Info
OutboundPort <- OhipClient: Packages Info
InboundPort <- OutboundPort: Packages Info
Controller <- InboundPort: Packages Info
PMS <- Controller: Packages Info
@enduml