@startuml
entity "Reservation Entity Service" as A
entity "PMS Adapter Service" as PMS
entity "OHIP Adapter Service" as OHIP
entity OPERA

A -> PMS: GET /adp/v1/reservations/cancellationPolicies?basketReference={{basketReference}}?hotelId={{hotelId}}?ratePlanCode={{ratePlanCode}}?arrivalDate={{arrivalDate}}
PMS -> OHIP: GET /ohip/v1/reservations/cancellationPolicies?basketReference={{basketReference}}?hotelId={{hotelId}}?ratePlanCode={{ratePlanCode}}?arrivalDate={{arrivalDate}}
group reservationId
    OHIP -> OPERA: GET /rsv/v1/hotels/{{HotelId}}/reservations/{{ReservationId}}?fetchInstructions=ReservationPolicies
    OHIP <- OPERA: Reservation
end
group ratePlanCode and arrivalDate
    OHIP -> OPERA: GET /rsv/config/v0/cancelpolicies?hotelIds={{HotelId}}
    OHIP <- OPERA: CancellationPolicyDetails
    OHIP -> OPERA: GET /rsv/config/v0/hotels/{{HotelId}}/policyschedules?policyType=Cancellation&ratePlanCodes={{RatePlanCode}}
    OHIP <- OPERA: PolicySchedulesDetails
end
PMS <- OHIP: CancellationPoliciesResponse
A <- PMS: CancellationPoliciesResponse
@enduml