@startuml
entity "PMS Adapter Service" as PMS
participant HotelReservationController as Controller
participant HotelReservationInPort as InboundPort
participant HotelReservationOutboundPort as OutboundPort
participant HotelReservationWebClient as Webclient
entity Opera as opera

PMS -> Controller: POST /ohip/v1//reservations/movePaymentDetails
Controller -> InboundPort: movePaymentDetails
InboundPort -> OutboundPort: movePaymentDetails

OutboundPort -> Webclient: sendGetReservationsByIds(String hotelId, Set<String> reservationIds)

loop for each reservationId
    Webclient -> opera: GET /rsv/v1/hotels/{{HotelId}}/reservations/{{ReservationId}}/\n?fetchInstructions=Reservation&fetchInstructions=InventoryItems\n&fetchInstructions=ReservationPolicies&fetchInstructions=Packages
    Webclient <- opera: Reservation
end
OutboundPort <- Webclient: Reservations

loop for each reservation
    OutboundPort -> Webclient: sendChangeReservationRequest(String hotelId, String reservationId, ChangeReservation changeReservation)
    Webclient -> opera: PUT /rsv/v1/hotels/{{HotelId}}/reservations
    Webclient <- opera: ChangeReservationDetails
    OutboundPort <- Webclient:200 OK
end

InboundPort <- OutboundPort: 200 OK
Controller <- InboundPort: 200 OK
PMS <- Controller: 200 OK
@enduml