@startuml
entity "OHIP Adapter Service" as OHIP
participant HotelReservationController as Controller
participant HotelReservationInPort as InboundPort
participant HotelReservationOutboundPort as OutboundPort
participant HotelReservationWebClient as WebClient
entity OPERA

OHIP -> Controller: PUT /v1/reservations/reasonForStay
Controller -> InboundPort: updateReasonForStay
InboundPort -> OutboundPort: updateReasonForStay
OutboundPort -> WebClient: sendChangeReservationRequest

loop for each reservationId
    WebClient -> OPERA: PUT /rsv/v1/hotels/{{HotelId}}/reservations/{{ReservationId}}
    WebClient <- OPERA: ChangeReservationDetails
end

OutboundPort <- WebClient: ChangeReservationDetails
InboundPort <- OutboundPort: UpdateReasonForStayResponse
Controller <- InboundPort: UpdateReasonForStayResponse
OHIP <- Controller: UpdateReasonForStayResponseDto
@enduml