import org.springframework.cloud.contract.spec.Contract

Contract.make {
    description("Get Customers Current Balance  belongs to given company-id, employee-id")
    request {
        method 'GET'
        url '/piba/account/balance'
        headers {
            header('Content-Type', 'application/json')
            header('company-id', '123')
            header('employee-id', '42')
            header('viewAll', 'false')
            header("Authorization", "Bearer dummy_value6")
        }
    }

    response {
        status 200
        body('''
{
   "currentBalances":[
      {
         "schemeCustomerId":782810,
         "outstanding":{
            "amount":8653.44,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "newTransactions":{
            "amount":507.53,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "available":{
            "amount":97.98,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "creditLimit":{
            "amount":3000.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "currentBalance":{
            "amount":2902.02,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "interimPayments":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "tetheredGuid":"CE3C22D3-D413-4FB2-8219-1160FEE0FC21",
         "accountName":"100216",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "ACCOUNT_HOLDER"
         ]
      },
      {
         "schemeCustomerId":782831,
         "outstanding":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "newTransactions":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "available":{
            "amount":10000.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "creditLimit":{
            "amount":10000.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "currentBalance":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "interimPayments":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "tetheredGuid":"1EA0F9EF-A09B-479A-AD27-148BC6B19483",
         "accountName":"07734435",
         "accountNumber":"3000003200100301",
         "registrationRoles":[
            "ACCOUNT_HOLDER"
         ]
      },
      {
         "schemeCustomerId":782931,
         "outstanding":null,
         "newTransactions":null,
         "available":null,
         "creditLimit":null,
         "currentBalance":null,
         "interimPayments":null,
         "tetheredGuid":"62E3C0AB-1A10-4852-B5EC-BB6EB390C041",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "FINANCE_USER"
         ],
         "errorCode":"Error while retrieving balance"
      },
      {
         "schemeCustomerId":783139,
         "outstanding":null,
         "newTransactions":null,
         "available":null,
         "creditLimit":null,
         "currentBalance":null,
         "interimPayments":null,
         "tetheredGuid":"AD70A44A-6324-4367-9C8C-60A985FF08D9",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "ACCOUNT_HOLDER"
         ],
         "errorCode":"Error while retrieving balance"
      },
      {
         "schemeCustomerId":783562,
         "outstanding":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "newTransactions":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "available":{
            "amount":800.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "creditLimit":{
            "amount":800.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "currentBalance":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "interimPayments":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "tetheredGuid":"327F7A0C-9A33-41C2-808D-74F15F24797C",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "ACCOUNT_HOLDER"
         ]
      },
      {
         "schemeCustomerId":783576,
         "outstanding":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "newTransactions":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "available":{
            "amount":800.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "creditLimit":{
            "amount":800.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "currentBalance":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "interimPayments":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "tetheredGuid":"2EE9558D-1ECB-40AA-B58C-2187145B6026",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "ACCOUNT_HOLDER"
         ]
      },
      {
         "schemeCustomerId":783576,
         "outstanding":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "newTransactions":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "available":{
            "amount":800.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "creditLimit":{
            "amount":800.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "currentBalance":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "interimPayments":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "tetheredGuid":"6F5A0338-24B9-474B-B961-6EF9D07145AE",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "ACCOUNT_HOLDER"
         ]
      },
      {
         "schemeCustomerId":783577,
         "outstanding":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "newTransactions":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "available":{
            "amount":9999.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "creditLimit":{
            "amount":9999.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "currentBalance":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "interimPayments":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "tetheredGuid":"7AEC6C37-581D-44EE-AFA4-8D70E6B895F2",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "ACCOUNT_HOLDER"
         ]
      },
      {
         "schemeCustomerId":783582,
         "outstanding":null,
         "newTransactions":null,
         "available":null,
         "creditLimit":null,
         "currentBalance":null,
         "interimPayments":null,
         "tetheredGuid":"9B1B3ED5-F61C-403E-8A56-59F0B625F856",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "CARD_HOLDER",
            "ACCOUNT_HOLDER"
         ],
         "errorCode":"Error while retrieving balance"
      },
      {
         "schemeCustomerId":783582,
         "outstanding":null,
         "newTransactions":null,
         "available":null,
         "creditLimit":null,
         "currentBalance":null,
         "interimPayments":null,
         "tetheredGuid":"27BC5494-E249-4577-AC98-980BE72F4966",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "CARD_HOLDER",
            "ACCOUNT_HOLDER"
         ],
         "errorCode":"Error while retrieving balance"
      },
      {
         "schemeCustomerId":783582,
         "outstanding":null,
         "newTransactions":null,
         "available":null,
         "creditLimit":null,
         "currentBalance":null,
         "interimPayments":null,
         "tetheredGuid":"6B2DDD1A-764D-445E-BC38-8C77DC215168",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "CARD_HOLDER",
            "ACCOUNT_HOLDER"
         ],
         "errorCode":"Error while retrieving balance"
      },
      {
         "schemeCustomerId":783582,
         "outstanding":null,
         "newTransactions":null,
         "available":null,
         "creditLimit":null,
         "currentBalance":null,
         "interimPayments":null,
         "tetheredGuid":"AB19C8D6-7F0C-420A-B3DE-63C9D562A9D0",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "CARD_HOLDER",
            "ACCOUNT_HOLDER"
         ],
         "errorCode":"Error while retrieving balance"
      },
      {
         "schemeCustomerId":783582,
         "outstanding":null,
         "newTransactions":null,
         "available":null,
         "creditLimit":null,
         "currentBalance":null,
         "interimPayments":null,
         "tetheredGuid":"4B3898F2-0EAC-4065-AE9A-DCBB6F617C2C",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "CARD_HOLDER",
            "ACCOUNT_HOLDER"
         ],
         "errorCode":"Error while retrieving balance"
      },
      {
         "schemeCustomerId":783582,
         "outstanding":null,
         "newTransactions":null,
         "available":null,
         "creditLimit":null,
         "currentBalance":null,
         "interimPayments":null,
         "tetheredGuid":"EECF9F1D-A69E-4D5B-8116-EF3A61E775E7",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "CARD_HOLDER",
            "ACCOUNT_HOLDER"
         ],
         "errorCode":"Error while retrieving balance"
      },
      {
         "schemeCustomerId":783582,
         "outstanding":null,
         "newTransactions":null,
         "available":null,
         "creditLimit":null,
         "currentBalance":null,
         "interimPayments":null,
         "tetheredGuid":"F74A3737-7B64-49BA-AAED-BC977C3B04F1",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "CARD_HOLDER",
            "ACCOUNT_HOLDER"
         ],
         "errorCode":"Error while retrieving balance"
      },
      {
         "schemeCustomerId":783582,
         "outstanding":null,
         "newTransactions":null,
         "available":null,
         "creditLimit":null,
         "currentBalance":null,
         "interimPayments":null,
         "tetheredGuid":"94323209-BC55-4BFA-8AA5-827CAA94DB05",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "CARD_HOLDER",
            "ACCOUNT_HOLDER"
         ],
         "errorCode":"Error while retrieving balance"
      },
      {
         "schemeCustomerId":783582,
         "outstanding":null,
         "newTransactions":null,
         "available":null,
         "creditLimit":null,
         "currentBalance":null,
         "interimPayments":null,
         "tetheredGuid":"3B9F93DE-8AB9-4A38-8581-3F56D7109986",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "CARD_HOLDER",
            "ACCOUNT_HOLDER"
         ],
         "errorCode":"Error while retrieving balance"
      },
      {
         "schemeCustomerId":783582,
         "outstanding":null,
         "newTransactions":null,
         "available":null,
         "creditLimit":null,
         "currentBalance":null,
         "interimPayments":null,
         "tetheredGuid":"1C3252B7-746B-4CC7-B07A-1C59EF007DF4",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "CARD_HOLDER",
            "ACCOUNT_HOLDER"
         ],
         "errorCode":"Error while retrieving balance"
      },
      {
         "schemeCustomerId":783586,
         "outstanding":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "newTransactions":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "available":{
            "amount":1500.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "creditLimit":{
            "amount":1500.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "currentBalance":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "interimPayments":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "tetheredGuid":"48362B2C-8B75-431C-89A8-B3A394CB0996",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "ACCOUNT_HOLDER"
         ]
      },
      {
         "schemeCustomerId":783592,
         "outstanding":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "newTransactions":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "available":{
            "amount":500.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "creditLimit":{
            "amount":500.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "currentBalance":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "interimPayments":{
            "amount":0.0,
            "currencyCode":"GBP",
            "currencySymbol":"£"
         },
         "tetheredGuid":"97BBBCF7-C5CA-4F95-9C8E-3BE3055E333F",
         "accountName":"07788435",
         "accountNumber":"3089503200100301",
         "registrationRoles":[
            "ACCOUNT_HOLDER"
         ]
      }
   ],
   "totalRecordCount":22
}
        ''')
        headers {
            header('Content-Type', 'application/json')
        }
    }
}