package uk.co.whitbread.shared.azureemail.model;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum EmailTemplate {

  PI_FORGOT_PASSWORD("EMAIL0016"),
  BB_FORGOT_PASSWORD("EMAIL0087"),
  BB_FORGOT_PASSWORD_DE("EMAIL0087de"),
  UPDATE_ACCOUNT("EMAIL0014"),
  PI_REGISTER("EMAIL0011"),
  PI_REGISTER_DE("EMAIL0011de"),
  BB_COMPANY_ACTIVATION("EMAIL0080"),
  BB_COMPANY_ACTIVATION_DE("EMAIL0080de"),
  BB_ACTIVATE_ACCOUNT("EMAIL0081"),
  BB_ACTIVATE_ACCOUNT_DE("EMAIL0081de"),
  BB_INVITE_EMPLOYEE("EMAIL0083"),
  BB_INVITE_EMPLOYEE_DE("EMAIL0083de"),
  BB_EMPLOYEE_REGISTRATION_NOTIFICATION("EMAIL0150"),
  BB_EMPLOYEE_REGISTRATION_NOTIFICATION_DE("EMAIL0150de"),
  BB_EMPLOYEE_ACCESS_LEVEL_CHANGE("EMAIL0156"),
  BB_EMPLOYEE_ACCESS_LEVEL_CHANGE_DE("EMAIL0156de"),
  OUT_OF_POLICY_SETUP("EMAIL0084"),
  REQUEST_TO_JOIN_ACCEPTED("EMAIL0151"),
  REQUEST_TO_JOIN_ACCEPTED_DE("EMAIL0151de"),
  REQUEST_TO_JOIN_REJECTED("EMAIL0152"),
  REQUEST_TO_JOIN_REJECTED_DE("EMAIL0152de"),
  PI_ACCOUNT_REGISTRATION("EM_PI_ACCSETUP_001"),
  PI_ACCOUNT_REGISTRATION_DE("EM_PID_ACCSETUP_001"),
  PI_OTP_PASSWORD_RESET("EM_PI_OTPASSWORD_001"),
  PI_OTP_PASSWORD_RESET_DE("EM_PID_OTPASSWORD_001"),
  PI_CHANGE_PASSWORD_CONFIRMATION("EM_PI_PASSWORDCHANGE_001"),
  PI_CHANGE_PASSWORD_CONFIRMATION_DE("EM_PID_PASSWORDCHANGE_001"),
  PI_ACCOUNT_BLOCKED("EM_PI_ACCOUNTBLOCKED_001"),
  PI_ACCOUNT_BLOCKED_DE("EM_PID_ACCOUNTBLOCKED_001");

  private final String templateId;
}