export const TEMPORARY_BASKET_KEY = 'tempBasketKey';
export const INITIAL_CONFIRM_AMEND_ERROR_VALUE = '';
export const INITIAL_CONFIRM_AMEND_ERROR_KEY = 'ConfirmAmendError';

export const AMEND_DEPOSIT_FOLIOS_EXCEPTION_VALUE = 'AMEND_DEPOSIT_FOLIOS_EXCEPTION';
export const AMEND_CONFIRM_EXCEPTION_VALUE = 'AMEND_CONFIRM_EXCEPTION';
export const AMEND_REFUND_EXCEPTION_VALUE = 'AMEND_REFUND_EXCEPTION';
export const AMEND_REVERT_EXCEPTION_VALUE = 'AMEND_REVERT_EXCEPTION';

export const AMEND_3CP_VISITED_KEY = '3cpVisitedAmend';
export const AMEND_3CP_VISITED_INITIAL_VALUE = '';

export const AMEND_A2C_PAYMENT_PATH = '/amend/payment';
