export enum ActionContextKeys {
  GET_SAVED_PACKAGES_OPERA = 'GET_SAVED_PACKAGES_OPERA',
  GET_BOOKING_INFO_AEM = 'GET_BOOKING_INFO_AEM',
  GET_MEALS_AEM = 'GET_MEALS_AEM',
  GET_LOGO_AEM = 'GET_LOGO_AEM',
  GET_PACKAGES_OPERA = 'GET_PACKAGES_OPERA',
  GET_HOTEL_INFORMATION = 'GET_HOTEL_INFORMATION'
}
