export enum ActionContextKeys {
  BOOKING_FLOW_ID = 'BOOKING_FLOW_ID',
  BOOKING_INFO_MESSAGES = 'BOOKING_INFO_MESSAGES',
  BOOKING_INFORMATION_BY_BASKET = 'BOOKING_INFORMATION_BY_BASKET',
  HOTEL_INFORMATION_FOR_BOOKING = 'HOTEL_INFORMATION_FOR_BOOKING',
  RATE_INFORMATION = 'RATE_INFORMATION',
  ROOM_TYPE = 'ROOM_TYPE'
}
