/* Recommendation: Use UPPERCASE for page names. This is added as an experimental way to have everything w.r.t. Pages, associated Feature Flags, etc at one place. This needs to be taken care of by everyone from the next time/when you refactor
 */
import {
  FT_BB_GROUP_BOOKING_FORM,
  FT_PI_BB_CCUI_TRIP_ADVISOR,
  FT_BB_ACCOMPANYING_GUEST_DETAILS,
  FT_PI_BB_CCUI_COMPANY_NAME_SPECIAL_CHARACTERS,
  FT_PI_BB_CCUI_NONSILENT_SUBSTITUTION_PER_ROOMCLASS,
  FT_PI_BB_CCUI_MAXROOMS_AMEND,
  FT_BB_ENABLE_PAYPAL,
  FT_BB_ENABLE_PAYMENT_REDESIGN,
  FT_PI_BB_CCUI_DISABLE_PAYMENTS,
  FT_PI_CCUI_BB_PREM_PLUS_ACCESSIBLE,
  FT_PI_BB_CCUI_ROOMS_DISCLAIMER,
  FT_BB_SORT_ORDER_DROPDOWN,
  FT_PI_BB_CCUI_BARRIER_FREE_LABEL,
  FT_BB_PRICE_PER_NIGHT,
  FT_PI_BB_NON_GUARANTEED_REMINDER,
  FT_PI_BB_ACCOUNT_SERV_TO_SERV,
  FT_PI_BB_CCUI_CHOOSE_ROOM_TYPE,
  FT_BB_ROOM_UPGRADE_POPUP,
  FT_PI_BB_CANCELLATION_POLICY,
  FT_IB_USER_PILOT,
  FT_PI_BB_CCUI_SHOW_MEALS_FREE,
  FT_PI_BB_CCUI_HDP_IMAGE_GALLERY_REDESIGN,
  FT_PI_BB_CCUI_SRP_MULTIPLE_IMAGES,
  FT_PI_SIGNUP_IN_HEADER,
  FT_PI_PRICE_FINDER_SEO_NOINDEX,
  FT_PI_BB_BOOKING_HISTORY_REDESIGN,
  FT_BB_SHOW_PROMOTION_BOX,
  FT_IB_REDIRECT_AFTER_LOGIN,
  FT_PI_PIB_CCUI_SHOW_LOWEST_PRICE_MONTH_TAB,
  FT_PI_PIB_CCUI_SHOW_FILTER_ROOM_TYPES,
  FT_BB_PROMO_CODE_LANDING_PAGE,
  FT_BB_PROMO_CODE_SITE_WIDE,
  FT_PI_PIB_SWAP_PAYMENT_OPTIONS,
  FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN,
  FT_PI_PIB_PAYMENT_BACK_TO_OPTIONS_LINK,
  FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN_ANCILLARIES_GDP_PAYMENT,
  FT_PI_PIB_CCUI_CITY_TAX_AMEND,
  FT_PI_PIB_CCUI_ENABLE_HUB_HOTELS_POA,
  FT_PI_PIB_BIC_DOWNLOAD_INVOICE,
  FT_PI_BB_CONTROLS_MOBILE_DISPLAY,
  FT_PI_BB_SHOW_GOOGLE_STATIC_MAP,
  FT_BB_FREE_FNB_AND_EXTRAS,
  FT_SRP_DYNAMIC_FILTERS,
  FT_PI_CCUI_BB_PROMOTION_BOX_CODE_COOKIE,
  FT_PI_BB_CCUI_PROMOTIONS_IN_HOTELAVAILABILITY,
  FT_SEMANTIC_TYPOGRAPHY_TOKENIZATION,
  FT_PI_REDIS_RQ_CACHE,
  FT_DYNATRACE_RUM_COOKIE_CONSENT,
  FT_ONE_TRUST_COOKIE_CONSENT,
} from '@whitbread-eos/api';

export const PAYMENT_NAVIGATION_SOURCE_QUERY_PARAM = 'from';
export const PAYMENT_NAVIGATION_SOURCE_GUEST_DETAILS = 'guest-details';

//  A collection of feature toggles that are common to both HDP and SRP.
const commonFeatureToggles = {
  [FT_PI_BB_CCUI_TRIP_ADVISOR]: false,
  [FT_BB_GROUP_BOOKING_FORM]: false,
  [FT_PI_BB_CCUI_NONSILENT_SUBSTITUTION_PER_ROOMCLASS]: false,
  [FT_PI_CCUI_BB_PREM_PLUS_ACCESSIBLE]: false,
  [FT_PI_BB_CCUI_ROOMS_DISCLAIMER]: false,
  [FT_BB_SORT_ORDER_DROPDOWN]: false,
  [FT_PI_BB_CCUI_BARRIER_FREE_LABEL]: false,
  [FT_PI_BB_CCUI_CHOOSE_ROOM_TYPE]: false,
  [FT_BB_PRICE_PER_NIGHT]: false,
  [FT_BB_ROOM_UPGRADE_POPUP]: false,
  [FT_IB_USER_PILOT]: false,
  [FT_PI_BB_CCUI_SHOW_MEALS_FREE]: false,
  [FT_PI_BB_CCUI_HDP_IMAGE_GALLERY_REDESIGN]: false,
  [FT_IB_REDIRECT_AFTER_LOGIN]: false,
  [FT_BB_PROMO_CODE_LANDING_PAGE]: false,
  [FT_BB_PROMO_CODE_SITE_WIDE]: false,
  [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN]: false,
  [FT_PI_CCUI_BB_PROMOTION_BOX_CODE_COOKIE]: false,
  [FT_PI_BB_CCUI_PROMOTIONS_IN_HOTELAVAILABILITY]: false,
  [FT_PI_REDIS_RQ_CACHE]: false,
  [FT_ONE_TRUST_COOKIE_CONSENT]: false,
};

const globalFeatureToggles = {
  [FT_DYNATRACE_RUM_COOKIE_CONSENT]: false,
  [FT_SEMANTIC_TYPOGRAPHY_TOKENIZATION]: false,
};

export const PAGE = {
  HDP: {
    featureToggles: {
      appPage: 'BB | HDP | Hotel Details Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        ...commonFeatureToggles,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN]: false,
        [FT_PI_BB_SHOW_GOOGLE_STATIC_MAP]: false,
        [FT_BB_SHOW_PROMOTION_BOX]: false,
      },
    },
  },
  SRP: {
    featureToggles: {
      appPage: 'BB | SRP | Search Results Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        ...commonFeatureToggles,
        [FT_PI_BB_CCUI_SRP_MULTIPLE_IMAGES]: false,
        [FT_PI_BB_CONTROLS_MOBILE_DISPLAY]: false,
        [FT_SRP_DYNAMIC_FILTERS]: false,
      },
    },
  },
  GDP: {
    featureToogles: {
      appPage: 'BB | GDP Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_BB_ACCOMPANYING_GUEST_DETAILS]: false,
        [FT_PI_BB_CANCELLATION_POLICY]: false,
        [FT_PI_BB_CCUI_SHOW_MEALS_FREE]: false,
        [FT_BB_PROMO_CODE_LANDING_PAGE]: false,
        [FT_BB_PROMO_CODE_SITE_WIDE]: false,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN]: false,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN_ANCILLARIES_GDP_PAYMENT]: false,
        [FT_BB_FREE_FNB_AND_EXTRAS]: false,
        [FT_ONE_TRUST_COOKIE_CONSENT]: false,
      },
    },
  },
  DASHBOARD: {
    featureToogles: {
      appPage: 'BB | Dashboard Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_BB_CCUI_BARRIER_FREE_LABEL]: false,
        [FT_PI_BB_NON_GUARANTEED_REMINDER]: false,
        [FT_IB_USER_PILOT]: false,
        [FT_PI_BB_CCUI_SHOW_MEALS_FREE]: false,
        [FT_PI_BB_BOOKING_HISTORY_REDESIGN]: false,
        [FT_IB_REDIRECT_AFTER_LOGIN]: false,
        [FT_BB_PROMO_CODE_LANDING_PAGE]: false,
        [FT_BB_PROMO_CODE_SITE_WIDE]: false,
        [FT_PI_PIB_BIC_DOWNLOAD_INVOICE]: false,
        [FT_PI_BB_CCUI_PROMOTIONS_IN_HOTELAVAILABILITY]: false,
        [FT_PI_REDIS_RQ_CACHE]: false,
        [FT_ONE_TRUST_COOKIE_CONSENT]: false,
      },
    },
  },
  AMEND: {
    featureToggles: {
      appPage: 'BB | Amend Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_BB_CCUI_MAXROOMS_AMEND]: false,
        [FT_PI_BB_NON_GUARANTEED_REMINDER]: false,
        [FT_IB_USER_PILOT]: false,
        [FT_PI_BB_CCUI_SHOW_MEALS_FREE]: false,
        [FT_BB_PROMO_CODE_LANDING_PAGE]: false,
        [FT_BB_PROMO_CODE_SITE_WIDE]: false,
        [FT_PI_BB_CCUI_PROMOTIONS_IN_HOTELAVAILABILITY]: false,
        [FT_PI_REDIS_RQ_CACHE]: false,
        [FT_ONE_TRUST_COOKIE_CONSENT]: false,
        [FT_PI_PIB_CCUI_CITY_TAX_AMEND]: false,
      },
    },
  },
  PAYMENT: {
    featureToggles: {
      appPage: 'BB | Payment Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_BB_ENABLE_PAYPAL]: false,
        [FT_BB_ENABLE_PAYMENT_REDESIGN]: false,
        [FT_PI_BB_CCUI_COMPANY_NAME_SPECIAL_CHARACTERS]: false,
        [FT_PI_BB_CCUI_DISABLE_PAYMENTS]: false,
        [FT_PI_BB_NON_GUARANTEED_REMINDER]: false,
        [FT_IB_USER_PILOT]: false,
        [FT_BB_PROMO_CODE_LANDING_PAGE]: false,
        [FT_BB_PROMO_CODE_SITE_WIDE]: false,
        [FT_PI_PIB_SWAP_PAYMENT_OPTIONS]: false,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN]: false,
        [FT_PI_PIB_PAYMENT_BACK_TO_OPTIONS_LINK]: false,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN_ANCILLARIES_GDP_PAYMENT]: false,
        [FT_PI_PIB_CCUI_ENABLE_HUB_HOTELS_POA]: false,
        [FT_PI_REDIS_RQ_CACHE]: false,
        [FT_ONE_TRUST_COOKIE_CONSENT]: false,
      },
    },
  },
  CHOOSE_ROOMTYPE: {
    featureToggles: {
      appPage: 'BB | Choose Roomtype Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_BB_ACCOUNT_SERV_TO_SERV]: false,
        [FT_PI_CCUI_BB_PREM_PLUS_ACCESSIBLE]: false,
        [FT_PI_BB_CCUI_CHOOSE_ROOM_TYPE]: false,
        [FT_BB_PROMO_CODE_LANDING_PAGE]: false,
        [FT_BB_PROMO_CODE_SITE_WIDE]: false,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN]: false,
        [FT_PI_REDIS_RQ_CACHE]: false,
        [FT_ONE_TRUST_COOKIE_CONSENT]: false,
      },
    },
  },
  PRICE_FINDER: {
    featureToggles: {
      appPage: 'BB | Price Finder Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_SIGNUP_IN_HEADER]: false,
        [FT_PI_PRICE_FINDER_SEO_NOINDEX]: false,
        [FT_PI_PIB_CCUI_SHOW_LOWEST_PRICE_MONTH_TAB]: false,
        [FT_IB_REDIRECT_AFTER_LOGIN]: false,
        [FT_PI_PIB_CCUI_SHOW_FILTER_ROOM_TYPES]: false,
        [FT_PI_REDIS_RQ_CACHE]: false,
        [FT_ONE_TRUST_COOKIE_CONSENT]: false,
      },
    },
  },
  CONFIRMATION: {
    featureToggles: {
      appPage: 'BB | Confirmation Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN]: false,
        [FT_BB_PROMO_CODE_LANDING_PAGE]: false,
        [FT_BB_PROMO_CODE_SITE_WIDE]: false,
        [FT_PI_BB_NON_GUARANTEED_REMINDER]: false,
        [FT_PI_BB_SHOW_GOOGLE_STATIC_MAP]: false,
        [FT_ONE_TRUST_COOKIE_CONSENT]: false,
        [FT_PI_REDIS_RQ_CACHE]: false,
      },
    },
  },
  RESET_PASSWORD: {
    featureToggles: {
      appPage: 'BB | Reset Password Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_REDIS_RQ_CACHE]: false,
      },
    },
  },
};
