package com.whitbread.premierinn.api


// Booking Error Codes
const val BOOKING_PAYMENT_DECLINED = "HB1"
const val BOOKING_PAYMENT_NOT_FOUND = "HB2"
const val BOOKING_PAYMENT_GENERAL = "HB3"
const val BOOKING_BART_SESSION_TIME_OUT = "HB4"
const val BOOKING_PAYMENT_AMOUNT_CONFLICT = "HB5"
const val BOOKING_PAYMENT_TRANSACTION_REFUND = "HB6"
const val BOOKING_PAYMENT_FRAUD_CHECK = "HB7"


// Payment Error codes
const val PAYMENT_UNKOWN_ERROR = 0
const val PAYMENT_VALIDATION_ERROR = 1
const val PAYMENT_MS_PROVIDER_ACCOUNT_NOT_FOUND = 2
const val PAYMENT_TEMPLATE_ERROR = 3
const val PAYMENT_UNABLE_TO_PARSE_PROVIDER_RESPONSE = 4
const val PAYMENT_ERROR_HANDLING_REQUEST = 5
const val PAYMENT_PROVIDER_ERROR = 6
const val PAYMENT_UNAUTHORISED = 7
const val PAYMENT_PAYMENT_NOT_FOUND = 8
const val PAYMENT_UNABLE_TO_REFUND = 9
const val PAYMENT_WEB_2_PAY_TIME_OUT = 10