@startuml

title Forgot password

actor User
participant "Whitbread page" as Client
participant "GraphQL Layer" as gql
participant "Hotel Account Service" as HAS
participant "Auth0" as AUT
participant "CDH" as CDH
participant "Azure Emailing Service" as AZ

User -> Client: Navigates to Forgot password page
Client -> gql: Mutation forgotPassword
gql -> HAS: POST /auth/hotels/forgot-password\n(e-mail address)\n(business flag)
alt business
    HAS -> AUT: Get Auth0 user by e-mail address
    AUT --> HAS: Return user
    alt user exists in Auth0
      HAS -> CDH: Get /AccountServices/V1/employees by e-mail address
      CDH --> HAS: Return user
      alt user exists in CDH
        HAS -> HAS: Generate reset key
        HAS -> HAS: Generate reset URL InnBusiness
        HAS -> AUT: Save reset key & its expiry time - for user
        HAS -> AZ: Send reset password e-mail with reset key
      else user not found
        HAS -> HAS: Log warn & return success=true\n(Security - avoid leaking info on existing users)
      end
    else user not found
      HAS -> HAS: Log warn & return success=true\n(Security - avoid leaking info on existing users)
    end
else leisure flow
    HAS -> HAS: Generate reset key
    HAS -> AUT: Save reset key & its expiry time - for user
    HAS -> AZ: Send reset password e-mail with reset key

end

HAS -> gql: Success
gql -> Client: Success
Client -> User: Success

@enduml