@startuml
actor User
participant "Whitbread FE page" as FE
participant "Hotel Account Microservice" as MS
User -> FE: Forgot Password
FE -> MS: Forgot Password request
MS -> MS: Generate reset token
MS -> Auth0: Save the token and its expiry time
MS -> MailingService: Send email with reset link containing the token
User <- MailingService: Email sent with reset link containing the token
User -> User: Open reset link
User -> FE: Enter new password
FE -> MS: Reset password request
MS -> MS: Check token validity
opt If Valid token
  MS -> Auth0: Update password & Remove token and expiry time
end
opt If Invalid token
  MS -> FE: Invalid token error
end
@enduml