@startuml
actor User
participant "Reset Password Page" as RP
participant "Hotel Account Microservice" as MS
User -> RP: Reset Password
RP -> MS: Reset Password request
MS -> Auth0: Get reset link
MS <- Auth0: Return link
MS -> MailingService: Send email with reset link
MS <- MailingService: Sent email OK (if user found in Auth0)
RP <- MS: Display notification
User <- MailingService: Email sent with reset link
@enduml