<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>uk.co.whitbread</groupId>
    <artifactId>digital-monorepo-service-parent</artifactId>
    <version>${revision}</version>
    <relativePath>../../../parents/service-parent/pom.xml</relativePath>
  </parent>

  <artifactId>hotel-wallet-service-opera</artifactId>
  <packaging>jar</packaging>

  <properties>
    <application.port>9131</application.port>
    <pact-contract-test.version>4.6.8</pact-contract-test.version>
    <sonar.coverage.jacoco.xmlReportPaths>${project.basedir}/target/site/jacoco-all/jacoco.xml
    </sonar.coverage.jacoco.xmlReportPaths>
    <sonar.coverage.exclusions>
      **/model/**,
      **/properties/**,
      **/config/**,
      **/mapper/**,
      **/exception/**,
      **/exceptions/**,
      **/properties/**,
      **/generated/**,
      **WalletServiceApplication*
    </sonar.coverage.exclusions>
  </properties>

  <name>hotel-wallet-service-opera</name>
  <description>Hotel Wallet Service</description>

  <dependencies>

    <!-- Whitbread -->
    <dependency>
      <groupId>commons-validator</groupId>
      <artifactId>commons-validator</artifactId>
    </dependency>

    <dependency>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-annotations-jakarta</artifactId>
    </dependency>

    <dependency>
      <groupId>uk.co.whitbread.shared</groupId>
      <artifactId>common-auth0</artifactId>
      <exclusions>
        <exclusion>
          <groupId>uk.co.whitbread.shared</groupId>
          <artifactId>commons-entity-exceptions</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-security</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.nimbusds</groupId>
          <artifactId>nimbus-jose-jwt</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <!-- Spring/SpringBoot -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webservices</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-micrometer-tracing-brave</artifactId>
    </dependency>

    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webflux</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security-oauth2-client</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security-oauth2-resource-server</artifactId>
    </dependency>

    <dependency>
      <groupId>com.nimbusds</groupId>
      <artifactId>nimbus-jose-jwt</artifactId>
    </dependency>

    <dependency>
      <groupId>org.thymeleaf</groupId>
      <artifactId>thymeleaf</artifactId>
    </dependency>
    <dependency>
      <groupId>org.thymeleaf</groupId>
      <artifactId>thymeleaf-spring6</artifactId>
    </dependency>

    <dependency>
      <groupId>de.brendamour</groupId>
      <artifactId>jpasskit</artifactId>
      <exclusions>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>*</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.fasterxml.jackson.datatype</groupId>
          <artifactId>*</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.commons</groupId>
          <artifactId>*</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.slf4j</groupId>
          <artifactId>*</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>*</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.bouncycastle</groupId>
          <artifactId>bcprov-jdk18on</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>org.jsoup</groupId>
      <artifactId>jsoup</artifactId>
    </dependency>

    <!-- AWS -->
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-core</artifactId>
      <exclusions>
        <exclusion>
          <groupId>commons-logging</groupId>
          <artifactId>commons-logging</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-s3</artifactId>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-sts</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
    </dependency>

    <dependency>
      <groupId>org.openapitools</groupId>
      <artifactId>jackson-databind-nullable</artifactId>
    </dependency>

    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jsr310</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-jackson2</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-properties-migrator</artifactId>
      <scope>runtime</scope>
    </dependency>

    <dependency>
      <groupId>com.arcmutate</groupId>
      <artifactId>arcmutate-spring</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-contract-wiremock</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>com.squareup.okhttp3</groupId>
      <artifactId>okhttp</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>com.squareup.okhttp3</groupId>
      <artifactId>mockwebserver</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.modelmapper</groupId>
      <artifactId>modelmapper</artifactId>
    </dependency>

    <!-- Contract Testing -->
    <dependency>
      <groupId>au.com.dius.pact.consumer</groupId>
      <artifactId>junit5</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>au.com.dius.pact.provider</groupId>
      <artifactId>junit5spring</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>

  <build>
    <plugins>

      <!--spring-boot-maven-plugin is needed by springdoc-openapi-maven-plugin to generate OpenAPI yaml description -->
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <jvmArguments>-Dspring.application.admin.enabled=true</jvmArguments>
        </configuration>
        <executions>
          <execution>
            <id>pre-integration-test</id>
            <goals>
              <goal>start</goal>
            </goals>
          </execution>
          <execution>
            <id>post-integration-test</id>
            <goals>
              <goal>stop</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <!--Used to generate OpenAPI yaml description -->
      <plugin>
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>integration-test</id>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <apiDocsUrl>http://localhost:${application.port}/v3/api-docs.yaml</apiDocsUrl>
          <outputFileName>${project.name}-openApi.yaml</outputFileName>
          <outputDir>${basedir}/docs/openApi</outputDir>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>**/uk/co/whitbread/wallet/WalletServiceApplication*</exclude>
            <exclude>**/uk/co/whitbread/**/model/**</exclude>
            <exclude>**/uk/co/whitbread/**/config/**</exclude>
            <exclude>**/uk/co/whitbread/**/mapper/**</exclude>
            <exclude>**/uk/co/whitbread/**/exception/**</exclude>
            <exclude>**/uk/co/whitbread/**/exceptions/**</exclude>
            <exclude>**/uk/co/whitbread/**/properties/**</exclude>
            <exclude>**/uk/co/whitbread/**/generated/**</exclude>
          </excludes>
        </configuration>
        <executions>
          <execution>
            <id>controller-integration</id>
            <phase>post-integration-test</phase>
            <goals>
              <goal>merge</goal>
            </goals>
            <configuration>
              <fileSets>
                <fileSet>
                  <directory>${basedir}/target/</directory>
                  <includes>
                    <include>jacoco-it.exec</include>
                  </includes>
                </fileSet>
              </fileSets>
              <destFile>${basedir}/target/jacoco-controller.exec</destFile>
            </configuration>
          </execution>
          <execution>
            <id>after-integration-test-execution</id>
            <phase>post-integration-test</phase>
            <goals>
              <goal>report</goal>
            </goals>
            <configuration>
              <includes>
                <include>**/uk/co/whitbread/**/controller/**/*Controller.class</include>
              </includes>
              <dataFile>${basedir}/target/jacoco-controller.exec</dataFile>
              <outputDirectory>${basedir}/target/site/jacoco-controller/</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>merge-unit-and-integration</id>
            <phase>post-integration-test</phase>
            <goals>
              <goal>merge</goal>
            </goals>
            <configuration>
              <fileSets>
                <fileSet>
                  <directory>${basedir}/target/</directory>
                  <includes>
                    <include>jacoco.exec</include>
                    <include>jacoco-controller.exec</include>
                  </includes>
                </fileSet>
              </fileSets>
              <destFile>${basedir}/target/jacoco-all.exec</destFile>
            </configuration>
          </execution>
          <execution>
            <id>create-merged-report</id>
            <phase>post-integration-test</phase>
            <goals>
              <goal>report</goal>
            </goals>
            <configuration>
              <dataFile>${basedir}/target/jacoco-all.exec</dataFile>
              <outputDirectory>${basedir}/target/site/jacoco-all/</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>reservation</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <skipValidateSpec>true</skipValidateSpec>
              <inputSpec>
                ${project.basedir}/src/main/resources/openapi/reservation-service-openapi.yaml
              </inputSpec>
              <generatorName>spring</generatorName>
              <modelPackage>uk.co.whitbread.hotel.generated.models.reservation</modelPackage>
              <typeMappings>
                <typeMapping>OffsetDateTime=Date</typeMapping>
              </typeMappings>
              <importMappings>
                <importMapping>java.time.OffsetDateTime=java.util.Date</importMapping>
              </importMappings>
              <generateApis>false</generateApis>
              <generateApiDocumentation>false</generateApiDocumentation>
              <generateModelDocumentation>false</generateModelDocumentation>
              <generateSupportingFiles>false</generateSupportingFiles>
            </configuration>
          </execution>
          <execution>
            <id>basket</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <skipValidateSpec>true</skipValidateSpec>
              <inputSpec>
                ${project.basedir}/src/main/resources/openapi/basket-service-api.yaml
              </inputSpec>
              <generatorName>spring</generatorName>
              <modelPackage>uk.co.whitbread.hotel.generated.models.basket
              </modelPackage>
              <typeMappings>
                <typeMapping>OffsetDateTime=Date</typeMapping>
              </typeMappings>
              <importMappings>
                <importMapping>java.time.OffsetDateTime=java.util.Date</importMapping>
              </importMappings>
              <generateApis>false</generateApis>
              <generateApiDocumentation>false</generateApiDocumentation>
              <generateModelDocumentation>false</generateModelDocumentation>
              <generateSupportingFiles>false</generateSupportingFiles>
            </configuration>
          </execution>
          <execution>
            <id>content</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <skipValidateSpec>true</skipValidateSpec>
              <inputSpec>
                ${project.basedir}/src/main/resources/openapi/content-service-openapi.yaml
              </inputSpec>
              <generatorName>spring</generatorName>
              <modelPackage>uk.co.whitbread.basket.generated.models.content</modelPackage>
              <typeMappings>
                <typeMapping>OffsetDateTime=Date</typeMapping>
              </typeMappings>
              <importMappings>
                <importMapping>java.time.OffsetDateTime=java.util.Date</importMapping>
              </importMappings>
              <generateApis>false</generateApis>
              <generateApiDocumentation>false</generateApiDocumentation>
              <generateModelDocumentation>false</generateModelDocumentation>
              <generateSupportingFiles>false</generateSupportingFiles>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.google.code.maven-replacer-plugin</groupId>
        <artifactId>replacer</artifactId>
        <executions>
          <execution>
            <id>replace-import-javax-by-jakarta</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>replace</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <basedir>
            ${project.basedir}/target/generated-sources
          </basedir>
          <includes>
            <include>**/*.java</include>
          </includes>
          <replacements>
            <replacement>
              <token>import javax</token>
              <value>import jakarta</value>
            </replacement>
          </replacements>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.pitest</groupId>
        <artifactId>pitest-maven</artifactId>
        <configuration>
          <excludedClasses>
            <param>uk.co.whitbread.wallet.WalletServiceApplication</param>
          </excludedClasses>
          <excludedTestClasses>
            <excludedTestClass>
              uk.co.whitbread.wallet.ArchUnitTests
            </excludedTestClass>
          </excludedTestClasses>
        </configuration>
      </plugin>

      <plugin>
        <groupId>au.com.dius.pact.provider</groupId>
        <artifactId>maven</artifactId>
        <version>${pact-contract-test.version}</version>
        <configuration>
          <pactBrokerUrl>http://pact-broker.pact-broker/</pactBrokerUrl>
        </configuration>
      </plugin>

      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <systemPropertyVariables>
            <pact.provider.version>${project.version}</pact.provider.version>
            <pact.verifier.publishResults>true</pact.verifier.publishResults>
          </systemPropertyVariables>
        </configuration>
      </plugin>

    </plugins>
  </build>

</project>
