//
//  BathroomSelectionView.swift
//  PremierInn
//
//
//  Created Nick Jones on 04/07/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit

import Formeka
import SimpleNetwork

class BathroomSelectionViewController: BaseViewController {
    override var screenName: String { PIAnalytics.StateNames.chooseRooms }
    override var screenType: String { PIAnalytics.StateTypes.bookingFlow }
    override var customParameters: [String: Any]? {
        let data = customTrackingParameters

        return data
    }

    var customTrackingParameters: PIDictionary = [:]

    @IBOutlet weak var table: UITableView! {
        didSet {
            table.rowHeight = UITableView.automaticDimension
            table.estimatedRowHeight = 150
            table.backgroundColor = .whiteTwo
            table.tableHeaderView = UIView(frame: CGRect(x: 0, y: 0, width: 0, height: CGFloat.leastNormalMagnitude))
            table.separatorStyle = .none
            table.accessibilityIdentifier = "tableView"

            registerNibs()
        }
    }

    @IBOutlet weak var continueContainer: UIView! {
        didSet {
            continueContainer.set(hasHeaderFooterShadow: true)
        }
    }

    @IBOutlet weak var totalSubButton: UIButton! {
        didSet {
            totalSubButton.contentHorizontalAlignment = .left
            totalSubButton.titleLabel?.font = UIFont.BodySmall()
            totalSubButton.setTitle(PILocalizedString("subButtonFooterBathroom"), for: .normal)
        }
    }

    @IBOutlet weak var total: UILabel! {
        didSet {
            total.font = UIFont.Heading2_Semibold()
        }
    }

    @IBAction func breakdownButtonDidTap(_ sender: Any) {
        eventHandler?.summaryButtonDidTap()
    }

    @IBOutlet weak var continueButton: UIButton! {
        didSet {
            continueButton.setTitleColor(.BaseWhite, for: .normal)
            continueButton.backgroundColor = .Tint1
            continueButton.contentHorizontalAlignment = .center
            continueButton.titleLabel?.font = .Button1()
            continueButton.setTitle(PILocalizedString("bookingReviewContinueButtonTitle"), for: .normal)
        }
    }
    @IBOutlet weak var continueButtonSpinner: UIActivityIndicatorView! {
        didSet {
            continueButtonSpinner.isHidden = true
        }
    }

    var eventHandler: BathroomSelectionViewEventHandler?

    private var viewModel: FormekaViewModel?

    override func viewDidLoad() {
        super.viewDidLoad()

        title = PILocalizedString("bathroomSelectionScreenTitle", comment: "Bathroom selection: screen title")

        eventHandler?.viewIsReady()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)

        navigationController?.setNavigationBarHidden(false, animated: animated)

        eventHandler?.viewIsAppearing()
    }

    private func registerNibs() {
        table.registerCellNib(with: BathroomOptionCell.self)
        table.registerCellNib(with: SimpleSubtitleCell.self)
        table.registerCellNib(with: DottedSeparatorCell.self)
        table.registerCellNib(with: FlexibleContentInformationCell.self)
        table.registerCellNib(with: FlexibleTextContentCell.self)
        table.registerCellNib(with: CarouselCell.self)
        table.registerCellNib(with: BathroomSelectionHeaderCell.self)
        table.registerHeaderFooterNib(with: SimpleFooter.self)
    }

    @IBAction func continueButtonDidTap(_ sender: Any) {
        eventHandler?.continueButtonDidTap()
    }

    @objc func tappedChangedRoom(atIndex index: Int) {
        eventHandler?.tappedChange(withIndex: index)
    }
}

extension BathroomSelectionViewController: BathroomSelectionViewProtocol {
    func enableContinueButton() {
        continueButton.isEnabled = true
        continueButton.isUserInteractionEnabled = true
        continueButton.setTitle(PILocalizedString("Continue"), for: .normal)
        continueButtonSpinner.isHidden = true
        continueButtonSpinner.stopAnimating()
    }

    func disableContinueButton() {
        continueButton.isEnabled = false
        continueButton.isUserInteractionEnabled = false
        continueButton.setTitle("", for: .normal)
        continueButtonSpinner.isHidden = false
        continueButtonSpinner.startAnimating()
    }

    func update(withViewModel viewModel: BathroomSelectionViewModel) {
        self.viewModel = self.tableViewModel(with: viewModel)
        table.delegate = self.viewModel
        table.dataSource = self.viewModel

        total.text = BookingDetails.sharedInstance.totalCost.localizedValue

        table.reloadData()
    }

    func errorOccured() {
        let alertController = UIAlertController(
            title: PILocalizedString("bathroomSelectionFailMessage"),
            message: nil,
            preferredStyle: .alert
        )
        alertController.addAction(UIAlertAction(title: PILocalizedString("Cancel"), style: .cancel, handler: nil))
        alertController.addAction(UIAlertAction(title: PILocalizedString("OK"), style: .default, handler: nil))

        present(alertController, animated: true)

        NotificationFeedbackManager.shared.provideFeedback(for: .error)
    }
}
