//
//  BathroomSelectionRouter.swift
//  PremierInn
//
//
//  Created Nick Jones on 04/07/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit
import SimpleNetwork

class BathroomSelectionRouter: BathroomSelectionRouterProtocol {
    var view: UIViewController?
    var presenter: BathroomSelectionViewEventHandler?

    func showHoldRateError() {
        let controller = UIAlertController(
            title: PILocalizedString("holdBookingErrorAlertTitle", comment: "Hold booking error alert title"),
            message: PILocalizedString("holdBookingErrorAlertMessage", comment: "Hold booking error alert message"),
            preferredStyle: .alert
        )
        controller.addAction(UIAlertAction(
            title: PILocalizedString("holdBookingErrorAlertAction", comment: "Hold booking error alert action"),
            style: .cancel
        ) { _ in
            self.goBackToResultsScreenIfPossible()
        })

        view?.present(controller, animated: true)
    }

    func goBackToResultsScreenIfPossible() {
        guard let viewController = self.view else { return }

        // If there's a results list, pop to that
        if let resultsController = viewController.navigationController?.viewControllers
           .first(where: { $0 is MapListContainerViewController }) {
            viewController.navigationController?.popToViewController(resultsController, animated: true)
            return
        }

        // Otherwise pop to the root
        viewController.navigationController?.popToRootViewController(animated: true)
    }

    func moveToNextScreen(withUpsellsAvailable upsellsAvailable: Bool) {
        let controllerToPresent = nextController(with: upsellsAvailable, and: BookingDetails.sharedInstance)

        view?.navigationController?.pushViewController(controllerToPresent, animated: true)
    }

    func nextController(with upsellsAvailable: Bool, and bookingDetails: BookingDetails) -> UIViewController {
        let isBBFlow = bookingDetails.bookingMode == .business

        switch  (upsellsAvailable, isBBFlow) {
        case (true, _):
            return UpsellsModule.build(with: bookingDetails)
        case (false, false):
            return UserDetailsRouter.buildController(
                bookingDetails: BookingDetails.sharedInstance,
                loggedUser: UserSessionManager.sharedInstance.currentUser,
                scope: .bookingFlow,
                delegate: nil
            )
        case (false, true):
            guard bookingDetails.shouldShowEmployeeQuestionsForOpera
                else { return ReviewAndBookRouter.build(with: bookingDetails) }
            guard let questions = UserSessionManager.sharedInstance.currentUser?.company?.businessCardQuestions,
                  questions.isNotEmpty else { return ReviewAndBookRouter.build(with: bookingDetails) }
            let businessController = BusinessCardQuestionsRouter.build(with: questions, isModal: false)
            businessController.delegate = self
            return businessController
        }
    }

    func showAccessibleRoomTypeSelection(
        with roomTypes: [AccessibleRoomType],
        andPreselected preselected: AccessibleRoomType
    ) {
        let vc = RoomTypeSelectModule.buildAccessibleSelection(with: roomTypes, selectedRoomType: preselected, and: self)
        vc.view.frame = view?.view.bounds ?? CGRect.zero

        view?.addChild(vc)
        view?.view.addSubview(vc.view)
    }

    func showSummary(with bookingDetails: BookingDetails) {
        let controller = BookingSummaryRouter.build(hotel: nil, bookingDetails: bookingDetails, reservation: nil)
        controller.hidesBottomBarWhenPushed = true

        view?.navigationController?.pushViewController(controller, animated: true)
    }
}

extension BathroomSelectionRouter: RoomTypeSelectRouterDelegate {
    func roomTypeSelectViewControllerDidUpdate(roomType: SelectableRoomType) {
        guard let accessibleRoomType = roomType as? AccessibleRoomType else { return }

        presenter?.userSelectedNewRoomType(accessibleRoomType)
    }
}

extension BathroomSelectionRouter: BusinessCardQuestionsDelegate {
    func submitBusinessCardQuestions(questions: [BusinessCardQuestionAndAnswer]) {
        BookingDetails.sharedInstance.businessCardQuestionsAndAnswers = questions

        let controller: UIViewController = {
            if BookingDetails.sharedInstance.bookingMode == .business {
                return ReviewAndBookRouter.build(with: BookingDetails.sharedInstance)
            }

            return UserDetailsRouter.buildController(
                bookingDetails: BookingDetails.sharedInstance,
                loggedUser: UserSessionManager.sharedInstance.currentUser,
                scope: .bookingFlow,
                delegate: nil
            )
        }()

        view?.navigationController?.pushViewController(controller, animated: true)
    }
}
