//
//  BathroomSelectionModule.swift
//  PremierInn
//
//  Created Nick Jones on 04/07/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit
import SimpleNetwork

enum BathrooomSelectionModule {
    static func buildModule(
        with rooms: [Room],
        accessibleRoomImages: [URL],
        twinRoomImages: [URL],
        and productString: String = ""
    ) -> UIViewController {
        let viewController = BathroomSelectionViewController()
        viewController.eventHandler = {
            let router = BathroomSelectionRouter()
            router.view = viewController

            let interactor = BathroomSelectionInteractor(
                with: rooms,
                accessibleRoomImages: accessibleRoomImages,
                twinRoomImages: twinRoomImages,
                and: productString
            )
            viewController.customTrackingParameters = interactor.customTrackingDictionary

            let presenter = BathroomSelectionPresenter(with: interactor)

            router.presenter = presenter

            presenter.router = router
            presenter.view = viewController

            interactor.presenter = presenter

            return presenter
        }()

        return viewController
    }
}

struct BathroomSelectionViewModel {
    var accessibleRoomImageURLs: [URL]
    var twinRoomImageURLs: [URL]
    var roomOptionViewModels: [RoomOptionViewModel]
    var bathroomTypeNeverAvailable: BathroomType?
}


enum AccessibleRoomType: CaseIterable {
    case Double
    case Twin
}

enum BathroomType: CaseIterable {
    case LoweredBath
    case WetRoom
}

enum NewTwinRoomType: CaseIterable {
    case TrueTwin
    case PremierInnTwin
}

struct RoomOptionViewModel {
    var identifier: UUID

    var roomNumber: Int
    var numberOfAdults: Int
    var numberOfChildren: Int
    var numberOfInfants: Int
    var roomTypeName: String
    var roomPrice: String

    var bathroomSelectionRequired: Bool
    var twinRoomSelectionRequired: Bool

    var roomTypesCurrentlyAvailable: [AccessibleRoomType]
    var roomTypeCurrentlyUnavailable: AccessibleRoomType?
    var roomTypeToSelect: AccessibleRoomType?

    var bathroomTypesCurrentlyAvailable: [BathroomType]?
    var bathroomTypeCurrentlyUnavailable: BathroomType?
    var bathroomTypeToSelect: BathroomType?

    var twinRoomTypesCurrentlyAvailable: [(NewTwinRoomType, Cost)]?
    var twinRoomTypeCurrentlyUnavailable: NewTwinRoomType?
    var twinRoomTypeToSelect: NewTwinRoomType?

    var roomAndSelectionRowViewModel: RoomAndSelectionRowViewModel
}

struct RoomAndSelectionRowViewModel {
    var roomNumber: String
    var roomCriteria: String
    var otherRoomAvailabilityDescription: String?
    var currentRoomDescription: String
}

protocol BathroomSelectionViewProtocol: AnyObject {
    var customTrackingParameters: PIDictionary { get set }

    func update(withViewModel viewModel: BathroomSelectionViewModel)
    func enableContinueButton()
    func disableContinueButton()
}

protocol BathroomSelectionViewEventHandler {
    func viewIsReady()
    func viewIsAppearing()
    func continueButtonDidTap()
    func summaryButtonDidTap()

    func selected(bathroomOfType newBathroomType: BathroomType, forRoomID identifier: UUID)
    func selected(twinRoomOfType newTwinRoomType: NewTwinRoomType, forRoomID identifier: UUID)
    func tappedChange(withIndex index: Int)

    func userSelectedNewRoomType(_ roomType: AccessibleRoomType)
}

protocol BathroomSelectionInteractorProtocol {
    var viewModel: BathroomSelectionViewModel { get }
    var hasUpsells: Bool { get }
    var customTrackingDictionary: PIDictionary { get }

    func update(roomWithUniqueID identifier: UUID, toBathroomType bathroomType: BathroomType)
    func update(toRoomType accessibleRoomType: AccessibleRoomType)
    func update(roomWithUniqueID identifier: UUID, toTwinRoomType twinRoomType: NewTwinRoomType)
    func updateAvailability(completion: @escaping (Result<Bool>) -> Void)
    func holdBooking(completion: @escaping (Bool) -> Void)

    func roomTypeIsBeingChanged(atIndex index: Int)
    func availableRoomTypesForRoom(atIndex index: Int) -> [AccessibleRoomType]
    func preselectedRoomType(atIndex index: Int) -> AccessibleRoomType?
}

protocol BathroomSelectionRouterProtocol {
    func showHoldRateError()
    func moveToNextScreen(withUpsellsAvailable upsellsAvailable: Bool)
    func showAccessibleRoomTypeSelection(
        with roomTypes: [AccessibleRoomType],
        andPreselected preselected: AccessibleRoomType
    )
    func showSummary(with bookingDetails: BookingDetails)
}
