//
//  BathroomSelectionInteractor.swift
//  PremierInn
//
//
//  Created Nick Jones on 04/07/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import SimpleNetwork
import Foundation

struct RoomAndSelection: Hashable {
    var lettingType: String?
    var price: Cost?

    var isAccessibleRoom: Bool
    var isTwinRoom: Bool

    var roomType: AccessibleRoomType?

    var bathroomType: BathroomType?
    var twinType: NewTwinRoomType?
}

extension RoomAndSelection: Equatable {
    static func == (lhs: RoomAndSelection, rhs: RoomAndSelection) -> Bool {
        lhs.roomType == rhs.roomType && lhs.bathroomType == rhs.bathroomType && lhs.twinType == rhs.twinType
    }
}

struct RoomAndSelectionConfig {
    var roomAndSelection: RoomAndSelection?
    var originalRoom: Room

    var identifier: UUID
}

class BathroomSelectionInteractor {
    typealias Analytics = AnalyticsType & AnalyticsPromotionsTrackable

    // MARK: - Properties

    private var requestsManager: RequestsManager = RequestsManager()

    private let lock = NSLock()
    private var _currentRoomIDBeingChanged: UUID?
    private var currentRoomIDBeingChanged: UUID? {
        get {
            _currentRoomIDBeingChanged
        }
        set {
            lock.lock()
            _currentRoomIDBeingChanged = newValue
            lock.unlock()
        }
    }
    private var roomsToUse: [Room]

    // accessible rooms
    private var roomAndSelectionStore: [RoomAndSelection]
    private var currentRoomAndOptionConfiguration: [RoomAndSelectionConfig]
    private var accessibleRoomImages: [URL]
    private var roomAndOptionsCurrentlyUnused: [RoomAndSelection]

    // twin rooms
    private var twinRoomImages: [URL]

    private var productString: String = ""
    private var _viewModel: BathroomSelectionViewModel

    var presenter: BathroomSelectionPresenter?
    var analytics: Analytics = AnalyticsManager.shared

    // MARK: - Lifecycle

    init(with rooms: [Room], accessibleRoomImages: [URL], twinRoomImages: [URL], and productString: String = "") {
        self.accessibleRoomImages = accessibleRoomImages
        self.twinRoomImages = twinRoomImages
        self.roomsToUse = rooms

        roomAndSelectionStore = BathroomSelectionInteractor.buildRoomAndSelectionStore(from: self.roomsToUse)

        currentRoomAndOptionConfiguration = BathroomSelectionInteractor.buildCurrentRoomAndOptionConfiguration(
            withRooms: roomsToUse,
            from: roomAndSelectionStore
        )

        let currentlyInUseOptions = currentRoomAndOptionConfiguration.compactMap { $0.roomAndSelection }

        var remainingOptions = roomAndSelectionStore
        for option in currentlyInUseOptions {
            if let optionToRemoveIndex = remainingOptions.firstIndex(of: option) {
                if optionToRemoveIndex <= remainingOptions.count - 1 {
                    remainingOptions.remove(at: optionToRemoveIndex)
                }
            }
        }
        roomAndOptionsCurrentlyUnused = remainingOptions

        _viewModel = BathroomSelectionInteractor.buildViewModel(
            fromRoomAndSelectionConfiguration: currentRoomAndOptionConfiguration,
            rooms: self.roomsToUse,
            accessibleRoomImages: self.accessibleRoomImages,
            twinRoomImages: self.twinRoomImages,
            currentlyAvailableBathroomTypes: roomAndSelectionStore
        )

        self.productString = productString
    }

    // MARK: - Methods

    private static func parseRoomAndSelection(
        fromLettingType lettingType: String,
        specialRequests: [String]? = nil
    ) -> (room: AccessibleRoomType, bathroom: BathroomType)? {
        parseOperaRoomAndSelection(fromLettingType: lettingType, specialRequests: specialRequests)
    }

    private static func parseOperaRoomAndSelection(
        fromLettingType lettingType: String,
        specialRequests: [String]? = nil
    ) -> (room: AccessibleRoomType, bathroom: BathroomType)? {
        guard let specialRequest = specialRequests?
              .first(where: { bathroomSpecialRequests.contains(SpecialRequest(rawValue: $0) ?? .unknown) })
        else { return nil }
        guard let bathroomSpecialRequest = SpecialRequest(rawValue: specialRequest) else { return nil }

        var roomType: AccessibleRoomType
        var bathroomTypeToAdd: BathroomType

        // we need to check against the specialRequest here to make sure this room is intended for a bathroom use e.g. a LOWTWN (lowered bathroom twin can be re-purposed as both bathroom and twin room)
        switch bathroomSpecialRequest {
        case .wetRoom:
            bathroomTypeToAdd = .WetRoom
        case .loweredBath:
            bathroomTypeToAdd = .LoweredBath
        default:
            // if the special request is missing then don't treat it as bathroom selection
            return nil
        }

        // we should not be using opera room codes, but currently this is the only available solution
        let operaBathroom = OperaRoomTypeCode(rawValue: lettingType)

        switch operaBathroom {
        case .wetDouble, .loweredDouble:
            roomType = .Double
        case .wetTwin, .loweredTwin:
            roomType = .Twin
        default:
            // we treat unknown codes as double currently - if new codes get added at least the core logic will not break
            roomType = .Double
        }

        return (room: roomType, bathroom: bathroomTypeToAdd)
    }

    private static func buildRoomAndSelectionStore(from rooms: [Room]) -> [RoomAndSelection] {
        var roomAndSelectionOptions = [RoomAndSelection]()

        let accessibleRooms = rooms.filter { $0.isAccessibleRoom }

        for accessibleRoom in accessibleRooms {
            guard let roomOptions = accessibleRoom.options else {
                guard let lettingType = accessibleRoom.lettingType else { continue }
                let parsedRoomAndSelection = parseRoomAndSelection(fromLettingType: lettingType)

                roomAndSelectionOptions.append(RoomAndSelection(
                    lettingType: lettingType,
                    price: accessibleRoom.totalCost,
                    isAccessibleRoom: parsedRoomAndSelection?
                                                .room != nil && parsedRoomAndSelection?.bathroom != nil,
                    isTwinRoom: false,
                    roomType: parsedRoomAndSelection?.room,
                    bathroomType: parsedRoomAndSelection?.bathroom
                )
                )

                continue
            }

            for roomOption in roomOptions {
                /*
                 🦑 YARR CUSTOM LOGIC HERE 🦑
                 Here we're making large assumptions on the structure of what lettings types we're going to get back. The exhaustive list is:
                 AB, AB+C, ABS, ABS+, IB, IB+C, IBS, IBS+C, AW, AW+C, AWS, AWS+C, IW, IW+C, IWS, IWS+C

                 But switching and sorting through all of these is far too heavy we'll be switching on the first two characters which identify (So far as we've been told) the room type (I for twin, A for double) and the bathroom type (B for bath W for wet room). We aren't taking the S or the +C into account here as they denote whether the room is "As a single" and "With cot" respectively; both of which we don't need knowledge of here.
                */
                guard let lettingType = roomOption.lettingType else { continue }
                guard let parsedRoomAndSelection = parseRoomAndSelection(
                    fromLettingType: lettingType,
                    specialRequests: roomOption.specialRequests
                ) else { continue }

                let bathroom = RoomAndSelection(
                    lettingType: lettingType,
                    price: roomOption.totalCost,
                    isAccessibleRoom: true,
                    isTwinRoom: false,
                    roomType: parsedRoomAndSelection.room,
                    bathroomType: parsedRoomAndSelection.bathroom
                )

                // this doesn't exist in Opera
                if roomOption.alternativeLettingType != .accessible {
                    /*
                     🦑 YARR CUSTOM LOGIC HERE 🦑
                     Here we're adding the "original" letting type that is sent back from BART and adding it to the list of available room and bathroom options

                     We know which one it is because it is not marked with alternativeType, like the alternative options...
                    */

                    roomAndSelectionOptions.append(bathroom)
                } else {
                    // Once we have the room type we can check if we've already added, say, Wet rooms for a twin room
                    guard roomAndSelectionOptions
                          .contains(where: {
                        $0.roomType == parsedRoomAndSelection.room && $0.bathroomType == parsedRoomAndSelection.bathroom
                            }) ==
                          false else { continue }

                    // And if we haven't then we'll add enough bathroom and rooms to match
                    let bathrooms = [RoomAndSelection](repeating: bathroom, count: roomOption.numberAvailable ?? 0)

                    roomAndSelectionOptions.append(contentsOf: bathrooms)
                }
            }
        }

        // same process for twin rooms
        roomAndSelectionOptions.append(contentsOf: buildTwinRoomStore(from: rooms))

        return roomAndSelectionOptions
    }

    private static func buildCurrentRoomAndOptionConfiguration(
        withRooms rooms: [Room],
        from availableRoomsAndOptions: [RoomAndSelection]
    ) -> [RoomAndSelectionConfig] {
        var roomAndSelectionConfigurations = [RoomAndSelectionConfig]()

        // We want to always try and give our customers wet rooms where possible but failing that we'll offer them lowered baths
        // So we need to see how many wet rooms we have available. If there are wet rooms available in both double rooms and twin rooms we'll give them a double room with a wet room; but if there are any twin rooms with wet room we'll give them that.
        var accessibleRoomsSortedByPriority = availableRoomsAndOptions.filter({ $0.isAccessibleRoom == true })
            .sorted(by: { priorityWeighting(for: $0) > priorityWeighting(for: $1) })
        var twinRoomsSortedByPriority = availableRoomsAndOptions.filter({ $0.isTwinRoom == true })
            .sorted(by: { priorityWeighting(for: $0) > priorityWeighting(for: $1) })

        for room in rooms {
            guard room.type == .accessible || room.type == .twin else {
                roomAndSelectionConfigurations.append(RoomAndSelectionConfig(
                    roomAndSelection: nil,
                    originalRoom: room,
                    identifier: UUID()
                ))
                continue
            }

            // opera
            if let specialRequestString = room.options?.first?.specialRequests?
               .first(where: {
                (bathroomSpecialRequests + twinRoomSpecialRequests).contains(SpecialRequest(rawValue: $0) ?? .unknown) }),
               let specialRequest = SpecialRequest(rawValue: specialRequestString) {
                switch specialRequest {
                case .wetRoom, .loweredBath:
                    roomAndSelectionConfigurations.append(RoomAndSelectionConfig(
                        roomAndSelection: accessibleRoomsSortedByPriority.removeFirst(),
                        originalRoom: room,
                        identifier: UUID()
                    ))
                case .twinDoubleBedAndSofa, .twinTwoSingleBeds:
                    roomAndSelectionConfigurations.append(RoomAndSelectionConfig(
                        roomAndSelection: twinRoomsSortedByPriority.removeFirst(),
                        originalRoom: room,
                        identifier: UUID()
                    ))
                default:
                    roomAndSelectionConfigurations.append(RoomAndSelectionConfig(
                        roomAndSelection: nil,
                        originalRoom: room,
                        identifier: UUID()
                    ))
                }
            }
        }

        return roomAndSelectionConfigurations
    }

    // 🌍--“We are all flawed and creatures of our times. Is it fair to judge us by the unknown standards of the future?”--🌍
    // Pass in a RoomAndBathroom combination to get the priority of it in terms of when it should be selected "as default" for a customer, i.e. a Double Room with Wet Room is the most desirable where Twin with Lowered Bath is the least desireable 👑
    // swiftlint:disable:next cyclomatic_complexity
    static func priorityWeighting(for roomAndSelectionCombination: RoomAndSelection) -> Int {
        let totalNumberOfCombinations = (AccessibleRoomType.allCases.count + BathroomType.allCases.count) + 1

        if roomAndSelectionCombination.isAccessibleRoom {
            guard let roomType = roomAndSelectionCombination.roomType else { return 0 }
            guard let bathroomType = roomAndSelectionCombination.bathroomType else { return 0 }

            switch (roomType, bathroomType) {
            case (.Twin, .WetRoom):
                // Lowest priority room type combo 😅
                return totalNumberOfCombinations * 1
            case (.Twin, .LoweredBath):
                return totalNumberOfCombinations * 2
            case (.Double, .LoweredBath):
                // Best possible room type combo 💪
                return totalNumberOfCombinations * 4
            case (.Double, .WetRoom):
                return totalNumberOfCombinations * 3
            }
        } else if roomAndSelectionCombination.isTwinRoom {
            guard let twinRoomType = roomAndSelectionCombination.twinType else { return 0 }

            switch twinRoomType {
            case (.TrueTwin):
                return totalNumberOfCombinations * 2
            case (.PremierInnTwin):
                return totalNumberOfCombinations * 1
            }
        }

        return 0
    }

    // swiftlint:disable:next cyclomatic_complexity
    private func updateCurrentlySelectedRoom(toRoomType accessibleRoomType: AccessibleRoomType) {
        guard let currentRoomID = self.currentRoomIDBeingChanged else { return }
        guard let indexToUpdate: Int = self.currentRoomAndOptionConfiguration
              .firstIndex(where: { $0.identifier == currentRoomID }) else { return }
        guard indexToUpdate <= self.currentRoomAndOptionConfiguration.count else { return }
        guard let roomToUpdate = self.currentRoomAndOptionConfiguration[indexToUpdate].roomAndSelection else { return }

        var desiredRoomConfig = roomToUpdate
        desiredRoomConfig.roomType = accessibleRoomType

        let currentlyInUseOptions = currentRoomAndOptionConfiguration.compactMap { $0.roomAndSelection }

        var remainingOptions = roomAndSelectionStore

        for inUseBathroom in currentlyInUseOptions {
            guard let bathroomToRemove = remainingOptions
                  .firstIndex(where: { $0.bathroomType == inUseBathroom.bathroomType && $0.roomType == inUseBathroom.roomType
                }) else { continue }
            remainingOptions.remove(at: bathroomToRemove)
        }

        let roomAndSelectionCombinationAvailable: Bool = remainingOptions.contains(desiredRoomConfig)

        if roomAndSelectionCombinationAvailable == false {
            desiredRoomConfig.bathroomType = desiredRoomConfig.bathroomType == .WetRoom ? .LoweredBath : .WetRoom
            let alternativeRoomAndSelectionCombinationAvailable = remainingOptions.contains(desiredRoomConfig)

            guard alternativeRoomAndSelectionCombinationAvailable else { return }
        }

        self.currentRoomAndOptionConfiguration[indexToUpdate].roomAndSelection = desiredRoomConfig

        for roomAndSelection in currentlyInUseOptions {
            var indexOfBathroomToRemove: Int?

            for (index, bathroom) in remainingOptions.enumerated() where roomAndSelection == bathroom {
                indexOfBathroomToRemove = index
            }

            guard let index = indexOfBathroomToRemove else { continue }
            remainingOptions.remove(at: index)
        }

        roomAndOptionsCurrentlyUnused = remainingOptions

        _viewModel = BathroomSelectionInteractor.buildViewModel(
            fromRoomAndSelectionConfiguration: self.currentRoomAndOptionConfiguration,
            rooms: self.roomsToUse,
            accessibleRoomImages: self.accessibleRoomImages,
            twinRoomImages: self.twinRoomImages,
            currentlyAvailableBathroomTypes: self.roomAndSelectionStore
        )

        self.currentRoomIDBeingChanged = nil
    }

    private func updateRoom(withIdentifier identifier: UUID, withBathroomType bathroomType: BathroomType) {
        guard let indexToUpdate: Int = self.currentRoomAndOptionConfiguration
              .firstIndex(where: { $0.identifier == identifier }) else { return }

        let currentlyInUseOptions = currentRoomAndOptionConfiguration.compactMap { $0.roomAndSelection }

        var remainingOptions = roomAndSelectionStore
        for inUseBathroom in currentlyInUseOptions {
            guard let bathroomToRemove = remainingOptions
                  .firstIndex(where: { $0.bathroomType == inUseBathroom.bathroomType && $0.roomType == inUseBathroom.roomType
                }) else { continue }
            remainingOptions.remove(at: bathroomToRemove)
        }

        // get the combination that we want to select
        let roomAndSelectionCombinationAvailable: RoomAndSelection? = remainingOptions
            .first(where: { $0.bathroomType == bathroomType })
        guard roomAndSelectionCombinationAvailable != nil else { return }

        // find the room and selection that we want to replace
        guard let indexToReplace: Int = remainingOptions.firstIndex(where: { $0.bathroomType == bathroomType })
            else { return }
        guard let roomAndSelectionToReplace = self.currentRoomAndOptionConfiguration[indexToUpdate].roomAndSelection
            else { return }
        remainingOptions[indexToReplace] = roomAndSelectionToReplace
        roomAndOptionsCurrentlyUnused = remainingOptions

        // change the selection
        self.currentRoomAndOptionConfiguration[indexToUpdate].roomAndSelection = roomAndSelectionCombinationAvailable

        _viewModel = BathroomSelectionInteractor.buildViewModel(
            fromRoomAndSelectionConfiguration: self.currentRoomAndOptionConfiguration,
            rooms: self.roomsToUse,
            accessibleRoomImages: self.accessibleRoomImages,
            twinRoomImages: self.twinRoomImages,
            currentlyAvailableBathroomTypes: self.roomAndSelectionStore
        )

        lockInNewRoomAndSelectionConfigurations()
    }

    private func updateRoom(withIdentifier identifier: UUID, withTwinRoomType twinRoomType: NewTwinRoomType) {
        guard let indexToUpdate: Int = self.currentRoomAndOptionConfiguration
              .firstIndex(where: { $0.identifier == identifier }) else { return }

        // setup the remaining available options
        let currentlyInUseOptions = currentRoomAndOptionConfiguration.compactMap { $0.roomAndSelection }

        var remainingOptions = roomAndSelectionStore
        for inUseTwinRoom in currentlyInUseOptions {
            guard let twinRoomToRemove = remainingOptions.firstIndex(where: { $0.twinType == inUseTwinRoom.twinType })
                else { continue }
            remainingOptions.remove(at: twinRoomToRemove)
        }

        // get the combination that we want to select
        let roomAndSelectionCombinationAvailable: RoomAndSelection? = remainingOptions
            .first(where: { $0.twinType == twinRoomType })
        guard roomAndSelectionCombinationAvailable != nil else { return }

        // find the room and selection that we want to replace
        guard let indexToReplace: Int = remainingOptions.firstIndex(where: { $0.twinType == twinRoomType }) else { return }
        guard let roomAndSelectionToReplace = self.currentRoomAndOptionConfiguration[indexToUpdate].roomAndSelection
            else { return }
        remainingOptions[indexToReplace] = roomAndSelectionToReplace
        roomAndOptionsCurrentlyUnused = remainingOptions

        // change the selection
        self.currentRoomAndOptionConfiguration[indexToUpdate].roomAndSelection = roomAndSelectionCombinationAvailable

        _viewModel = BathroomSelectionInteractor.buildViewModel(
            fromRoomAndSelectionConfiguration: self.currentRoomAndOptionConfiguration,
            rooms: self.roomsToUse,
            accessibleRoomImages: self.accessibleRoomImages,
            twinRoomImages: self.twinRoomImages,
            currentlyAvailableBathroomTypes: self.roomAndSelectionStore
        )

        lockInNewRoomAndSelectionConfigurations()
    }

    // We need an update current room and bathroom configuration function

    private static func buildViewModel(
        fromRoomAndSelectionConfiguration roomAndSelectionConfiguration: [RoomAndSelectionConfig],
        rooms: [Room],
        accessibleRoomImages: [URL],
        twinRoomImages: [URL],
        currentlyAvailableBathroomTypes: [RoomAndSelection]
    ) -> BathroomSelectionViewModel {
        // First we start by getting all of the current bathroom types
        var totalAvailableRoomsAndOptions = currentlyAvailableBathroomTypes.compactMap({ $0 })
        // Next we get all of the currently in use bathroom types
        let currentlyInUseRoomAndSelectionTypes = roomAndSelectionConfiguration.compactMap({ $0.roomAndSelection })

        // We then iterator over these in use bathroom types and remove all of them from the total list of types
        for inUseRoom in currentlyInUseRoomAndSelectionTypes {
            if let roomToRemoveIndex = totalAvailableRoomsAndOptions.firstIndex(of: inUseRoom) {
                if roomToRemoveIndex <= totalAvailableRoomsAndOptions.count - 1 {
                    totalAvailableRoomsAndOptions.remove(at: roomToRemoveIndex)
                }
            }
        }

        let uniqueListOfOptionsAvailable = Array(Set(totalAvailableRoomsAndOptions))

        let roomOptionViewModels: [RoomOptionViewModel] = BathroomSelectionInteractor.roomOptionViewModels(
            for: roomAndSelectionConfiguration,
            and: uniqueListOfOptionsAvailable
        )

        // Here we'll check to find our never available room type. We should never end up with more than one unavailable type as based on that logic we don't have any bathrooms available; and if we end up with 0 then that's fine as all room types are available
        let totalPossibleCombinations: [BathroomType] = [.LoweredBath, .WetRoom]
        var availableTypes = [BathroomType]()

        for room in currentlyAvailableBathroomTypes {
            guard let bathroomTypeFound = room.bathroomType else { continue }

            if totalPossibleCombinations.contains(bathroomTypeFound) {
                availableTypes.append(bathroomTypeFound)
            }
        }

        let unavailableTypes = totalPossibleCombinations.difference(from: availableTypes)

        let bathroomTypeNeverAvailable = unavailableTypes.count > 1 ? nil : unavailableTypes.first

        return BathroomSelectionViewModel(
            accessibleRoomImageURLs: accessibleRoomImages,
            twinRoomImageURLs: twinRoomImages,
            roomOptionViewModels: roomOptionViewModels,
            bathroomTypeNeverAvailable: bathroomTypeNeverAvailable
        )
    }

    // swiftlint:disable:next cyclomatic_complexity function_body_length
    private static func roomOptionViewModels(
        for roomAndSelectionConfiguration: [RoomAndSelectionConfig],
        and uniqueListOfOptionsAvailable: [RoomAndSelection]
    ) -> [RoomOptionViewModel] {
        var roomOptionViewModels = [RoomOptionViewModel]()

        for (index, room) in roomAndSelectionConfiguration.enumerated() {
            var bathroomOptionsAvailable = [BathroomType]()
            var twinRoomOptionsAndPricesAvailable = [(NewTwinRoomType, Cost)]()
            var currentlyUnavailableType: BathroomType?
            var currentlyUnavailableTwinType: NewTwinRoomType?

            if let bathroomType = room.roomAndSelection?.bathroomType {
                bathroomOptionsAvailable.append(bathroomType)
            }

            if let twinType = room.roomAndSelection?.twinType {
                guard let price = room.roomAndSelection?.price else { continue }

                twinRoomOptionsAndPricesAvailable.append((twinType, price))
            }

            if room.roomAndSelection?.isAccessibleRoom == true {
                guard let currentRoomType = room.roomAndSelection?.roomType else {
                    let optionViewModelParams = OptionViewModelParams(
                        room: room,
                        index: index,
                        bathroomOptionsAvailable: bathroomOptionsAvailable,
                        currentlyUnavailableType: currentlyUnavailableType,
                        twinRoomOptionsAndPricesAvailable: nil,
                        currentlyUnavailableTwinType: currentlyUnavailableTwinType
                    )
                    roomOptionViewModels
                        .append(BathroomSelectionInteractor.alternativeTypeRoomOptionViewModel(for: optionViewModelParams))
                    continue
                }

                var roomTypesCurrentlyAvailable: [AccessibleRoomType] = [currentRoomType]

                for roomAndSelection in uniqueListOfOptionsAvailable {
                    guard roomAndSelection.bathroomType != nil else { continue }

                    if roomAndSelection.roomType == room.roomAndSelection?.roomType {
                        guard let bathroom = roomAndSelection.bathroomType else { continue }

                        if bathroomOptionsAvailable.contains(bathroom) == false {
                            bathroomOptionsAvailable.append(bathroom)
                        }
                    } else {
                        guard let roomType = roomAndSelection.roomType else { continue }

                        if roomTypesCurrentlyAvailable.contains(roomType) == false {
                            roomTypesCurrentlyAvailable.append(roomType)
                        }
                    }
                }

                bathroomOptionsAvailable.sort(by: { $0 == BathroomType.LoweredBath && $1 != BathroomType.LoweredBath })

                if currentlyUnavailableType == nil && bathroomOptionsAvailable.count < 2 {
                    if let firstAvailableType = bathroomOptionsAvailable.first {
                        switch firstAvailableType {
                        case .WetRoom:
                            currentlyUnavailableType = .LoweredBath
                        case .LoweredBath:
                            currentlyUnavailableType = .WetRoom
                        }
                    }
                }

                let viewModel = BathroomSelectionInteractor.availableRoomOptionViewModel(
                    for: room,
                    and: index,
                    currentRoomType: currentRoomType,
                    roomTypesCurrentlyAvailable: roomTypesCurrentlyAvailable,
                    bathroomOptionsAvailable: bathroomOptionsAvailable,
                    currentlyUnavailableType: currentlyUnavailableType,
                    twinRoomOptionsAndPricesAvailable: [],
                    currentlyUnavailableTwinType: nil,
                    priceBathroom: uniqueListOfOptionsAvailable.first?.price ?? room.roomAndSelection?.price
                )

                roomOptionViewModels.append(viewModel)
            } else if room.roomAndSelection?.isTwinRoom == true {
                guard room.roomAndSelection?.twinType != nil else {
                    let optionViewModelParams = OptionViewModelParams(
                        room: room,
                        index: index,
                        bathroomOptionsAvailable: bathroomOptionsAvailable,
                        currentlyUnavailableType: currentlyUnavailableType,
                        twinRoomOptionsAndPricesAvailable: nil,
                        currentlyUnavailableTwinType: currentlyUnavailableTwinType
                    )
                    roomOptionViewModels
                        .append(BathroomSelectionInteractor.alternativeTypeRoomOptionViewModel(for: optionViewModelParams))
                    continue
                }

                for roomAndSelection in uniqueListOfOptionsAvailable {
                    guard let twinType = roomAndSelection.twinType else { continue }

                    if twinRoomOptionsAndPricesAvailable.map({ $0.0 }).contains(twinType) == false {
                        guard let price = roomAndSelection.price else { continue }

                        twinRoomOptionsAndPricesAvailable.append((twinType, price))
                    }
                }

                twinRoomOptionsAndPricesAvailable
                    .sort(by: { $0.0 == NewTwinRoomType.TrueTwin && $1.0 != NewTwinRoomType.TrueTwin })

                if currentlyUnavailableTwinType == nil && twinRoomOptionsAndPricesAvailable.count < 2 {
                    if let firstAvailableType = twinRoomOptionsAndPricesAvailable.first?.0 {
                        switch firstAvailableType {
                        case .TrueTwin:
                            currentlyUnavailableTwinType = .PremierInnTwin
                        case .PremierInnTwin:
                            currentlyUnavailableTwinType = .TrueTwin
                        }
                    }
                }

                let viewModel = BathroomSelectionInteractor.availableRoomOptionViewModel(
                    for: room,
                    and: index,
                    currentRoomType: .Twin,
                    roomTypesCurrentlyAvailable: [],
                    bathroomOptionsAvailable: [],
                    currentlyUnavailableType: currentlyUnavailableType,
                    twinRoomOptionsAndPricesAvailable: twinRoomOptionsAndPricesAvailable,
                    currentlyUnavailableTwinType: currentlyUnavailableTwinType,
                    priceBathroom: uniqueListOfOptionsAvailable.first?.price
                )

                roomOptionViewModels.append(viewModel)
            } else {
                let optionViewModelParams = OptionViewModelParams(
                    room: room,
                    index: index,
                    bathroomOptionsAvailable: bathroomOptionsAvailable,
                    currentlyUnavailableType: currentlyUnavailableType,
                    twinRoomOptionsAndPricesAvailable: nil,
                    currentlyUnavailableTwinType: currentlyUnavailableTwinType
                )
                roomOptionViewModels
                    .append(BathroomSelectionInteractor.alternativeTypeRoomOptionViewModel(for: optionViewModelParams))
            }
        }

        return roomOptionViewModels
    }

    typealias OptionViewModelParams = (
        room: RoomAndSelectionConfig,
        index: Int,
        bathroomOptionsAvailable: [BathroomType],
        currentlyUnavailableType: BathroomType?,
        twinRoomOptionsAndPricesAvailable: [(NewTwinRoomType, Cost)]?,
        currentlyUnavailableTwinType: NewTwinRoomType?
    )

    private static func alternativeTypeRoomOptionViewModel(for optionViewModelParams: OptionViewModelParams)
        -> RoomOptionViewModel {
        let room = optionViewModelParams.room
        let bathroomOptionsAvailable = optionViewModelParams.bathroomOptionsAvailable
        let currentlyUnavailableType = optionViewModelParams.currentlyUnavailableType
        let twinRoomOptionsAndPricesAvailable = optionViewModelParams.twinRoomOptionsAndPricesAvailable
        let currentlyUnavailableTwinType = optionViewModelParams.currentlyUnavailableTwinType
        let index = optionViewModelParams.index

        return RoomOptionViewModel(
            identifier: room.identifier,
            roomNumber: index + 1,
            numberOfAdults: room.originalRoom.adults,
            numberOfChildren: room.originalRoom.children,
            numberOfInfants: room.originalRoom.infants,
            roomTypeName: room.originalRoom.type.name,
            roomPrice: room.roomAndSelection?.price?.amount.stringValue ?? "0",
            bathroomSelectionRequired: room.roomAndSelection?.isAccessibleRoom ?? false,
            twinRoomSelectionRequired: room.roomAndSelection?.isTwinRoom ?? false,
            roomTypesCurrentlyAvailable: [],
            roomTypeCurrentlyUnavailable: nil,
            roomTypeToSelect: room.roomAndSelection?.roomType,
            bathroomTypesCurrentlyAvailable: bathroomOptionsAvailable,
            bathroomTypeCurrentlyUnavailable: currentlyUnavailableType,
            bathroomTypeToSelect: room.roomAndSelection?.bathroomType,
            twinRoomTypesCurrentlyAvailable: twinRoomOptionsAndPricesAvailable,
            twinRoomTypeCurrentlyUnavailable: currentlyUnavailableTwinType,
            twinRoomTypeToSelect: room.roomAndSelection?.twinType,
            roomAndSelectionRowViewModel: BathroomSelectionInteractor.buildRoomRowViewModel(
                withRoomIndex: index,
                currentRoomType: .Double,
                roomAndSelectionConfig: room,
                andListOfCurrentlyAvailableRoomTypes: [],
                roomDescription: room.originalRoom.type.localizedName.capitalized
            )
        )
    }

    // swiftlint:disable:next function_parameter_count
    private static func availableRoomOptionViewModel(
        for room: RoomAndSelectionConfig,
        and index: Int,
        currentRoomType: AccessibleRoomType,
        roomTypesCurrentlyAvailable: [AccessibleRoomType],
        bathroomOptionsAvailable: [BathroomType],
        currentlyUnavailableType: BathroomType?,
        twinRoomOptionsAndPricesAvailable: [(NewTwinRoomType, Cost)]?,
        currentlyUnavailableTwinType: NewTwinRoomType?,
        priceBathroom: Cost?
    ) -> RoomOptionViewModel {
        let roomAndSelectionRowViewModel: RoomAndSelectionRowViewModel = buildRoomRowViewModel(
            withRoomIndex: index,
            currentRoomType: currentRoomType,
            roomAndSelectionConfig: room,
            // the below is only for accessible double vs accessible twin
            andListOfCurrentlyAvailableRoomTypes: roomTypesCurrentlyAvailable
        )

        return RoomOptionViewModel(
            identifier: room.identifier,
            roomNumber: index + 1,
            numberOfAdults: room.originalRoom.adults,
            numberOfChildren: room.originalRoom.children,
            numberOfInfants: room.originalRoom.infants,
            roomTypeName: room.originalRoom.type.name,
            roomPrice: priceBathroom?.localizedValue ?? "0",
            bathroomSelectionRequired: room.roomAndSelection?.isAccessibleRoom ?? false,
            twinRoomSelectionRequired: room.roomAndSelection?.isTwinRoom ?? false,
            roomTypesCurrentlyAvailable: roomTypesCurrentlyAvailable,
            roomTypeCurrentlyUnavailable: nil,
            roomTypeToSelect: room.roomAndSelection?.roomType,
            bathroomTypesCurrentlyAvailable: bathroomOptionsAvailable,
            bathroomTypeCurrentlyUnavailable: currentlyUnavailableType,
            bathroomTypeToSelect: room.roomAndSelection?.bathroomType,
            twinRoomTypesCurrentlyAvailable: twinRoomOptionsAndPricesAvailable,
            twinRoomTypeCurrentlyUnavailable: currentlyUnavailableTwinType,
            twinRoomTypeToSelect: room.roomAndSelection?.twinType,
            roomAndSelectionRowViewModel: roomAndSelectionRowViewModel
        )
    }

    private static func buildRoomRowViewModel(
        withRoomIndex index: Int,
        currentRoomType: AccessibleRoomType,
        roomAndSelectionConfig: RoomAndSelectionConfig,
        andListOfCurrentlyAvailableRoomTypes currentlyAvailableRoomTypes: [AccessibleRoomType],
        roomDescription: String? = nil
    ) -> RoomAndSelectionRowViewModel {
        let roomNumber = "\(PILocalizedString("Room", comment: "")) \(index + 1)"

        var roomCriteria = String.localizedStringWithFormat(
            PILocalizedString("%d adult(s)", comment: "Message shown for number of adults"),
            roomAndSelectionConfig.originalRoom.adults
        )

        let numberOfInfantsDescription = roomAndSelectionConfig.originalRoom
            .infants > 0 ?
            ", \(String.localizedStringWithFormat(PILocalizedString("%d Infant(Infants)", comment: "Message shown for number of infants"), roomAndSelectionConfig.originalRoom.infants))" :
            ""
        roomCriteria.append(numberOfInfantsDescription)

        let numberOfChildrenDescription = roomAndSelectionConfig.originalRoom
            .children > 0 ?
            ", \(String.localizedStringWithFormat(PILocalizedString("%d child(children)", comment: "Message shown for number of children"), roomAndSelectionConfig.originalRoom.children))" :
            ""
        roomCriteria.append(numberOfChildrenDescription)

        var otherRoomTypeDescription: String?
        if currentlyAvailableRoomTypes.count > 1 {
            for roomType in currentlyAvailableRoomTypes where roomType != currentRoomType {
                switch roomType {
                case .Double:
                    otherRoomTypeDescription = "\(PILocalizedString("accessibleDoubleTitle")) available"
                case .Twin:
                    otherRoomTypeDescription = "\(PILocalizedString("accessibleTwinTitle")) available"
                }
            }
        }

        let currentRoomDescription: String = roomDescription ??
            (roomAndSelectionConfig.roomAndSelection?
            .isTwinRoom == true ? PILocalizedString("TWIN") :
            ((roomAndSelectionConfig.roomAndSelection?
            .roomType == .Double ? PILocalizedString("accessibleDoubleTitle") : PILocalizedString("accessibleTwinTitle"))))

        return RoomAndSelectionRowViewModel(
            roomNumber: roomNumber,
            roomCriteria: roomCriteria,
            otherRoomAvailabilityDescription: otherRoomTypeDescription,
            currentRoomDescription: currentRoomDescription
        )
    }

    private func realWorldLettingType(from roomAndSelection: RoomAndSelectionConfig?) -> String? {
        roomAndSelection?.roomAndSelection?.lettingType
    }

    private func lockInNewRoomAndSelectionConfigurations() {
        for realRoom in self.roomsToUse {
            for roomInStore in currentRoomAndOptionConfiguration
                where (roomInStore.originalRoom.uniqueID == realRoom.uniqueID) {
                if roomInStore.roomAndSelection?.isAccessibleRoom == true || roomInStore.roomAndSelection?
                   .isTwinRoom == true {
                    guard let newLettingType = realWorldLettingType(from: roomInStore) else { continue }
                    realRoom.lettingType = newLettingType
                }
            }
        }

        BookingDetails.sharedInstance.rate?.rooms = roomsToUse
        BookingDetails.sharedInstance.roomLettings = roomsToUse
    }
}

extension BathroomSelectionInteractor: BathroomSelectionInteractorProtocol {
    var hasUpsells: Bool {
        let isUltimateWifiIncluded = BookingDetails.sharedInstance.isUltimateWifiIncluded

        let mealsCount = BookingDetails.sharedInstance.rate?.foodUpsells?.count ?? 0
        var extrasCount = BookingDetails.sharedInstance.rate?.extraUpsells?.count ?? 0
        let wifiCount = isUltimateWifiIncluded ? (BookingDetails.sharedInstance.rate?.wifiUpsells?.count ?? 0) : 0

        if !SettingsManager.sharedInstance.featureAllowEciLco {
            extrasCount = BookingDetails.sharedInstance.rate?.extraUpsellsExcludingECiLco?.count ?? 0
        }

        return (mealsCount + extrasCount + wifiCount) > 0
    }

    var viewModel: BathroomSelectionViewModel {
        _viewModel
    }

    var customTrackingDictionary: PIDictionary {
        var data: PIDictionary = analytics.analyticsProperties(stateType: PIAnalytics.StateTypes.bookingFlow)

        // this doesn't say much as it is sending what's preselected when the screen loads
//        let lettingTypesString: String = currentRoomAndOptionConfiguration.compactMap { realWorldLettingType(from: $0) ?? $0.originalRoom.lettingType ?? "Unknown" }.joined(separator: "_")

        data = data.merging(
            BookingDetails.sharedInstance.criteria.analyticsDictionary,
            uniquingKeysWith: { (_, last) in last }
        )

        let rateCode = BookingDetails.sharedInstance.rate?.rateCode()

        data[PIAnalytics.Keys.productString] = productString
        data[PIAnalytics.Keys.bfRateCode] = rateCode
//        data[PIAnalytics.Keys.bfLettingType] = lettingTypesString
        data[PIAnalytics.Keys.bfRateDescription] = BookingDetails.sharedInstance.rate?.name ?? ""

        if let promotionsAnalyticsData = analytics.getPromotionsAnalyticsDict(with: .sharedInstance) {
            data.mergePreferNew(promotionsAnalyticsData)
        }

        return data
    }

    func update(roomWithUniqueID identifier: UUID, toBathroomType bathroomType: BathroomType) {
        updateRoom(withIdentifier: identifier, withBathroomType: bathroomType)
    }

    func update(toRoomType accessibleRoomType: AccessibleRoomType) {
        self.updateCurrentlySelectedRoom(toRoomType: accessibleRoomType)
    }

    func update(roomWithUniqueID identifier: UUID, toTwinRoomType twinRoomType: NewTwinRoomType) {
        updateRoom(withIdentifier: identifier, withTwinRoomType: twinRoomType)
    }

    func updateAvailability(completion: @escaping (Result<Bool>) -> Void) {
        guard let hotel = BookingDetails.sharedInstance.hotel else {
            completion(.failure(error: UpdateAvailabilityError.missingHotel))
            return
        }

        requestsManager.hotelAvailability(
            hotelCode: hotel.code,
            hotelBrand: hotel.brand,
            bookingDetails: BookingDetails.sharedInstance
        ) { response, error in
            if let error = error {
                AnalyticsManager.shared.track(error: error, name: PIAnalytics.Error.remoteAvailabilityLoadError)

                return completion(.failure(error: error.serverErrorForUpdateAvailability))
            }

            guard response?.available == true, let bookingRate = BookingDetails.sharedInstance.rate,
                  let newRate = (response?.rates.first { $0.rateCode() == bookingRate.rateCode() }) else {
                AnalyticsManager.shared.track(errorName: PIAnalytics.Error.timeoutNoAvailError)

                return completion(.failure(error: UpdateAvailabilityError.noMoreAvailability))
            }
            guard bookingRate.totalCost.amount == newRate.totalCost.amount else {
                AnalyticsManager.shared.track(errorName: PIAnalytics.Error.rateChangedError)

                return completion(.failure(error: UpdateAvailabilityError.offerNewRate(newRate)))
            }

            BookingDetails.sharedInstance.rate = newRate
        }
    }

    func holdBooking(completion: @escaping (Bool) -> Void) {
        lockInNewRoomAndSelectionConfigurations()

        requestsManager.performHoldBooking(bookingDetails: BookingDetails.sharedInstance) { basketReference, _ in
            guard let basketReference = basketReference else {
                return completion(false)
            }

            self.requestsManager.bookingInformation(
                with: basketReference,
                isBusiness: BookingDetails.sharedInstance.bookingMode == .business,
                completion: { basketInfo, _ in
                guard let bookingFlowId = basketInfo?.bookingFlowId,
                      let hotelCode = BookingDetails.sharedInstance.hotel?.code else {
                    AnalyticsManager.shared.log(
                        event: FirebaseAnalytics.Event.failedToGetBookingFlowId,
                        parameters: AnalyticsManager.getPackagesErrorParams(bookingDetails: BookingDetails.sharedInstance)
                    )
                    return completion(true)
                }

                self.requestsManager.getPackages(
                    reservationId: basketReference,
                    bookingDetails: BookingDetails.sharedInstance,
                    hotelCode: hotelCode,
                    bookingFlowId: bookingFlowId
                ) { response, _ in
                    guard let upsells = response?.0 else {
                        AnalyticsManager.shared.log(
                            event: FirebaseAnalytics.Event.failedToGetPackages,
                            parameters: AnalyticsManager.getPackagesErrorParams(
                                bookingDetails: BookingDetails.sharedInstance,
                                bookingFlow: bookingFlowId
                            )
                        )
                        return completion(true)
                    }

                    if let addedUpsells = response?.1 {
                        BookingDetails.sharedInstance.loadPreselectedRateUpsells(upsells: addedUpsells)
                    }

                    BookingDetails.sharedInstance.rate?.upsellItems = upsells
                    BookingDetails.sharedInstance.hotel?.cityTaxForLeisure = response?.2.cityTaxForLeisure
                    BookingDetails.sharedInstance.hotel?.cityTaxForBusiness = response?.2.cityTaxForBusiness
                    BookingDetails.sharedInstance.goshOptions = response?.3

                    return completion(true)
                }
            }
            )
        }
    }

    func roomTypeIsBeingChanged(atIndex index: Int) {
        guard index < currentRoomAndOptionConfiguration.endIndex else { return }

        currentRoomIDBeingChanged = currentRoomAndOptionConfiguration[index].identifier
    }

    func preselectedRoomType(atIndex index: Int) -> AccessibleRoomType? {
        guard index < viewModel.roomOptionViewModels.endIndex else { return nil }

        return viewModel.roomOptionViewModels[index].roomTypeToSelect
    }

    func availableRoomTypesForRoom(atIndex index: Int) -> [AccessibleRoomType] {
        guard index < viewModel.roomOptionViewModels.endIndex else { return [] }

        return viewModel.roomOptionViewModels[index].roomTypesCurrentlyAvailable
    }
}
