//
//  BathroomSelectionPresenter.swift
//  PremierInn
//
//
//  Created Nick Jones on 04/07/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import Foundation
import SimpleNetwork

class BathroomSelectionPresenter: BathroomSelectionViewEventHandler {
    weak var view: BathroomSelectionViewProtocol?

    var interactor: BathroomSelectionInteractorProtocol
    var router: BathroomSelectionRouterProtocol?

    init(with interactor: BathroomSelectionInteractorProtocol) {
        self.interactor = interactor
    }

    func viewIsReady() {
        view?.update(withViewModel: interactor.viewModel)
    }

    func viewIsAppearing() {
        interactor.updateAvailability { _ in
        }
    }

    func continueButtonDidTap() {
        view?.disableContinueButton()
        DispatchGroupManager.sharedInstance.availabilityDispatchGroup.notify(queue: .main) {
            self.interactor.holdBooking { [weak self] (result) in
                DispatchQueue.main.async {
                    self?.view?.enableContinueButton()
                }
                if result == false {
                    self?.showHoldBookingError()
                } else {
                    self?.router?.moveToNextScreen(withUpsellsAvailable: self?.interactor.hasUpsells == true)
                }
            }
        }
    }

    func summaryButtonDidTap() {
        router?.showSummary(with: BookingDetails.sharedInstance)
    }

    func selected(bathroomOfType newBathroomType: BathroomType, forRoomID identifier: UUID) {
        interactor.update(roomWithUniqueID: identifier, toBathroomType: newBathroomType)

        view?.update(withViewModel: interactor.viewModel)
    }

    func selected(twinRoomOfType newTwinRoomType: NewTwinRoomType, forRoomID identifier: UUID) {
        interactor.update(roomWithUniqueID: identifier, toTwinRoomType: newTwinRoomType)

        view?.update(withViewModel: interactor.viewModel)
    }

    func showHoldBookingError() {
        DispatchQueue.main.async {
            self.router?.showHoldRateError()
        }
    }

    func tappedChange(withIndex index: Int) {
        interactor.roomTypeIsBeingChanged(atIndex: index)

        let availableRoomTypes = interactor.availableRoomTypesForRoom(atIndex: index)
        guard let preselectedRoomType = interactor.preselectedRoomType(atIndex: index) else { return }

        router?.showAccessibleRoomTypeSelection(with: availableRoomTypes, andPreselected: preselectedRoomType)
    }

    func userSelectedNewRoomType(_ roomType: AccessibleRoomType) {
        interactor.update(toRoomType: roomType)

        view?.update(withViewModel: interactor.viewModel)
    }
}
