// Auto-generated from Opera package codes data
// Each entry contains the full metadata needed to build the PUT payload

export interface PackageCodeConfig {
  code: string;
  description: string;
  shortDescription?: string;
  group: boolean;
  forecastGroup?: string;
  postingRhythm?: string;
  priceCalculationRule?: string;
  addToRate: boolean;
  printSeparateLine: boolean;
  sellSeparate: boolean;
  postNextDay: boolean;
  forecastNextDay: boolean;
  webBookable: boolean;
  catering: boolean;
  inventoryItems: Array<{ articleNumber: string; description: string; quantity: number; itemId: number }>;
  calculatedPrice: number;
}

export const PACKAGE_CODES: PackageCodeConfig[] = [
  {
    code: 'BFADBF',
    description: 'Premier Inn Breakfast Food VEN',
    group: false,
    forecastGroup: 'BKF',
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: true,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 11.99,
  },
  {
    code: 'BFADCT',
    description: 'Continental Breakfast Food',
    group: false,
    forecastGroup: 'BKF',
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: true,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 9.99,
  },
  {
    code: 'BFCHDF',
    description: 'Free Childrens Breakfast',
    group: false,
    forecastGroup: 'BKF',
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: true,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'BFCHDP',
    description: 'Chargeable Childrens Breakfast Food',
    group: false,
    forecastGroup: 'BKF',
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: true,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 4,
  },
  {
    code: 'OBFADS',
    description: 'Shareholder Adults Breakfast',
    group: false,
    forecastGroup: 'BKF',
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: true,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'OBFCOM',
    description: 'Complimentary Breakfast',
    group: false,
    forecastGroup: 'BKF',
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: true,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'OBFGRF',
    description: 'Group Breakfast Food',
    group: false,
    forecastGroup: 'BKF',
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerAdult',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: true,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'ZMIGBF',
    description: 'Group Breakfast Food (9.50)',
    group: false,
    forecastGroup: 'BKF',
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerAdult',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: true,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'OBG24S',
    description: 'Group Breakfast Food Spring 24',
    group: false,
    forecastGroup: 'BKF',
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerAdult',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: true,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'BFGROL',
    description: 'Breakfast Roll Bundle',
    shortDescription: 'Breakfast Roll Bundle',
    group: false,
    forecastGroup: 'BKF',
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: true,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'BFGCON',
    description: 'Continental Bundle',
    shortDescription: 'Continental Bundle',
    group: false,
    forecastGroup: 'BKF',
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: true,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'OBFBRK',
    description: 'Premier Inn Breakfast Food',
    group: false,
    forecastGroup: 'BKF',
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerAdult',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: true,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'BFGLGH',
    description: 'Lighter Bundle',
    shortDescription: 'Lighter Bundle',
    group: false,
    forecastGroup: 'BKF',
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: true,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'DBCHDF',
    description: "Free Children's Dinner",
    group: false,
    forecastGroup: 'DIN',
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: true,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'FHSCOU2',
    description: 'Free Late Check Out',
    group: false,
    postingRhythm: 'LastNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [{ articleNumber: 'LCO2', description: 'Late Check Out 2pm', quantity: 1, itemId: 71627 }],
    calculatedPrice: 0,
  },
  {
    code: 'CARPRK',
    description: 'Car Parking',
    group: false,
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'FlatRate',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 7,
  },
  {
    code: 'FI24HR',
    description: 'Ultimate Wi-Fi - 24 hours',
    group: false,
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 5,
  },
  {
    code: 'FIFR24',
    description: 'Free Ultimate Wi-Fi - 24 hours',
    group: false,
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'HSATWN',
    description: 'Twin Fee',
    group: false,
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'FlatRate',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 5,
  },
  {
    code: 'HSCKIN',
    description: 'Early Check In',
    shortDescription: 'Early Check In',
    group: false,
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'FlatRate',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: true,
    catering: false,
    inventoryItems: [{ articleNumber: 'ECI', description: 'Early Check In', quantity: 1, itemId: 38572 }],
    calculatedPrice: 10,
  },
  {
    code: 'HSCKIF',
    description: 'Early Check In (Free)',
    group: false,
    postingRhythm: 'ArrivalNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [{ articleNumber: 'ECI', description: 'Early Check In', quantity: 1, itemId: 38572 }],
    calculatedPrice: 0,
  },
  {
    code: 'HSCOU2',
    description: 'Late Check Out 2pm',
    group: false,
    postingRhythm: 'LastNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [{ articleNumber: 'LCO2', description: 'Late Check Out 2pm', quantity: 1, itemId: 71627 }],
    calculatedPrice: 10,
  },
  {
    code: 'HSCOU4',
    description: 'Late Check Out 4pm',
    group: false,
    postingRhythm: 'LastNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [{ articleNumber: 'LCO4', description: 'Late Check Out 4pm', quantity: 5, itemId: 71628 }],
    calculatedPrice: 20,
  },
  {
    code: 'HSPPFD',
    description: 'Premier Plus Upsell',
    group: false,
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'INCFCP',
    description: 'Premier Inn Breakfast Food Corp (Inc)',
    group: false,
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerAdult',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'DBPROS',
    description: 'Bottle of Prosecco',
    shortDescription: 'Bottle of Prosecco',
    group: false,
    postingRhythm: 'ArrivalNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [{ articleNumber: 'BOP', description: 'Bottle of Prosecco', quantity: 1, itemId: 54603 }],
    calculatedPrice: 0,
  },
  {
    code: 'OBFPRO',
    description: 'Promotion Breakfast',
    group: false,
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerAdult',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'PROBF',
    description: 'Promotion Breakfast',
    shortDescription: 'Promotion Breakfast',
    group: false,
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerAdult',
    addToRate: false,
    printSeparateLine: false,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'OBFREP',
    description: 'Compensation Breakfast (Booked), PI',
    group: false,
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'OBFREC',
    description: 'Compensation Breakfast (Booked), Cont',
    group: false,
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerRoom',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'MHPC30',
    description: 'Test Package Code MH',
    group: false,
    postingRhythm: 'EveryNight',
    priceCalculationRule: 'PerAdult',
    addToRate: false,
    printSeparateLine: false,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'ZR0705',
    description: 'Booking Fee',
    shortDescription: 'Booking Fee',
    group: false,
    postingRhythm: 'ArrivalNight',
    priceCalculationRule: 'PerRoom',
    addToRate: true,
    printSeparateLine: false,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'ZCHR10',
    description: 'On Line Charity Pledge £0.50',
    group: false,
    postingRhythm: 'ArrivalNight',
    priceCalculationRule: 'FlatRate',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'ZCHR11',
    description: 'On Line Charity Pledge £1.50',
    group: false,
    postingRhythm: 'ArrivalNight',
    priceCalculationRule: 'FlatRate',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'ZCHR12',
    description: 'On Line Charity Pledge £2',
    group: false,
    postingRhythm: 'ArrivalNight',
    priceCalculationRule: 'FlatRate',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'ZCHR13',
    description: 'On Line Charity Pledge £2.50',
    group: false,
    postingRhythm: 'ArrivalNight',
    priceCalculationRule: 'FlatRate',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'ZCHRY1',
    description: 'On Line Charity Pledge £3',
    group: false,
    postingRhythm: 'ArrivalNight',
    priceCalculationRule: 'FlatRate',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'ZCHRY2',
    description: 'On Line Charity Pledge £0.30',
    group: false,
    postingRhythm: 'ArrivalNight',
    priceCalculationRule: 'FlatRate',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'ZCHRY6',
    description: 'On Line Charity Pledge £5',
    group: false,
    postingRhythm: 'ArrivalNight',
    priceCalculationRule: 'FlatRate',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
  {
    code: 'ZCHRY7',
    description: 'On Line Charity Pledge £1',
    group: false,
    postingRhythm: 'ArrivalNight',
    priceCalculationRule: 'FlatRate',
    addToRate: false,
    printSeparateLine: true,
    sellSeparate: true,
    postNextDay: false,
    forecastNextDay: false,
    webBookable: false,
    catering: false,
    inventoryItems: [],
    calculatedPrice: 0,
  },
];

export function getPackageConfig(code: string): PackageCodeConfig | undefined {
  return PACKAGE_CODES.find((p) => p.code === code);
}
