excluded:
  - PremierInn/ImportedSDKs
  - PremierInn-DEV-Unit-Tests
  - PremierInnDEVEarlGreyTests
  - PremierInnTests
  - SimpleNetwork/SimpleNetworkTests

disabled_rules:
  - type_name
  - vertical_whitespace
  - identifier_name
  - file_length
  - class_delegate_protocol
  - weak_delegate
  - large_tuple
  - todo

type_body_length:
  warning: 1200
  error: 1200

function_body_length:
  warning: 100
  error: 100

line_length:
  warning: 125
  error: 125
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_multiline_strings: true

trailing_whitespace:
  severity: error
  ignores_empty_lines: false
  ignores_comments: true
  ignores_literals: false

opt_in_rules:
  - multiline_arguments
  - empty_count
  - empty_string
  - redundant_self
  - extension_access_modifier
  - convenience_type
  - unneeded_break_in_switch
  - contains_over_range_nil_comparison
  - implicit_optional_initialization
  - legacy_multiple
  - operator_usage_whitespace
  - implicit_return
  - return_value_from_void_function
  - overridden_super_call
  - private_over_fileprivate
  - prefer_zero_over_explicit_init
  - prefer_self_type_over_type_of_self
  - first_where
  - last_where
  - identical_operands
  - toggle_bool
  - redundant_void_return
  - redundant_discardable_let
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - strict_fileprivate
  - modifier_order

multiline_arguments: { severity: error }
empty_count: { severity: error }
empty_string: { severity: error }
redundant_self: { severity: error }
extension_access_modifier: { severity: error }
convenience_type: { severity: error }
unneeded_break_in_switch: { severity: error }
contains_over_range_nil_comparison: { severity: error }
implicit_optional_initialization: { severity: error }
legacy_multiple: { severity: error }
operator_usage_whitespace: { severity: error }
implicit_return: { severity: error }
return_value_from_void_function: { severity: error }
overridden_super_call: { severity: error }
private_over_fileprivate: { severity: error }
prefer_zero_over_explicit_init: { severity: error }
prefer_self_type_over_type_of_self: { severity: error }
first_where: { severity: error }
last_where: { severity: error }
identical_operands: { severity: error }
toggle_bool: { severity: error }
redundant_void_return: { severity: error }
redundant_discardable_let: { severity: error }
vertical_whitespace_opening_braces: { severity: error }
vertical_whitespace_closing_braces: { severity: error }
strict_fileprivate: { severity: error }
modifier_order: { severity: error }
unused_closure_parameter: { severity: error }
switch_case_alignment: { severity: error }
