export enum BASKET_STATUS {
  FAILED = 'FAILED',
  COMPLETED = 'COMPLETED',
  PROCESSING = 'PROCESSING',
  OPEN = 'OPEN',
  CANCELLED = 'CANCELLED',
  PAY_PENDING = 'PAY_PENDING',
  AMENDING = 'AMENDING',
  AMENDED = 'AMENDED',
  AMEND_FAILED = 'AMEND_FAILED',
  PAYMENT_REQUIRED = 'PAYMENT_REQUIRED',
  NOT_REQUIRED = 'NOT_REQUIRED',
  SECURE_FAILED = 'SECURE_FAILED',
}
