export enum CcuiCardType {
  NEW_CARD = 'NEW_CARD',
  NEW_PIBA = 'NEW_PIBA',
  PIBA_UK = 'NEW_PIBA_UK',
  PIBA_EU = 'NEW_PIBA_EU',
  ACCOUNT_COMPANY = 'ACCOUNT_COMPANY',
  NON_GUARANTEED = 'RESERVE_WITHOUT_CARD',
  PIBAGB = 'PIBAGB',
  PIBADE = 'PIBADE',
}
