export enum ExtrasId {
  EARLY_CHECK_IN = 'HSCKIN',
  LATE_CHECK_OUT = 'HSCOU2',
  ULTIMATE_WIFI = 'FI24HR',
  BOTTLE_OF_PROSECCO = 'DBPROS',
  ULTIMATE_WIFI_FREE = 'FIFR24',
  EARLY_CHECK_IN_FREE = 'HSCKIF',
  LATE_CHECK_OUT_FREE = 'FHSCOU2',
}
