export enum PiCardType {
  SAVED_CARD = 'SAVED_CARD',
  NEW_CARD = 'NEW_CARD',
  NEW_PIBA = 'NEW_PIBA',
  ACCOUNT_COMPANY = 'ACCOUNT_COMPANY',
  RESERVE_WITHOUT_CARD = 'RESERVE_WITHOUT_CARD',
  AMEND_SAVED_CARD = 'AMEND_SAVED_CARD',
  PAYPAL_PAYMENT = 'PAYPAL',
  APGP = 'APGP',
}

export enum PiCardSubType {
  PIBA_UK = 'PIBAGB',
  PIBA_EU = 'PIBADE',
}
