<definitions targetNamespace="http://bartws.micros.com/1.4" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:s0="http://bartws.micros.com/1.4" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<types>
		<s:schema elementFormDefault="qualified" targetNamespace="http://bartws.micros.com/1.4">
			<s:element name="CheckBookingConfirmationRequest">
				<s:complexType>
					<s:sequence>
						<s:element minOccurs="0" name="CheckBookingConfirmationRequest" type="s0:CheckBookingConfirmationRequest"/>
					</s:sequence>
				</s:complexType>
			</s:element>
			<s:complexType name="CheckBookingConfirmationRequest">
				<s:sequence>
					<s:element name="sessionID" type="s:string"/>
					<s:element name="ConfirmationRequest" type="s0:ArrayOfConfirmationConfirmation"/>
				</s:sequence>
			</s:complexType>
			<s:complexType name="ArrayOfConfirmationConfirmation">
				<s:sequence>
					<s:element maxOccurs="unbounded" minOccurs="0" name="Confirmation" nillable="true" type="s0:Confirmation"/>
				</s:sequence>
			</s:complexType>
			<s:complexType name="Confirmation">
				<s:sequence>
					<s:element minOccurs="0" name="id" type="s:long"/>
					<s:element name="type">
						<s:simpleType>
							<s:restriction base="s:string">
								<s:enumeration value="EMAIL"/>
								<s:enumeration value="SMS"/>
							</s:restriction>
						</s:simpleType>
					</s:element>
					<s:element name="destination" type="s:string"/>
				</s:sequence>
			</s:complexType>
			<s:element name="CheckBookingConfirmationRequestResponse">
				<s:complexType>
					<s:sequence>
						<s:element name="CheckBookingConfirmationRequestResult" type="s0:CheckBookingConfirmationResponse"/>
					</s:sequence>
				</s:complexType>
			</s:element>
			<s:complexType name="CheckBookingConfirmationResponse">
				<s:sequence>
					<s:element name="sessionID" type="s:string"/>
					<s:element minOccurs="0" name="confirmationSent" type="s0:ArrayOfconfirmationConfirmationSent"/>
					<s:element minOccurs="0" name="checkBookingConfirmationError">
						<s:simpleType>
							<s:restriction base="s:string">
								<s:enumeration value="MISSING_MANDATORY_FIELD"/>
								<s:enumeration value="INVALID_DATA_IN_FIELD"/>
								<s:enumeration value="INVALID_EMAIL_ADDRESS"/>
								<s:enumeration value="INVALID_MOBILE_NUMBER"/>
							</s:restriction>
						</s:simpleType>
					</s:element>
					<s:element minOccurs="0" name="errorDetail" type="s0:ErrorDetails"/>
				</s:sequence>
			</s:complexType>
			<s:complexType name="ArrayOfconfirmationConfirmationSent">
				<s:sequence>
					<s:element maxOccurs="unbounded" minOccurs="0" name="confirmation" nillable="true" type="s0:ConfirmationSent"/>
				</s:sequence>
			</s:complexType>
			<s:complexType name="ConfirmationSent">
				<s:sequence>
					<s:element minOccurs="0" name="id" type="s:long"/>
					<s:element name="success" type="s:boolean"/>
				</s:sequence>
			</s:complexType>
			<s:complexType name="ErrorDetails">
				<s:sequence>
					<s:element minOccurs="0" name="errorMessage" type="s:string"/>
				</s:sequence>
			</s:complexType>
		</s:schema>
	</types>
	<message name="CheckBookingConfirmationRequestSoapIn">
		<part element="s0:CheckBookingConfirmationRequest" name="parameters"/>
	</message>
	<message name="CheckBookingConfirmationRequestSoapOut">
		<part element="s0:CheckBookingConfirmationRequestResponse" name="parameters"/>
	</message>
	<portType name="CheckBookingSoap">
		<operation name="CheckBookingConfirmationRequest">
			<input message="s0:CheckBookingConfirmationRequestSoapIn"/>
			<output message="s0:CheckBookingConfirmationRequestSoapOut"/>
		</operation>
	</portType>
	<binding name="CheckBookingSoap" type="s0:CheckBookingSoap">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="CheckBookingConfirmationRequest">
			<soap:operation soapAction="http://bartws.micros.com/1.4/ws.CheckBooking.CheckBookingService.CheckBookingConfirmationRequest" style="document"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="CheckBooking">
		<port binding="s0:CheckBookingSoap" name="CheckBookingSoap">
			<soap:address location="https://bookings.premierinn.com:443/csp/sql/ws.CheckBooking.CheckBookingService.cls"/>
		</port>
	</service>
</definitions>