<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:bb="http://corporate.micros.com/1.0"
             xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:s0="http://corporate.micros.com/1.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             targetNamespace="http://corporate.micros.com/1.0">
    <types>
        <s:schema elementFormDefault="qualified" targetNamespace="http://corporate.micros.com/1.0">
            <s:include schemaLocation="../xsd/bart-business-10.xsd"/>
            <s:element name="BookingSummary">
                <s:complexType>
                    <s:sequence>
                        <s:element minOccurs="0" name="request" type="s0:BookingSummaryRequest"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
            <s:complexType name="BookingSummaryRequest">
                <s:sequence>
                    <s:element name="sessionID" type="s:string"/>
                    <s:element name="companyID" type="s:string"/>
                    <s:element name="employeeID" type="s:string"/>
                    <s:element minOccurs="0" name="searchCriteria" type="s:string"/>
                    <s:element minOccurs="0" name="searchDate" type="s:date"/>
                    <s:element name="typeOfBooking">
                        <s:simpleType>
                            <s:restriction base="s:string">
                                <s:enumeration value="U"/>
                                <s:enumeration value="F"/>
                                <s:enumeration value="P"/>
                                <s:enumeration value="C"/>
                            </s:restriction>
                        </s:simpleType>
                    </s:element>
                    <s:element minOccurs="0" name="recordsPerPage" type="s:long"/>
                    <s:element minOccurs="0" name="pageRequired" type="s:long"/>
                </s:sequence>
            </s:complexType>
            <s:element name="BookingSummaryResponse">
                <s:complexType>
                    <s:sequence>
                        <s:element name="BookingSummaryResult" type="s0:BookingSummaryResponse"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
            <s:complexType name="BookingSummaryResponse">
                <s:sequence>
                    <s:element name="bookings" type="s0:ArrayOfBookingSummaryBookingSummary"/>
                    <s:element minOccurs="0" name="endOfFile" type="s:boolean"/>
                    <s:element name="success" type="s:boolean"/>
                    <s:element minOccurs="0" name="errors" type="bb:ArrayOferrorError"/>
                </s:sequence>
            </s:complexType>
            <s:complexType name="ArrayOfBookingSummaryBookingSummary">
                <s:sequence>
                    <s:element maxOccurs="unbounded" minOccurs="0" name="BookingSummary" nillable="true" type="s0:BookingSummary"/>
                </s:sequence>
            </s:complexType>
            <s:complexType name="BookingSummary">
                <s:sequence>
                    <s:element minOccurs="0" name="upcomingBooking" type="s0:UpcomingBooking"/>
                    <s:element minOccurs="0" name="frequentBooking" type="s0:FrequentBooking"/>
                    <s:element minOccurs="0" name="pastBooking" type="s0:PastBooking"/>
                    <s:element minOccurs="0" name="cancelledBooking" type="s0:CancelledBooking"/>
                    <s:element name="bookerStayer">
                        <s:simpleType>
                            <s:restriction base="s:string">
                                <s:enumeration value="STAYER"/>
                                <s:enumeration value="BOOKER"/>
                                <s:enumeration value="SUPER"/>
                            </s:restriction>
                        </s:simpleType>
                    </s:element>
                </s:sequence>
            </s:complexType>
            <s:complexType name="UpcomingBooking">
                <s:sequence>
                    <s:element minOccurs="0" name="hotelCode" type="s:string"/>
                    <s:element minOccurs="0" name="guestHistoryNumber" type="s:string"/>
                    <s:element minOccurs="0" name="guestHistoryRecordNumber" type="s:string"/>
                    <s:element minOccurs="0" name="bookingID" type="s:string"/>
                    <s:element minOccurs="0" name="arrivalDate" type="s:string"/>
                    <s:element minOccurs="0" name="departureDate" type="s:string"/>
                    <s:element minOccurs="0" name="bookedBy" type="s:string"/>
                    <s:element minOccurs="0" name="rateName" type="s:string"/>
                    <s:element minOccurs="0" name="totalCost" type="s0:Price"/>
                    <s:element minOccurs="0" name="bookingFee" type="s0:Price"/>
                    <s:element minOccurs="0" name="outstandingAmount" type="s0:Price"/>
                    <s:element minOccurs="0" name="paymentStatus" type="s:string"/>
                    <s:element minOccurs="0" name="bookingStatus" type="s:string"/>
                    <s:element minOccurs="0" name="frequentBooking" type="s:string"/>
                    <s:element minOccurs="0" name="amendable" type="s:boolean"/>
                    <s:element minOccurs="0" name="rooms" type="s0:ArrayOfRoomRoom"/>
                    <s:element minOccurs="0" name="isMPIBooking" type="s:boolean"/>
                </s:sequence>
            </s:complexType>
            <s:complexType name="Price">
                <s:sequence>
                    <s:element name="amount" type="s:decimal"/>
                    <s:element name="currency" type="s:string"/>
                </s:sequence>
            </s:complexType>
            <s:complexType name="ArrayOfRoomRoom">
                <s:sequence>
                    <s:element maxOccurs="unbounded" minOccurs="0" name="Room" nillable="true" type="s0:Room"/>
                </s:sequence>
            </s:complexType>
            <s:complexType name="Room">
                <s:sequence>
                    <s:element minOccurs="0" name="roomType" type="s:string"/>
                    <s:element minOccurs="0" name="leadGuest" type="bb:Person"/>
                </s:sequence>
            </s:complexType>
            <s:complexType name="FindEmployee">
                <s:complexContent>
                    <s:extension base="bb:Person">
                        <s:sequence>
                            <s:element name="employeeID" type="s:string"/>
                            <s:element name="companyID" type="s:string"/>
                            <s:element name="emailAddress" type="s:string"/>
                            <s:element minOccurs="0" name="employeeStatus">
                                <s:simpleType>
                                    <s:restriction base="s:string">
                                        <s:enumeration value="ACTIVE"/>
                                        <s:enumeration value="INACTIVE"/>
                                        <s:enumeration value="SUSPENDED"/>
                                        <s:enumeration value="DEACTIVATED"/>
                                    </s:restriction>
                                </s:simpleType>
                            </s:element>
                            <s:element minOccurs="0" name="accessLevel">
                                <s:simpleType>
                                    <s:restriction base="s:string">
                                        <s:enumeration value="STAYER"/>
                                        <s:enumeration value="SELF"/>
                                        <s:enumeration value="BOOKER"/>
                                        <s:enumeration value="SUPER"/>
                                    </s:restriction>
                                </s:simpleType>
                            </s:element>
                        </s:sequence>
                    </s:extension>
                </s:complexContent>
            </s:complexType>
            <s:complexType name="SelfRegisterContact">
                <s:complexContent>
                    <s:extension base="bb:Person">
                        <s:sequence>
                            <s:element name="emailAddress" type="s:string"/>
                            <s:element name="phoneNumber" type="s:string"/>
                        </s:sequence>
                    </s:extension>
                </s:complexContent>
            </s:complexType>
            <s:complexType name="UpdateSalesEmployee">
                <s:complexContent>
                    <s:extension base="bb:Person">
                        <s:sequence>
                            <s:element name="employeeID" type="s:string"/>
                            <s:element name="emailAddress" type="s:string"/>
                        </s:sequence>
                    </s:extension>
                </s:complexContent>
            </s:complexType>
            <s:complexType name="FrequentBooking">
                <s:sequence>
                    <s:element minOccurs="0" name="hotelCode" type="s:string"/>
                    <s:element minOccurs="0" name="arrivalDate" type="s:string"/>
                    <s:element minOccurs="0" name="departureDate" type="s:string"/>
                    <s:element minOccurs="0" name="rooms" type="s0:ArrayOfRoomRequirementRoomRequirement"/>
                    <s:element minOccurs="0" name="employeeStatus" type="s:string"/>
                    <s:element minOccurs="0" name="frequentBookingID" type="s:string"/>
                </s:sequence>
            </s:complexType>
            <s:complexType name="ArrayOfRoomRequirementRoomRequirement">
                <s:sequence>
                    <s:element maxOccurs="unbounded" minOccurs="0" name="RoomRequirement" nillable="true" type="s0:RoomRequirement"/>
                </s:sequence>
            </s:complexType>
            <s:complexType name="RoomRequirement">
                <s:sequence>
                    <s:element minOccurs="0" name="firstName" type="s:string"/>
                    <s:element minOccurs="0" name="lastName" type="s:string"/>
                    <s:element minOccurs="0" name="roomType" type="s:string"/>
                    <s:element minOccurs="0" name="numOfAdults" type="s:decimal"/>
                    <s:element minOccurs="0" name="numOfChildren" type="s:decimal"/>
                    <s:element minOccurs="0" name="numOfCots" type="s:decimal"/>
                </s:sequence>
            </s:complexType>
            <s:complexType name="PastBooking">
                <s:sequence>
                    <s:element name="hotelCode" type="s:string"/>
                    <s:element minOccurs="0" name="guestHistoryNumber" type="s:string"/>
                    <s:element minOccurs="0" name="guestHistoryRecordNumber" type="s:string"/>
                    <s:element minOccurs="0" name="bookingID" type="s:string"/>
                    <s:element minOccurs="0" name="arrivalDate" type="s:string"/>
                    <s:element minOccurs="0" name="departureDate" type="s:string"/>
                    <s:element minOccurs="0" name="bookedBy" type="s:string"/>
                    <s:element minOccurs="0" name="rateName" type="s:string"/>
                    <s:element minOccurs="0" name="totalCost" type="s0:Price"/>
                    <s:element minOccurs="0" name="bookingFee" type="s0:Price"/>
                    <s:element minOccurs="0" name="paymentStatus" type="s:string"/>
                    <s:element minOccurs="0" name="rooms" type="s0:ArrayOfRoomRoom"/>
                    <s:element name="isMPIBooking" type="s:boolean"/>
                </s:sequence>
            </s:complexType>
            <s:complexType name="CancelledBooking">
                <s:sequence>
                    <s:element minOccurs="0" name="hotelCode" type="s:string"/>
                    <s:element minOccurs="0" name="guestHistoryNumber" type="s:string"/>
                    <s:element minOccurs="0" name="guestHistoryRecordNumber" type="s:string"/>
                    <s:element minOccurs="0" name="bookingID" type="s:string"/>
                    <s:element minOccurs="0" name="cancellationID" type="s:string"/>
                    <s:element minOccurs="0" name="arrivalDate" type="s:string"/>
                    <s:element minOccurs="0" name="departureDate" type="s:string"/>
                    <s:element minOccurs="0" name="bookedBy" type="s:string"/>
                    <s:element minOccurs="0" name="rateName" type="s:string"/>
                    <s:element minOccurs="0" name="totalCost" type="s0:Price"/>
                    <s:element minOccurs="0" name="bookingFee" type="s0:Price"/>
                    <s:element minOccurs="0" name="paymentStatus" type="s:string"/>
                    <s:element minOccurs="0" name="rooms" type="s0:ArrayOfRoomRoom"/>
                    <s:element minOccurs="0" name="isMPIBooking" type="s:boolean"/>
                </s:sequence>
            </s:complexType>
            <s:element name="UserLogin">
                <s:complexType>
                    <s:sequence>
                        <s:element minOccurs="0" name="request" type="s0:UserLoginRequest"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
            <s:complexType name="UserLoginRequest">
                <s:sequence>
                    <s:element name="userName" type="s:string"/>
                    <s:element name="password" type="s:string"/>
                </s:sequence>
            </s:complexType>
            <s:element name="UserLoginResponse">
                <s:complexType>
                    <s:sequence>
                        <s:element name="UserLoginResult" type="s0:UserLoginResponse"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
            <s:complexType name="UserLoginResponse">
                <s:sequence>
                    <s:element name="sessionID" type="s:string"/>
                    <s:element name="companyID" type="s:string"/>
                    <s:element name="employee" type="bb:Employee"/>
                    <s:element name="basicCompanyDetails" type="bb:BasicCompanyDetails"/>
                    <s:element minOccurs="0" name="setupDetails" type="bb:CompanySetupDetails"/>
                    <s:element minOccurs="0" name="numberOfEmployees" type="s:decimal"/>
                    <s:element minOccurs="0" name="upcomingBookings" type="bb:ArrayOfUpcomingBookingSummaryUpcomingBookingSummary"/>
                    <s:element name="setupProgress">
                        <s:simpleType>
                            <s:restriction base="s:string">
                                <s:enumeration value="COMPANY_DETAILS"/>
                                <s:enumeration value="PAYMENT_OPTIONS"/>
                                <s:enumeration value="MANAGEMENT_INFORMATION"/>
                                <s:enumeration value="BOOKING_ALLOWANCES"/>
                                <s:enumeration value="BOOKING_ALERTS"/>
                                <s:enumeration value="COMPLETE"/>
                            </s:restriction>
                        </s:simpleType>
                    </s:element>
                    <s:element name="miSetupRequired" type="s:boolean"/>
                    <s:element name="changeCompanyName" type="s:boolean"/>
                    <s:element minOccurs="0" name="awaitingApproval" type="s:decimal"/>
                    <s:element minOccurs="0" name="tetheredGuid" type="s:string"/>
                    <s:element minOccurs="0" name="MyPILink" type="s:string"/>
                    <s:element name="dismissMPILink" type="s:boolean"/>
                    <s:element name="success" type="s:boolean"/>
                    <s:element minOccurs="0" name="errors" type="bb:ArrayOferrorError"/>
                </s:sequence>
            </s:complexType>
            <s:element name="deleteFrequentBooking">
                <s:complexType>
                    <s:sequence>
                        <s:element minOccurs="0" name="request" type="s0:deleteFrequentBookingRequest"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
            <s:complexType name="deleteFrequentBookingRequest">
                <s:sequence>
                    <s:element name="sessionID" type="s:string"/>
                    <s:element name="companyID" type="s:string"/>
                    <s:element name="employeeID" type="s:string"/>
                    <s:element name="frequentBookingID" type="s:string"/>
                </s:sequence>
            </s:complexType>
            <s:element name="deleteFrequentBookingResponse">
                <s:complexType>
                    <s:sequence>
                        <s:element name="deleteFrequentBookingResult" type="s0:deleteFrequentBookingResponse"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
            <s:complexType name="deleteFrequentBookingResponse">
                <s:sequence>
                    <s:element name="success" type="s:boolean"/>
                    <s:element minOccurs="0" name="errors" type="bb:ArrayOferrorError"/>
                </s:sequence>
            </s:complexType>
            <s:element name="emailCopyInvoice">
                <s:complexType>
                    <s:sequence>
                        <s:element minOccurs="0" name="request" type="s0:EmailCopyInvoiceRequest"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
            <s:complexType name="EmailCopyInvoiceRequest">
                <s:sequence>
                    <s:element name="sessionID" type="s:string"/>
                    <s:element name="companyID" type="s:string"/>
                    <s:element name="employeeID" type="s:string"/>
                    <s:element name="invoiceHistoryNumber" type="s:string"/>
                    <s:element name="invoiceRecordNumber" type="s:string"/>
                </s:sequence>
            </s:complexType>
            <s:element name="emailCopyInvoiceResponse">
                <s:complexType>
                    <s:sequence>
                        <s:element name="emailCopyInvoiceResult" type="s0:EmailCopyInvoiceResponse"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
            <s:complexType name="EmailCopyInvoiceResponse">
                <s:sequence>
                    <s:element name="success" type="s:boolean"/>
                    <s:element minOccurs="0" name="errors" type="bb:ArrayOferrorError"/>
                </s:sequence>
            </s:complexType>
            <s:element name="resetPassword">
                <s:complexType>
                    <s:sequence>
                        <s:element minOccurs="0" name="request" type="s0:ResetPasswordRequest"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
            <s:complexType name="ResetPasswordRequest">
                <s:sequence>
                    <s:element name="key" type="s:string"/>
                    <s:element name="password" type="s:string"/>
                </s:sequence>
            </s:complexType>
            <s:element name="resetPasswordResponse">
                <s:complexType>
                    <s:sequence>
                        <s:element name="resetPasswordResult" type="s0:ResetPasswordResponse"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
            <s:complexType name="ResetPasswordResponse">
                <s:sequence>
                    <s:element minOccurs="0" name="sessionID" type="s:string"/>
                    <s:element name="success" type="s:boolean"/>
                    <s:element minOccurs="0" name="errors" type="bb:ArrayOferrorError"/>
                </s:sequence>
            </s:complexType>
            <s:element name="resetPasswordRequest">
                <s:complexType>
                    <s:sequence>
                        <s:element minOccurs="0" name="request" type="s0:ResetPasswordRequestRequest"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
            <s:complexType name="ResetPasswordRequestRequest">
                <s:sequence>
                    <s:element name="emailAddress" type="s:string"/>
                </s:sequence>
            </s:complexType>
            <s:element name="resetPasswordRequestResponse">
                <s:complexType>
                    <s:sequence>
                        <s:element name="resetPasswordRequestResult" type="s0:ResetPasswordRequestResponse"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
            <s:complexType name="ResetPasswordRequestResponse">
                <s:sequence>
                    <s:element name="success" type="s:boolean"/>
                    <s:element minOccurs="0" name="errors" type="bb:ArrayOferrorError"/>
                </s:sequence>
            </s:complexType>
            <s:element name="saveFrequentBooking">
                <s:complexType>
                    <s:sequence>
                        <s:element minOccurs="0" name="request" type="s0:SaveFrequentBookingRequest"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
            <s:complexType name="SaveFrequentBookingRequest">
                <s:sequence>
                    <s:element name="sessionID" type="s:string"/>
                    <s:element name="companyID" type="s:string"/>
                    <s:element name="employeeID" type="s:string"/>
                    <s:element name="bookingReference" type="s:string"/>
                </s:sequence>
            </s:complexType>
            <s:element name="saveFrequentBookingResponse">
                <s:complexType>
                    <s:sequence>
                        <s:element name="saveFrequentBookingResult" type="s0:SaveFrequentBookingResponse"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
            <s:complexType name="SaveFrequentBookingResponse">
                <s:sequence>
                    <s:element name="success" type="s:boolean"/>
                    <s:element minOccurs="0" name="errors" type="bb:ArrayOferrorError"/>
                    <s:element minOccurs="0" name="frequentBookingID" type="s:decimal"/>
                </s:sequence>
            </s:complexType>
        </s:schema>
    </types>
    <message name="BookingSummarySoapIn">
        <part name="parameters" element="s0:BookingSummary"/>
    </message>
    <message name="BookingSummarySoapOut">
        <part name="parameters" element="s0:BookingSummaryResponse"/>
    </message>
    <message name="UserLoginSoapIn">
        <part name="parameters" element="s0:UserLogin"/>
    </message>
    <message name="UserLoginSoapOut">
        <part name="parameters" element="s0:UserLoginResponse"/>
    </message>
    <message name="deleteFrequentBookingSoapIn">
        <part name="parameters" element="s0:deleteFrequentBooking"/>
    </message>
    <message name="deleteFrequentBookingSoapOut">
        <part name="parameters" element="s0:deleteFrequentBookingResponse"/>
    </message>
    <message name="emailCopyInvoiceSoapIn">
        <part name="parameters" element="s0:emailCopyInvoice"/>
    </message>
    <message name="emailCopyInvoiceSoapOut">
        <part name="parameters" element="s0:emailCopyInvoiceResponse"/>
    </message>
    <message name="resetPasswordSoapIn">
        <part name="parameters" element="s0:resetPassword"/>
    </message>
    <message name="resetPasswordSoapOut">
        <part name="parameters" element="s0:resetPasswordResponse"/>
    </message>
    <message name="resetPasswordRequestSoapIn">
        <part name="parameters" element="s0:resetPasswordRequest"/>
    </message>
    <message name="resetPasswordRequestSoapOut">
        <part name="parameters" element="s0:resetPasswordRequestResponse"/>
    </message>
    <message name="saveFrequentBookingSoapIn">
        <part name="parameters" element="s0:saveFrequentBooking"/>
    </message>
    <message name="saveFrequentBookingSoapOut">
        <part name="parameters" element="s0:saveFrequentBookingResponse"/>
    </message>
    <portType name="DashboardServiceSoap">
        <operation name="BookingSummary">
            <input message="s0:BookingSummarySoapIn"/>
            <output message="s0:BookingSummarySoapOut"/>
        </operation>
        <operation name="UserLogin">
            <input message="s0:UserLoginSoapIn"/>
            <output message="s0:UserLoginSoapOut"/>
        </operation>
        <operation name="deleteFrequentBooking">
            <input message="s0:deleteFrequentBookingSoapIn"/>
            <output message="s0:deleteFrequentBookingSoapOut"/>
        </operation>
        <operation name="emailCopyInvoice">
            <input message="s0:emailCopyInvoiceSoapIn"/>
            <output message="s0:emailCopyInvoiceSoapOut"/>
        </operation>
        <operation name="resetPassword">
            <input message="s0:resetPasswordSoapIn"/>
            <output message="s0:resetPasswordSoapOut"/>
        </operation>
        <operation name="resetPasswordRequest">
            <input message="s0:resetPasswordRequestSoapIn"/>
            <output message="s0:resetPasswordRequestSoapOut"/>
        </operation>
        <operation name="saveFrequentBooking">
            <input message="s0:saveFrequentBookingSoapIn"/>
            <output message="s0:saveFrequentBookingSoapOut"/>
        </operation>
    </portType>
    <binding name="DashboardServiceSoap" type="s0:DashboardServiceSoap">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="BookingSummary">
            <soap:operation soapAction="http://corporate.micros.com/1.0/ws.Corporate.DashboardService.BookingSummary" style="document"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="UserLogin">
            <soap:operation soapAction="http://corporate.micros.com/1.0/ws.Corporate.DashboardService.UserLogin" style="document"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="deleteFrequentBooking">
            <soap:operation soapAction="http://corporate.micros.com/1.0/ws.Corporate.DashboardService.deleteFrequentBooking" style="document"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="emailCopyInvoice">
            <soap:operation soapAction="http://corporate.micros.com/1.0/ws.Corporate.DashboardService.emailCopyInvoice" style="document"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="resetPassword">
            <soap:operation soapAction="http://corporate.micros.com/1.0/ws.Corporate.DashboardService.resetPassword" style="document"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="resetPasswordRequest">
            <soap:operation soapAction="http://corporate.micros.com/1.0/ws.Corporate.DashboardService.resetPasswordRequest" style="document"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="saveFrequentBooking">
            <soap:operation soapAction="http://corporate.micros.com/1.0/ws.Corporate.DashboardService.saveFrequentBooking" style="document"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="DashboardService">
        <port name="DashboardServiceSoap" binding="s0:DashboardServiceSoap">
            <soap:address location="https://inntouch.slough.microsdc.com:443/csp/sql/ws.Corporate.DashboardService.cls"/>
        </port>
    </service>
</definitions>