openapi: 3.1.0
info:
  title: Feedback Service Opera API Documentation
  description: <p>Endpoints for managing customer feedback.</p>
  version: "1.4"
servers:
- url: http://localhost:9033
  description: Generated server url
tags:
- name: Actuator
  description: Monitor and interact
  externalDocs:
    description: Spring Boot Actuator Web API Documentation
    url: https://docs.spring.io/spring-boot/docs/current/actuator-api/html/
paths:
  /feedback:
    post:
      tags:
      - feedback-controller
      summary: Add Feedback
      description: Adds customer feedback
      operationId: addFeedback
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Feedback"
        required: true
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "400":
          description: 'Error Occurred '
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeedbackResponse"
  /feedback-service/actuator:
    get:
      tags:
      - Actuator
      summary: Actuator root web endpoint
      operationId: links
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
  /feedback-service/actuator/prometheus:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'prometheus'
      operationId: scrape
      parameters:
      - name: format
        in: query
        schema:
          type: string
          enum:
          - CONTENT_TYPE_004
          - CONTENT_TYPE_OPENMETRICS_100
          - CONTENT_TYPE_PROTOBUF
      - name: includedNames
        in: query
        schema:
          type: string
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: OK
          content:
            text/plain;version=0.0.4;charset=utf-8:
              schema:
                type: object
            application/openmetrics-text;version=1.0.0;charset=utf-8:
              schema:
                type: object
            application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited:
              schema:
                type: object
  /feedback-service/actuator/metrics:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'metrics'
      operationId: listNames
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/json:
              schema:
                type: object
  /feedback-service/actuator/metrics/{requiredMetricName}:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'metrics-requiredMetricName'
      operationId: metric
      parameters:
      - name: requiredMetricName
        in: path
        required: true
        schema:
          type: string
      - name: tag
        in: query
        schema:
          type: string
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/json:
              schema:
                type: object
        "404":
          description: Not Found
  /feedback-service/actuator/info:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'info'
      operationId: info
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/json:
              schema:
                type: object
  /feedback-service/actuator/health:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'health'
      operationId: health
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/json:
              schema:
                type: object
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          example: "001"
          minLength: 1
        details:
          type: array
          example:
          - Error message
          items:
            type: string
      required:
      - code
      - details
    Feedback:
      type: object
      properties:
        whb_wfsource:
          type: string
        title:
          type: string
          minLength: 1
        whb_wfbookingrefifapplicable:
          type: string
        whb_wfcontactnumber:
          type: string
          minLength: 1
        whb_wfdateofstayifapplicable:
          type: string
        whb_wfemailaddress:
          type: string
          minLength: 1
        whb_wfreasonforfeedback:
          type: string
          minLength: 1
        whb_summary:
          type: string
          minLength: 1
        whb_wffeedbacktype:
          type: integer
          format: int32
        whb_wffirstname:
          type: string
          minLength: 1
        whb_wflastname:
          type: string
          minLength: 1
        whb_wfpostcode:
          type: string
          minLength: 1
        whb_wfhotelname:
          type: string
        whb_wfididntbookthroughpremierinncom:
          type: boolean
        whb_contacttype:
          type: integer
          format: int32
        whb_reasonforcontact:
          type: integer
          format: int32
        whb_wftypeofvisit:
          type: string
        whb_loyaltycardnumber:
          type: string
        whb_wfchecknumber:
          type: string
        whb_dateofvisit:
          type: string
        whb_wfsleep:
          type: boolean
        whb_wfreported:
          type: boolean
      required:
      - title
      - whb_contacttype
      - whb_reasonforcontact
      - whb_summary
      - whb_wfcontactnumber
      - whb_wfemailaddress
      - whb_wffeedbacktype
      - whb_wffirstname
      - whb_wfididntbookthroughpremierinncom
      - whb_wflastname
      - whb_wfpostcode
      - whb_wfreasonforfeedback
    FeedbackResponse:
      type: object
      properties:
        caseReferenceId:
          type: string
    Link:
      type: object
      properties:
        href:
          type: string
        templated:
          type: boolean
