@startuml
'https://plantuml.com/sequence-diagram
header piba-account-service
title /invoices/download/{schemeCustomerId}/{tetheredUserGuid}/{fileId}
autonumber
participant "UI" as Client
participant "PibaAccountController" as PAC
participant "PibaAccountService" as PAS
participant "PibaGuidServiceClient" as PGSC
participant "WorldlineTransformer" as WLT
participant "worldlineWebServiceTemplate" as WWST
participant "WorldLineAccountResponseValidator" as WLARV

Client -> PAC : Calls POST /proposecreditlimit with CreditProposeLimitRequest :: SchemeCustomerId:{} TetheredUserGuid:{}
PAC -> PAS : Calls downloadInvoices with schemeCustomerId, tetheredUserGuid, fileId
PAS -> WLT : Dispatches Request  CustomerAccountInvoiceDownload via method marshalSendAndReceive
WLT -> PAS : Returns CreditProposeNewLimitResponse
PAS -> WLARV : Validate the Response
WLT -> PAS : Return CreditProposeLimitResponse from toCreditProposeNewLimitResponse
PAS -> PAC : Return CustomerAccountInvoiceListDownloadResponse
PAC -> Client : Return CustomerAccountInvoiceListDownloadResponse Binary Data
@enduml