import {
  formatRatePrice,
  formatCurrency,
  formatPrice,
  formatPriceWithDecimal,
  getPriceValueWithDecimal,
  formatDataTestId,
  formatAssetsUrl,
  formatInnerHTMLAssetUrls,
  formatDate,
  checkDateFormatter,
  formatNextLocaleLink,
  formatFindBookingToken,
  formatUrlTermsConditions,
  formatGuestTitleOptions,
  formatTextWithSpace,
  replaceWithEmptyString,
  uppercaseAndReplace,
  upperFirst,
  upperOnlyFirst,
  swapKeysAndValues,
  formatForMobile,
  superRoleFilter,
  langFilter,
  removeHtmlTags,
  createReservationDetails,
  matchSilentSubstitutions,
  getYearsAgoFromNow,
  getPathForLocale,
  renderSanitizedHtml,
  formatBillingAddress,
  formatRequiredString,
  formatGuests,
  formatAccompanyingGuest,
  getObjectFormatNumber,
  parsePhoneNumber,
  getCanonicalLocale,
  getOneTrustConfigByLocale,
  isOneTrustCookieConsentActive,
} from './formatters';
import {
  // AUTH GETTERS
  ID_TOKEN_COOKIE,
  ACCESS_TOKEN_COOKIE,
  EMAIL_COOKIE,
  OPERA_COMPANY_ID,
  CDH_COMPANY_ID,
  CDH_EMPLOYEE_ID,
  MAX_AGE,
  getAuthCookie,
  getAccessTokenCookie,
  getLoggedInUserInfo,
  decodeIdToken,
  logout, // CONFIRMATION GETTERS
  getRoomGroups,
  getRoomTotalprice,
  getRoomExtrasTotal,
  getMealPrice,
  getAdultMealDescription,
  getChildrenMealDescription, // FIND BOOKING TOKEN GETTERS
  getFindBookingToken,
  cleanupFindBookingToken, // COMMON GETTERS
  getNightsNumber,
  getNoOfDaysInYear,
  getDistanceUnitBasedOnLocale,
  getDistanceUnitBasedOnLocaleSb,
  getCardEnding,
  getSecureTwoURL,
  getSortedCountries,
  getSortedCountriesByCurrentLang,
  getSortedCountriesByCurrentLangCcui,
  getMaxValueFromRoomStays,
  getMaxValueFromRoomStaysBC,
  getMaxValueFromHDPRoomTypes,
  getTotalPeople,
  getPlaceholderString,
  getRoomsPlaceholder,
  getSelectedDonationPackage,
  getIDVPassedStatus,
  getBookingDetailsForCard,
  getRoomDetailsForBartCard,
  getRoomTypeLabelsBySourceSystem, // GUEST DETAILS GETTERS
  getCityTaxMessages, // HOTEL DETAILS GETTERS
  getDefaultDataFromBooking,
  getAvailabilityParamsFromUrl,
  getStaticHotelInformationQueryDateDataFromUrl,
  getHotelAvailabilityQueryKey,
  isHotelOpeningSoon, // LABELS GETTERS
  isFaqValidForRender,
  transformLabels,
  getI18nLabels,
  getServerSideCustomLocale, // PAYMENT GETTERS
  getBookingSummaryData,
  getIsBillingAddressDisplayed,
  getIsDonationsDisplayed,
  getIsDonationInfoBoxDisplayed,
  setBusinessAllowancesSections,
  getIsBBCardDetailsDisplayed,
  getBillingAddress,
  getPaymentError, // SEARCH EMPLOYEES GETTERS
  getListOfEmployees, // SEARCH RESULTS GETTERS
  getPlace,
  getDefaultRooms,
  getSearchResultsPageSize,
  getPromoId,
  getNewSearchResultsPI,
  getNewSearchResultsBB,
  getNewSearchResultsCCUI,
  setPromoInfoState,
  getSessionStorageValuesForBookings,
  getAvailableRoomTypes,
  getRoomClassByRoomClassCode,
  getRateClassification,
  getRoomRatesThatMatchRoomClassifications,
  getAvailabilityRoomClassIndexes,
  getAllRoomTypesFromRates,
  getRoomTypesFromQuery,
  getPaypalOptionsParams,
  getPaypalDeviceData,
  getSelectedPMSRoomTypesAndSpecialRequests,
  getTwinRoomSelectionPrices,
  getLocalStorageMock,
  getAmendSectionTranslations,
  displayStorageSubstitutionLabels,
  getTitleDropdownValues,
  getA2CBusinessAllowances,
  getExtrasPackagePrice,
  extrasNamingCheck,
  filterWiFiForPlusRooms,
  getCentrallyStoredCardBillingAddress,
  getAccessibleRoomData,
  isAccessibleRoomType,
  getPIBrandText,
  getRoomClassByCodeAndType,
  getBathRoomSelectedPMSRoomTypesAndSpecialRequests,
  getSelectedRoomClassCode,
  getRoomClassTextForGAllery,
  getTodayTomorrowDate,
  filterRoomsByRoomClass,
  getAccessibleRoomSelectedPMSRoomTypesAndSpecialRequests,
  readPromotionsInformation,
  shouldDisplayPromoBanner,
  getBrandFromSnowDropSuggestions,
  type PromotionsInformation,
  PromoActionsType,
  hasMatchingPromotionCode,
  getActivePromotionCode,
  getUserAndRoles,
  extractMultiHotelAvailabilities,
  getRoomRatesWithRateInformation,
  mapBookingInformationForReuseBooking,
  checkIsBookingForSomeoneElse,
  getBrandForUnleashContext,
  extractPromoBoxData,
} from './getters';
import { getGQLClient } from './gql/client';
import {
  // BASE64 HELPERS
  encodeToBase64,
  decodeFromBase64, // BASKET DETAILS COOKIE HELPERS
  getCookie,
  setCookie,
  setCookieWithDefaultDomain,
  COOKIE_MODAL_CLOSED_EVENT,
  DYNATRACE_CONSENT_DISABLED,
  DYNATRACE_CONSENT_ENABLED,
  DYNATRACE_CONSENT_COOKIE_NAME,
  DYNATRACE_SYNC_COOKIE,
  hasCustomDynatraceConsent,
  hasOneTrustDynatraceConsent,
  getDynatraceConsentPaths,
  ONETRUST_GROUPS_UPDATED_EVENT,
  ONETRUST_DYNATRACE_CONSENT_GROUP,
  syncDynatraceConsent,
  syncDynatraceConsentFromCookie,
  syncDynatraceConsentFromOneTrust,
  setBookingCookie,
  deleteCookie,
  deleteCookieWithDefaultDomain, // DROPDOWN HELPERS
  createOptionsAdultsChildrenDropdown,
  getAdultsChildrenOptions,
  getRoomTypeOptions,
  getMappedRooms, // HANDLE REF HEIGHT CHANGE HELPER
  handleRefHeightChange, // WAIT FOR ELEMENT HELPER
  waitForElement,
  handleManageBookingParamsCCUI,
  getUnleashToggles,
  akamaiImageLoader,
  isIVMEnabled,
  displayMethodType,
  displayPaymentHelpText,
  isApplePayConfigured,
  isGooglePayConfigured,
  getDonationForBooking,
  getTotalCost,
  sortImagesByOrder,
  hashString,
  isObjectNotEmpty,
  applyDefaultPaymentRestrictions,
  isSecureBookingPage,
  secureBookingType,
  BookingDataType,
  getBookingConfirmationMessage,
  shouldDisplaySecureBooking,
  isValidSecureBooking,
  getValidOrTodayDate,
  getBookingFlowId,
  getInputTypographyOverride,
  getTextStyleTypographyOverride, // PAYMENT PARAMS HELPERS
  buildPaymentParams,
  buildCardFromPaymentMethod,
  updateSelectedPaymentOption,
  getBookingForSomeoneElse,
  type BuildPaymentParamsInput,
  type GetBookingForSomeoneElseInput,
} from './helpers';
import {
  roomDefaultValueIfError,
  isInnBusinessApp,
  hasSameRoomTypeCodes,
} from './helpers/roomHelpers';
import {
  useBookingConfimationData,
  useBookingSpinner,
  useCookieForABTesting,
  useCompanyDetails,
  useCustomLocale,
  useCustomLocaleAppRouter,
  useDebounce,
  useFeatureToggle,
  useHotelAvailabilityBB,
  useHotelAvailabilityCCUI,
  useHotelAvailability,
  useHotelRatesInformationBB,
  useHotelRatesInformationCCUI,
  useIPageSubmission,
  useLocalStorage,
  useSessionStorage,
  useOrientation,
  useSetOrientation,
  usePackages,
  graphQLRequest,
  useQueryRequest,
  useMutationRequest,
  axiosRequest,
  useRestQueryRequest,
  useRestMutationRequest,
  ProxyOptions,
  useScreenSize,
  useSetScreenSize,
  useStaticHotelInformation,
  useUserDetails,
  usePollBasketStatus,
  useFeatureSwitch,
  useIsExternalSearch,
  useScrolledPast,
  useElementVisited,
  useHotelBrands,
  useSilentRoomsMatch,
  usePaymentPaypal,
  useGetCountryLanguage,
  useUpdateSearchParams,
  useScrollVisibility,
  usePaymentMethod,
  usePaymentData,
  usePaymentAnalytics,
  useElementDimensions,
  useForDiscountedRateMicroSite,
  useForDiscountedRateFlag,
  useHotelRatesInformationDiscountRate,
  useHotelAvailabilityDiscountRate,
  useDiscountRateInfoHotelAvailability,
  getRatePlanCode,
  getCorporateDiscountRatePlanCode,
  useUpdateRateName,
  useGetDiscountRateComapnyId,
  useGetDiscountRateReservationData,
  usePromotionsNotification,
  useCookieWatcher,
  useInnBusinessLogin,
  useOutsideClick,
  useHorizontalScroll,
  useSoftBundles,
  usePromoTranslation,
  useMobileControlsDisplay,
  useAmendCookieValidation,
  useSemanticTypography,
} from './hooks';
// import useSetOrientation, { useOrientation } from './restaurants/hooks/use-orientation';
// import useSetScreenSize, { useScreenSize } from './restaurants/hooks/use-screensize';
import {
  graphQLRequestRestaurants as restaurantGraphQLRequest,
  useQueryRequestRestaurants as restaurantUseQueryRequest,
  useMutationRequestRestaurants as restaurantUseMutationRequest,
} from './hooks/use-request';
import clientLogger from './logger/clientLogger';
import {
  getLogger,
  instrument,
  instrumentQueryClient,
  tracingCookie,
  getDefaultSessionTracing,
  getClientDefaultSessionTracing,
  logger,
} from './logger/logger';
import QueriesLogger from './logger/queriesLogger';
import { mappingBookingStatus } from './mappers/bookingStatus';
// RESTAURANTS EXPORTS
import { type AnalyticsData as RestaurantAnalyticsData } from './restaurants/analytics';
import { formatDateToString, fetchFormattedDateValues } from './restaurants/getters';
import { getGQLClient as restaurantGetGQLClient } from './restaurants/gql/client';
import {
  dropdrownManipulatorFn,
  replaceInputPlaceholder,
} from './restaurants/helpers/aemContentHelper';
import { getCommonParams } from './restaurants/helpers/getCommonParams';
import { getRestaurantBrandGTMId } from './restaurants/helpers/getGTMID';
import {
  // ANCILLARIES SELECTORS
  enhanceMeal,
  enhancePrivacyPolicyMoreInfoItem,
  sortMealsByOrderOrName,
  adultsMealsSelector,
  freeBreakfastMaxAllowance,
  freeBreakfastMaxSelectedAllowance,
  childrenMealsSelector,
  menusSelector,
  securityNoticeMoreInfoDataSelector,
  enhanceSelectedMeals,
  selectedMealsPerRoomSelector,
  roomInformationSelector,
  numberOfSelectionsPerRoomSelector,
  mealsMapperSelector,
  autocompleteMeals,
  calculateTotalCostRoomSelection,
  formatImportantNotes,
  getImportantMessages,
  getUniqueRoomProperties,
  checkIfExistPreselection,
  shouldDisplayAutocompleteNotification,
  transformBartIdToOperaId,
  isCityTaxAvailable, // BUSINESS BOOKER SELECTORS
  isGuestDetailsPageAllowed,
  isDataCollectionMsgAndFormVisible, // COMMON SELECTORS
  hotelInformationSelector,
  enhanceCheckoutStepList,
  bookingGuestCount, // GUEST DETAILS SELECTORS
  generateSuggestionList,
  boldMatchCharacters,
  isTheSameGuest,
  addReservationNumber,
  sortMealsByReservationId,
  isArrivalDateWithinSetHours,
  updateSilentSubstLocalStorage,
  filterPackagesByAncillariesCloseOut,
  getCurrentReservationStorageData,
  extrasPackagesMapperSelector,
  addOrRemoveExtrasRoom,
  roomPackageSelection,
  addOrRemoveAllRoomsExtras,
} from './selectors';
import {
  updateAmendPageAnalytics,
  analytics,
  timeTrackerSeconds,
  restaurantFormAnalytics,
  analyticsConfirmation,
  AnalyticsProvider,
  AnalyticsProviderCCUI,
  initConfirmationAnalytics,
  updateConfirmationAnalytics,
  analyticsConfirmationPageName,
  updateDashboardAnalytics,
  updateHotelDisplayPageAnalytics,
  updateSearchResultsAnalytics,
  setPageAnalytics,
  formatAnalyticsFunnelStep,
  setAnalyticsUser,
  analyticsTrackings,
  updateAncillariesAnalytics,
  updateConfirmationPageAnalytics,
  extrasPackagesAnalyticsMap,
  updateDestinationPageAnalytics,
} from './services';
import {
  AppData,
  AppDataProvider,
  useAppData,
  useAppDataDispatch,
  AgentMemoState,
  useAgentMemo,
  AgentMemoProvider,
  UserDataContextType,
  UserDataContext,
  useUserData,
  UserContextProvider,
  useFeatureToggleData,
  FeatureToggleContextProvider,
  FeatureToggleContextType,
  FeatureToggleContext,
} from './store';
import {
  isStringValid,
  isDateValid,
  isSameDate,
  isNumber,
  isAlphabetic,
  hasValidCharacters,
  isJsonValid,
  ternaryCondition,
  logicalAndOperator,
  logicalOrOperator,
  isUrl,
  isEmailValid,
  isNonEmptyString,
  validateArrivalDate,
  isPromoAdmin,
} from './validators';

export { getBrowserFtOverrides } from './store';

// IMPORTANT: Export client-utils (including cn) FIRST to avoid circular dependency issues
// The cn utility is used by atoms components, which are imported by components like AmendPageWrapper
// Client-safe utilities (previously only available via @whitbread-eos/utils/server)
// Most of these are safe to use in both client and server components and don't depend on next/headers
// Browser-only utilities (using document/window) are marked with inline comments
// NOTE: Functions like getCountriesList, etc. that use cookies at runtime should be imported
// from @whitbread-eos/utils/server.
export {
  cn,
  TranslationProvider,
  useTranslation,
  RolesRequired,
  formatIBAssetsUrl,
  sanitize,
  findError,
  getSavedCardType,
  ParseDateToYMD,
  parseRegistrationQuestions,
  formatHDPUrl,
  capitalizeFirstLetter,
  getLabelType,
  getStyling,
  resolveAndDownloadBlob,
  formatAccountNumber,
  mapSwitchState,
  getDefaultSwitchState,
  getVariant,
  normalizeAddress,
  parseAnswersObj,
  isPIBACardType,
  getInitials,
  getLocaleByPathname,
  getCountryLanguageByLocale,
  downloadFromS3PreSignedUrl, // Browser-only utility (uses document)
} from './client-utils';

export * from './types/cookie-policies';
export { mappingBookingStatus };
export { useAuth0Navigation, resolveAuthEntryPoint } from './hooks/useAuth0Navigation';
export { useAuth0AccessToken } from './hooks/useAuth0AccessToken';
export { useAuthToken, useLoggedOrCCUI } from './hooks/useAuthToken';
export { useAuth0User } from './hooks/useAuth0User';

export {
  formatRatePrice,
  formatCurrency,
  formatPrice,
  formatPriceWithDecimal,
  getPriceValueWithDecimal,
  formatDataTestId,
  formatAssetsUrl,
  formatInnerHTMLAssetUrls,
  formatDate,
  checkDateFormatter,
  formatNextLocaleLink,
  formatFindBookingToken,
  formatUrlTermsConditions,
  formatGuestTitleOptions,
  formatTextWithSpace,
  replaceWithEmptyString,
  uppercaseAndReplace,
  upperFirst,
  upperOnlyFirst,
  swapKeysAndValues,
  formatForMobile,
  superRoleFilter,
  langFilter,
  removeHtmlTags,
  createReservationDetails,
  matchSilentSubstitutions,
  getYearsAgoFromNow,
  getPathForLocale,
  renderSanitizedHtml,
};
export {
  // GLOBAL CONSTANTS
  GLOBALS,
  MAX_ROOMS_SEARCH_LIMIT,
  MANUAL_ADDRESS,
  REGISTER_BASKET_REF_COOKIE,
  SCROLL_AMOUNTS,
  MONTHS,
  BASKET_IDS_COOKIE,
  BASKET_COOKIE_EXPIRY_HOURS,
  PAGE_UNAVAILABLE_URL_EN,
  PAGE_UNAVAILABLE_URL_DE,
  TWO_MONTH_SEARCH,
  BUNDLE_CHOICE,
  BOOKING_REFERENCE_ID,
  PROD_ENVS,
  BUNDLE_CHOICE_OPTIONS,
  WB_SESSION_ID,
  PIB_MANUAL_LOGOUT_FLAG,
  EXTRAS_ROOM_TAB_CHANGED,
  ONE_YEAR_IN_DAYS,
} from './global-constants';

export {
  // AUTH GETTERS
  ID_TOKEN_COOKIE,
  ACCESS_TOKEN_COOKIE,
  EMAIL_COOKIE,
  OPERA_COMPANY_ID,
  CDH_COMPANY_ID,
  CDH_EMPLOYEE_ID,
  MAX_AGE,
  getAuthCookie,
  getAccessTokenCookie,
  getLoggedInUserInfo,
  decodeIdToken,
  logout,
  // CONFIRMATION GETTERS
  getRoomGroups,
  getRoomTotalprice,
  getRoomExtrasTotal,
  getMealPrice,
  getAdultMealDescription,
  getChildrenMealDescription,
  // FIND BOOKING TOKEN GETTERS
  getFindBookingToken,
  cleanupFindBookingToken,
  // COMMON GETTERS
  getNightsNumber,
  getNoOfDaysInYear,
  getDistanceUnitBasedOnLocale,
  getDistanceUnitBasedOnLocaleSb,
  getCardEnding,
  getCentrallyStoredCardBillingAddress,
  formatBillingAddress,
  formatRequiredString,
  getSecureTwoURL,
  getSortedCountries,
  getSortedCountriesByCurrentLang,
  getSortedCountriesByCurrentLangCcui,
  getMaxValueFromRoomStays,
  getMaxValueFromRoomStaysBC,
  getMaxValueFromHDPRoomTypes,
  getTotalPeople,
  getPlaceholderString,
  getRoomsPlaceholder,
  getSelectedDonationPackage,
  getIDVPassedStatus,
  getBookingDetailsForCard,
  getRoomDetailsForBartCard,
  getRoomTypeLabelsBySourceSystem,
  getTodayTomorrowDate,
  // GUEST DETAILS GETTERS
  getCityTaxMessages,
  getDefaultDataFromBooking,
  // HOTEL DETAILS GETTERS
  getAvailabilityParamsFromUrl,
  getStaticHotelInformationQueryDateDataFromUrl,
  getHotelAvailabilityQueryKey,
  isHotelOpeningSoon,
  isFaqValidForRender,
  getAccessibleRoomData,
  isAccessibleRoomType,
  getPIBrandText,
  // LABELS GETTERS
  transformLabels,
  getI18nLabels,
  getServerSideCustomLocale,
  displayStorageSubstitutionLabels,
  // PAYMENT GETTERS
  getBookingSummaryData,
  getIsBillingAddressDisplayed,
  getIsDonationsDisplayed,
  getIsDonationInfoBoxDisplayed,
  setBusinessAllowancesSections,
  getIsBBCardDetailsDisplayed,
  getBillingAddress,
  getPaymentError,
  getA2CBusinessAllowances,
  // SEARCH EMPLOYEES GETTERS
  getListOfEmployees,
  // SEARCH RESULTS GETTERS
  getPlace,
  getDefaultRooms,
  getSearchResultsPageSize,
  //BOOKINGS PAGE GETTERS
  getPromoId,
  getNewSearchResultsPI,
  getNewSearchResultsBB,
  getNewSearchResultsCCUI,
  setPromoInfoState,
  getSessionStorageValuesForBookings,
  getAvailableRoomTypes,
  getRoomClassByRoomClassCode,
  getRateClassification,
  getRoomRatesThatMatchRoomClassifications,
  getAvailabilityRoomClassIndexes,
  getAllRoomTypesFromRates,
  getRoomTypesFromQuery,
  getSelectedPMSRoomTypesAndSpecialRequests,
  getTwinRoomSelectionPrices,
  getLocalStorageMock,
  getAmendSectionTranslations,
  getTitleDropdownValues,
  //EXTRAS SECTION GETTERS
  extrasNamingCheck,
  getExtrasPackagePrice,
  filterWiFiForPlusRooms,
  formatGuests,
  formatAccompanyingGuest,
  getCanonicalLocale,
  getOneTrustConfigByLocale,
  isOneTrustCookieConsentActive,
  getRoomClassByCodeAndType,
  getBathRoomSelectedPMSRoomTypesAndSpecialRequests,
  getAccessibleRoomSelectedPMSRoomTypesAndSpecialRequests,
  getSelectedRoomClassCode,
  getRoomClassTextForGAllery,
  filterRoomsByRoomClass,
  readPromotionsInformation,
  shouldDisplayPromoBanner,
  getBrandFromSnowDropSuggestions,
  type PromotionsInformation,
  type PromoActionsType,
  hasMatchingPromotionCode,
  getActivePromotionCode,
  getUserAndRoles,
  extractMultiHotelAvailabilities,
  getRoomRatesWithRateInformation,
  mapBookingInformationForReuseBooking,
  checkIsBookingForSomeoneElse,
  getBrandForUnleashContext,
  extractPromoBoxData,
};

export {
  // BASE64 HELPERS
  encodeToBase64,
  decodeFromBase64,
  getCookie,
  setCookie,
  setCookieWithDefaultDomain,
  COOKIE_MODAL_CLOSED_EVENT,
  DYNATRACE_CONSENT_DISABLED,
  DYNATRACE_CONSENT_ENABLED,
  DYNATRACE_CONSENT_COOKIE_NAME,
  DYNATRACE_SYNC_COOKIE,
  hasCustomDynatraceConsent,
  hasOneTrustDynatraceConsent,
  getDynatraceConsentPaths,
  ONETRUST_GROUPS_UPDATED_EVENT,
  ONETRUST_DYNATRACE_CONSENT_GROUP,
  syncDynatraceConsent,
  syncDynatraceConsentFromCookie,
  syncDynatraceConsentFromOneTrust,
  setBookingCookie,
  deleteCookie,
  deleteCookieWithDefaultDomain,
  // DROPDOWN HELPERS
  createOptionsAdultsChildrenDropdown,
  getAdultsChildrenOptions,
  getRoomTypeOptions,
  getMappedRooms,
  // HANDLE REF HEIGHT CHANGE HELPER
  handleRefHeightChange,
  // WAIT FOR ELEMENT HELPER
  waitForElement,
  getUnleashToggles,
  akamaiImageLoader,
  isIVMEnabled,
  handleManageBookingParamsCCUI,
  displayMethodType,
  displayPaymentHelpText,
  isApplePayConfigured,
  isGooglePayConfigured,
  getDonationForBooking,
  getTotalCost,
  sortImagesByOrder,
  hashString,
  isObjectNotEmpty,
  applyDefaultPaymentRestrictions,
  isSecureBookingPage,
  type secureBookingType,
  type BookingDataType,
  getBookingConfirmationMessage,
  shouldDisplaySecureBooking,
  isValidSecureBooking,
  getValidOrTodayDate,
  useSoftBundles,
  getBookingFlowId,
  getInputTypographyOverride,
  getTextStyleTypographyOverride,
  buildPaymentParams,
  buildCardFromPaymentMethod,
  updateSelectedPaymentOption,
  getBookingForSomeoneElse,
  type BuildPaymentParamsInput,
  type GetBookingForSomeoneElseInput,
};

export {
  useBookingConfimationData,
  useBookingSpinner,
  useCookieForABTesting,
  useCompanyDetails,
  useCustomLocale,
  useCustomLocaleAppRouter,
  useDebounce,
  useFeatureToggle,
  useHotelAvailabilityBB,
  useHotelAvailabilityCCUI,
  useHotelAvailability,
  useHotelRatesInformationBB,
  useHotelRatesInformationCCUI,
  useIPageSubmission,
  useLocalStorage,
  useSessionStorage,
  useOrientation,
  useSetOrientation,
  usePackages,
  graphQLRequest,
  useQueryRequest,
  useMutationRequest,
  axiosRequest,
  useRestQueryRequest,
  useRestMutationRequest,
  type ProxyOptions,
  useScreenSize,
  useSetScreenSize,
  useStaticHotelInformation,
  useUserDetails,
  usePollBasketStatus,
  useFeatureSwitch,
  useIsExternalSearch,
  useScrolledPast,
  useElementVisited,
  useHotelBrands,
  useSilentRoomsMatch,
  usePaymentPaypal,
  useGetCountryLanguage,
  useUpdateSearchParams,
  useScrollVisibility,
  usePaymentMethod,
  usePaymentData,
  usePaymentAnalytics,
  useElementDimensions,
  useForDiscountedRateMicroSite,
  useForDiscountedRateFlag,
  useHotelRatesInformationDiscountRate,
  useHotelAvailabilityDiscountRate,
  useDiscountRateInfoHotelAvailability,
  getRatePlanCode,
  getCorporateDiscountRatePlanCode,
  useUpdateRateName,
  useGetDiscountRateComapnyId,
  useGetDiscountRateReservationData,
  usePromotionsNotification,
  useCookieWatcher,
  useInnBusinessLogin,
  useOutsideClick,
  useHorizontalScroll,
  usePromoTranslation,
  useMobileControlsDisplay,
  useAmendCookieValidation,
  useSemanticTypography,
};

export {
  // ANCILLARIES SELECTORS
  enhanceMeal,
  enhancePrivacyPolicyMoreInfoItem,
  sortMealsByOrderOrName,
  adultsMealsSelector,
  freeBreakfastMaxAllowance,
  freeBreakfastMaxSelectedAllowance,
  childrenMealsSelector,
  menusSelector,
  securityNoticeMoreInfoDataSelector,
  enhanceSelectedMeals,
  selectedMealsPerRoomSelector,
  roomInformationSelector,
  numberOfSelectionsPerRoomSelector,
  mealsMapperSelector,
  autocompleteMeals,
  calculateTotalCostRoomSelection,
  formatImportantNotes,
  getImportantMessages,
  getUniqueRoomProperties,
  checkIfExistPreselection,
  shouldDisplayAutocompleteNotification,
  transformBartIdToOperaId,
  isCityTaxAvailable,
  // BUSINESS BOOKER SELECTORS
  isGuestDetailsPageAllowed,
  isDataCollectionMsgAndFormVisible,
  // COMMON SELECTORS
  hotelInformationSelector,
  enhanceCheckoutStepList,
  bookingGuestCount,
  // GUEST DETAILS SELECTORS
  generateSuggestionList,
  boldMatchCharacters,
  isTheSameGuest,
  addReservationNumber,
  sortMealsByReservationId,
  isArrivalDateWithinSetHours,
  updateSilentSubstLocalStorage,
  filterPackagesByAncillariesCloseOut,
  getCurrentReservationStorageData,
  extrasPackagesMapperSelector,
  addOrRemoveExtrasRoom,
  roomPackageSelection,
  addOrRemoveAllRoomsExtras,
};

export {
  updateAmendPageAnalytics,
  analytics,
  timeTrackerSeconds,
  restaurantFormAnalytics,
  analyticsConfirmation,
  extrasPackagesAnalyticsMap,
  AnalyticsProvider,
  AnalyticsProviderCCUI,
  initConfirmationAnalytics,
  updateConfirmationAnalytics,
  analyticsConfirmationPageName,
  updateDashboardAnalytics,
  updateHotelDisplayPageAnalytics,
  updateSearchResultsAnalytics,
  setPageAnalytics,
  formatAnalyticsFunnelStep,
  setAnalyticsUser,
  analyticsTrackings,
  updateAncillariesAnalytics,
  updateConfirmationPageAnalytics,
  updateDestinationPageAnalytics,
};

export {
  AppDataProvider,
  useAppData,
  useAppDataDispatch,
  useAgentMemo,
  AgentMemoProvider,
  UserDataContext,
  useUserData,
  UserContextProvider,
  useFeatureToggleData,
  FeatureToggleContextProvider,
  FeatureToggleContext,
};

export type { AppData, UserDataContextType, AgentMemoState, FeatureToggleContextType };

export {
  isStringValid,
  isDateValid,
  isSameDate,
  isNumber,
  isAlphabetic,
  hasValidCharacters,
  isJsonValid,
  ternaryCondition,
  logicalAndOperator,
  logicalOrOperator,
  isEmailValid,
  isUrl,
  isNonEmptyString,
  validateArrivalDate,
  getObjectFormatNumber,
  parsePhoneNumber,
  isPromoAdmin,
};

export {
  getLogger,
  instrument,
  instrumentQueryClient,
  tracingCookie,
  getDefaultSessionTracing,
  getClientDefaultSessionTracing,
  logger,
  clientLogger,
};
export { QueriesLogger };
export { getPaypalOptionsParams, getPaypalDeviceData };
export { getGQLClient };
export {
  isIOSDevice,
  decryptCryptString,
  formatReservationNumberInQuery,
  tabbingAccessibility,
  containsPlaceLD,
  getPriceRange,
  getRestaurantMessageDisplay,
} from './helpers';
export {
  // BASKET IDS COOKIE HELPERS
  addBasketIdToCookie,
  getBasketIdsFromCookie,
  getBasketIdsJsonFromCookie,
  validateBasketIdInCookie,
  validateBasketIdFromServer,
} from './helpers/basketIdsCookie';

// Mock data variables
export { bknReservationsMock, MOCK_SOFT_BUNDLES } from './mockData';
export {
  mockPackagesData,
  mockBookingConfirmationAmend,
  mockStayRules,
  mockEmployeeStayRules,
  mockRoomOccupancyLimitations,
  mockedGetStaticContent,
} from './mockData/amend';
export {
  getBookingInformationData,
  getBookingInformationDataForGermanHotel,
  singleBookingInformationData,
  getHotelInformation,
  gbHotelInfo,
  getCountriesData,
  getPostCodeAddresesData,
  getPostCodeAddresesInfoData,
  getRoomSelectionData,
  defaultValuesWithGuests,
  defaultValues,
} from './mockData/guestDetails';

export { roomDefaultValueIfError, isInnBusinessApp, hasSameRoomTypeCodes };

export {
  type RestaurantAnalyticsData,
  // RESTAURANTS GETTERS
  formatDateToString,
  fetchFormattedDateValues,
  // RESTAURANTS HELPERS - AEM CONTENT
  dropdrownManipulatorFn,
  replaceInputPlaceholder,
  // RESTAURANTS HELPERS - COMMON PARAMS
  getCommonParams,
  // RESTAURANTS HELPERS - GTM ID
  getRestaurantBrandGTMId,
  // RESTAURANTS HOOKS
  restaurantGraphQLRequest,
  restaurantUseQueryRequest,
  restaurantUseMutationRequest,
  // RESTAURANTS GQL CLIENT
  restaurantGetGQLClient,
};

// Export restaurants functions with Restaurants suffix as well
export {
  graphQLRequestRestaurants,
  useQueryRequestRestaurants,
  useMutationRequestRestaurants,
} from './hooks/use-request';

export { getHotelBrandFromSearchResults } from './getters';

export { getHotelLabel, labelsConstants } from './services';

// Client-callable mutations (uses dynamic imports for next/headers, safe for client)
export { downloadBookingInvoice } from './server/mutations/mutations';
export type { DownloadBookingInvoiceRequest } from './server/mutations/mutations';
