openapi: 3.1.0
info:
  title: Address Lookup API Documentation
  version: 1.0.0
servers:
- description: Generated server url
  url: http://localhost:9111
tags:
- description: Monitor and interact
  externalDocs:
    description: Spring Boot Actuator Web API Documentation
    url: https://docs.spring.io/spring-boot/docs/current/actuator-api/html/
  name: Actuator
paths:
  /v1/addresses:
    get:
      operationId: getAddressesByPostcode
      parameters:
      - example: SG89ES
        in: query
        name: searchTerm
        required: true
        schema:
          type: string
      - example: uk
        in: query
        name: countryCode
        required: false
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddressSearchResponseDto"
          description: Address lookup successfully retrieved
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Missing or invalid request
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Resource Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal server error
      tags:
      - address-lookup-controller
  /v1/addresses/actuator:
    get:
      operationId: links
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
          description: OK
      summary: Actuator root web endpoint
      tags:
      - Actuator
  /v1/addresses/actuator/health:
    get:
      operationId: health
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
          description: OK
      summary: Actuator web endpoint 'health'
      tags:
      - Actuator
  /v1/addresses/actuator/info:
    get:
      operationId: info
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
          description: OK
      summary: Actuator web endpoint 'info'
      tags:
      - Actuator
  /v1/addresses/actuator/metrics:
    get:
      operationId: listNames
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
          description: OK
      summary: Actuator web endpoint 'metrics'
      tags:
      - Actuator
  /v1/addresses/actuator/metrics/{requiredMetricName}:
    get:
      operationId: metric
      parameters:
      - in: path
        name: requiredMetricName
        required: true
        schema:
          type: string
      - in: query
        name: tag
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
          description: OK
        "404":
          description: Not Found
      summary: Actuator web endpoint 'metrics-requiredMetricName'
      tags:
      - Actuator
  /v1/addresses/actuator/prometheus:
    get:
      operationId: scrape
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - CONTENT_TYPE_004
          - CONTENT_TYPE_OPENMETRICS_100
          - CONTENT_TYPE_PROTOBUF
      - in: query
        name: includedNames
        schema:
          type: string
      responses:
        "200":
          content:
            application/openmetrics-text;version=1.0.0;charset=utf-8:
              schema:
                type: object
            application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited:
              schema:
                type: object
            text/plain;version=0.0.4;charset=utf-8:
              schema:
                type: object
          description: OK
      summary: Actuator web endpoint 'prometheus'
      tags:
      - Actuator
  /v1/addresses/{monikerId}:
    get:
      operationId: getFormattedAddress
      parameters:
      - in: path
        name: monikerId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddressFormatResponseDto"
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Missing or invalid request
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Resource Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal server error
      tags:
      - address-lookup-controller
components:
  schemas:
    AddressFormatResponseDto:
      type: object
      properties:
        addressLine1:
          type: string
        addressLine2:
          type: string
        addressLine3:
          type: string
        addressLine4:
          type: string
        addressLine5:
          type: string
        companyName:
          type: string
        country:
          type: string
        label:
          type: string
        postalCode:
          type: string
    AddressSearchResponseDto:
      type: object
      properties:
        addressText:
          type: string
        id:
          type: string
    ErrorResponse:
      type: object
      properties:
        debugMessage:
          type: string
        details:
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"
        errCode:
          type: integer
          format: int32
        globalErrTextTemplate:
          type: string
    Link:
      type: object
      properties:
        href:
          type: string
        templated:
          type: boolean
    ValidationError:
      type: object
      properties:
        elementId:
          type: string
        errTextTemplate:
          type: string
