@startuml
entity "Reservation Entity Service" as A
participant HotelReservationController as Controller
participant HotelReservationInPort as InboundPort
participant BasketOutboundPort as BasketOutboundPort
participant BasketWebClient as BasketWebclient
participant HotelReservationOutboundPort as HotelReservationOutboundPort
participant HotelReservationWebClient as HotelReservationWebclient
entity "Basket Service" as BSK
entity "OHIP Adapter Service" as OHIPAdapter

A -> Controller: POST /v1/reservations/{basketReference}/guests
Controller -> InboundPort: createReservationGuest
InboundPort -> BasketOutboundPort: getBasketByReference
BasketOutboundPort -> BasketWebclient: getBasketByReference
BasketWebclient -> BSK: GET /v1/baskets/{basket-reference}
BasketWebclient <- BSK: Basket with reservationIds, hotelId
BasketOutboundPort <- BasketWebclient: Basket with reservationIds, hotelId
InboundPort <- BasketOutboundPort: Basket with reservationIds, hotelId
InboundPort -> HotelReservationOutboundPort: createReservationGuest
HotelReservationOutboundPort -> HotelReservationWebclient: createReservationGuest
HotelReservationWebclient -> OHIPAdapter: POST v1/reservations/guests

HotelReservationWebclient <- OHIPAdapter: ReservationGuestResponse
HotelReservationOutboundPort <- HotelReservationWebclient: ReservationGuestResponse
InboundPort <- HotelReservationOutboundPort: ReservationGuestResponse
Controller <- InboundPort: ReservationGuestResponse
A <- Controller: ReservationGuestResponseDto
@enduml