@startuml
entity "Reservation Entity Service" as A
participant HotelReservationController as Controller
participant HotelReservationInPort as InboundPort
participant BasketOutboundPort as BasketOutboundPort
participant BasketWebClient as BasketWebclient
participant HotelReservationOutboundPort as HotelReservationOutboundPort
participant HotelReservationWebClient as HotelReservationWebclient
entity "Basket Service" as BSK
entity "OHIP Adapter Service" as OHIPAdapter

A -> Controller: PUT/v1/reservations/link-leisure-customer
Controller -> InboundPort: linkReservationToLeisureCustomerRequestDto
InboundPort -> BasketOutboundPort: getBasketByReference
BasketOutboundPort -> BasketWebclient: getBasketByReference
BasketWebclient -> BSK: GET /v1/baskets/{basket-reference}
BasketWebclient <- BSK: Basket with reservationIds, hotelId
BasketOutboundPort <- BasketWebclient: Basket with reservationIds, hotelId
InboundPort <- BasketOutboundPort: Basket with reservationIds, hotelId
InboundPort -> HotelReservationOutboundPort: linkReservationToLeisureCustomerRequestDto
HotelReservationOutboundPort -> HotelReservationWebclient: sendLinkReservationToLeisureCustomer
HotelReservationWebclient -> OHIPAdapter: PUT /v1/reservations/link-leisure-customer

HotelReservationWebclient <- OHIPAdapter: OK 200
HotelReservationOutboundPort <- HotelReservationWebclient: OK 200
InboundPort <- HotelReservationOutboundPort: OK 200
Controller <- InboundPort: OK 200
A <- Controller: OK 200
@enduml