@startuml
!pragma teoz true


entity "AppSync" as A
entity "Reservation Entity Service" as R
entity "BASKET" as BSK
entity "OHIP Adapter Service" as OHIP
entity "OHIP Adapter Service" as OAD
entity "OPERA" as OPERA



A -> R: graphql save reservations


R -> BSK: GET /bsk/v1/baskets/{basketReference}
R <- BSK: DTO with reservationIds, hotelId
R -> OHIP: PUT /v1/reservation/ancillaries
OHIP -> OAD: PUT /v1/reservation/ancillaries
OAD -> OPERA: PUT /rsv/v1/hotels/{{HotelId}}/reservations/{{ReservationId}}
OPERA -> OAD: OK 200
OAD -> OHIP:  OK 200
OHIP -> R: OK 200

R -> A: basketReference

@enduml