openapi: 3.0.1
info:
  description: <p>TBU</p>
  title: Sample API Documentation
  version: 3.0.0
servers:
- description: Generated server url
  url: http://localhost:9099
tags:
- description: Monitor and interact
  externalDocs:
    description: Spring Boot Actuator Web API Documentation
    url: https://docs.spring.io/spring-boot/docs/current/actuator-api/html/
  name: Actuator
paths:
  /v1/sample/actuator:
    get:
      operationId: links
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: '#/components/schemas/Link'
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: '#/components/schemas/Link'
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: '#/components/schemas/Link'
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "405":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Method Not Allowed
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: Actuator root web endpoint
      tags:
      - Actuator
  /v1/sample/actuator/health:
    get:
      operationId: health
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "405":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Method Not Allowed
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: Actuator web endpoint 'health'
      tags:
      - Actuator
  /v1/sample/actuator/health/**:
    get:
      operationId: health-path
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "405":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Method Not Allowed
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: Actuator web endpoint 'health-path'
      tags:
      - Actuator
  /v1/sample/actuator/info:
    get:
      operationId: info
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "405":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Method Not Allowed
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: Actuator web endpoint 'info'
      tags:
      - Actuator
  /v1/sample/actuator/prometheus:
    get:
      operationId: prometheus
      responses:
        "200":
          content:
            application/openmetrics-text;version=1.0.0;charset=utf-8:
              schema:
                type: object
            text/plain;version=0.0.4;charset=utf-8:
              schema:
                type: object
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "405":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Method Not Allowed
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: Actuator web endpoint 'prometheus'
      tags:
      - Actuator
  /v1/sample/hotels/availabilities:
    get:
      operationId: getAvailableHotels
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SampleHotelSearchDto'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 'Error Occurred '
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Resource Not Found
        "405":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Method Not Allowed
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: Retrieves Sample Hotels Availabilities Result
      tags:
      - sample-availability-controller
  /v1/sample/hotels/availabilities/custom:
    post:
      operationId: getResponse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SampleHotelSearchRequestDto'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SampleHotelSearchDto'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 'Error Occurred '
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Resource Not Found
        "405":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Method Not Allowed
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: Retrieves Sample Hotels Availabilities Custom Result
      tags:
      - sample-availability-controller
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        debugMessage:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
        errCode:
          type: integer
          format: int32
        globalErrTextTemplate:
          type: string
    Link:
      type: object
      properties:
        href:
          type: string
        templated:
          type: boolean
    SampleHotelSearchDto:
      type: object
      properties:
        responseData:
          type: array
          items:
            type: object
    SampleHotelSearchRequestDto:
      type: object
      properties:
        fromDate:
          type: string
        hotelName:
          type: string
      required:
      - fromDate
      - hotelName
    ValidationError:
      type: object
      properties:
        elementId:
          type: string
        errTextTemplate:
          type: string
