//
//  NewsletterModule.swift
//  PremierInn
//
//  Created Freddie Parks on 28/03/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit

enum NewsletterModule {
    static func build(with emailAddress: String) -> UIViewController {
        let controller = NewsletterView()

        controller.eventHandler = {
            let presenter = NewsletterPresenter()

            let router = NewsletterRouter()
            router.view = controller

            let interactor = NewsletterInteractor(with: emailAddress)

            presenter.view = controller
            presenter.interactor = interactor
            presenter.router = router

            return presenter
        }()

        return controller
    }
}

protocol NewsletterViewModel {
    var navigationTitle: String { get }
    var heading: String { get }
    var message: String { get }
    var emailAddress: String { get }
}

protocol NewsletterViewProtocol: AnyObject {
    func update(with viewModel: NewsletterViewModel)
}

protocol NewsletterViewEventHandler {
    func viewIsReady()
}

protocol NewsletterInteractorProtocol {
    var viewModel: NewsletterViewModel? { get }
}

protocol NewsletterRouterProtocol {
}
