//
//  NewsletterPresenter.swift
//  PremierInn
//
//
//  Created Freddie Parks on 28/03/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import Foundation

class NewsletterPresenter {
    weak var view: NewsletterViewProtocol?

    var interactor: NewsletterInteractorProtocol?
    var router: NewsletterRouterProtocol?
}

extension NewsletterPresenter: NewsletterViewEventHandler {
    func viewIsReady() {
        guard let viewModel = interactor?.viewModel else { return }
        view?.update(with: viewModel)
    }
}
