//
//  NewsletterRouter.swift
//  PremierInn
//
//
//  Created Freddie Parks on 28/03/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit

class NewsletterRouter {
    var view: UIViewController?
}

extension NewsletterRouter: NewsletterRouterProtocol {
}
