//
//  NewsletterView.swift
//  PremierInn
//
//
//  Created Freddie Parks on 28/03/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit

class NewsletterView: UIViewController {
    var eventHandler: NewsletterViewEventHandler?

    @IBOutlet weak var heading: UILabel! {
        didSet {
            heading.font = .Heading3_Semibold()
            heading.textColor = .TintD1
        }
    }
    @IBOutlet weak var message: UILabel! {
        didSet {
            message.font = .Body()
            message.textColor = .TintD1
        }
    }
    @IBOutlet weak var email: UILabel! {
        didSet {
            email.font = .Heading4_Semibold()
            email.textColor = .Tint1
            ContentsquareConfig.mask(view: email)
        }
    }

    init() {
        super.init(nibName: "NewsletterView", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func viewDidLoad() {
        super.viewDidLoad()

        eventHandler?.viewIsReady()
    }
}

extension NewsletterView: NewsletterViewProtocol {
    func update(with viewModel: NewsletterViewModel) {
        navigationItem.title = viewModel.navigationTitle

        heading.text = viewModel.heading
        message.text = viewModel.message
        email.text = viewModel.emailAddress
    }
}
