//
//  NewsletterInteractor.swift
//  PremierInn
//
//
//  Created Freddie Parks on 28/03/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import Foundation

class NewsletterInteractor {
    private var emailAddress: String?

    init(with emailAddress: String) {
        self.emailAddress = emailAddress
    }
}

extension NewsletterInteractor: NewsletterInteractorProtocol {
    private struct ViewModel: NewsletterViewModel {
        let navigationTitle: String
        let heading: String
        let message: String
        let emailAddress: String
    }

    var viewModel: NewsletterViewModel? {
        guard let emailAddress = emailAddress else { return nil }

        return ViewModel(
            navigationTitle: PILocalizedString("Newsletter", comment: ""),
            heading: PILocalizedString("newsletterUpdateTitle", comment: ""),
            message: PILocalizedString("newsletterUpdateMessage", comment: ""),
            emailAddress: emailAddress
        )
    }
}
