/* Recommendation: Use UPPERCASE for page names. This is added as an experimental way to have everything w.r.t. Pages, associated Feature Flags, etc at one place. This needs to be taken care of by everyone from the next time/when you refactor
 */
import {
  FT_DYNATRACE_RUM_COOKIE_CONSENT,
  FT_ONE_TRUST_COOKIE_CONSENT,
  FT_PI_ADDITIONAL_INFORMATION,
  FT_PI_AMEND_GUEST_ADDRESS,
  FT_PI_GDP_BILLING_ADDRESS,
  FT_PI_PRE_CHECK_IN,
  FT_PI_RECAPTCHA_REGISTER,
  FT_PI_GROUP_BOOKING_FORM,
  FT_PI_BB_CCUI_TRIP_ADVISOR,
  FT_PI_WEB_PUSH_NOTIFICATIONS,
  FT_PI_HREFLANG_ATTRIBUTE,
  FT_PI_BREAKFAST_PROMO_CODE,
  FT_PI_FREE_FNB_AND_EXTRAS,
  FT_PI_AMEND_DELETE_REG_CARD,
  FT_PI_META_CLASS_RATE_SEARCH,
  FT_PI_CP_CREATE_ACCOUNT,
  FT_PI_GDP_PAGE_DESIGN_CHANGE,
  FT_PI_GROUP_WEB_SSR_REST_CALL,
  FT_PI_BB_ACCOUNT_SERV_TO_SERV,
  FT_PI_BB_CCUI_COMPANY_NAME_SPECIAL_CHARACTERS,
  FT_PI_ACCOMPANYING_GUEST_DETAILS,
  FT_PI_DISCOUNT_RATE,
  FT_PI_AEM_PAGE_CSR_ONLY,
  FT_PI_AEM_PAGE_NO_SANITIZE,
  FT_PI_NEW_DLP_FILTERS,
  FT_PI_BB_CCUI_NONSILENT_SUBSTITUTION_PER_ROOMCLASS,
  FT_PI_BB_CCUI_MAXROOMS_AMEND,
  FT_PI_ENABLE_PAYPAL,
  FT_PI_ENABLE_PAYMENT_REDESIGN,
  FT_PI_BB_CCUI_DISABLE_PAYMENTS,
  FT_PI_CCUI_BB_PREM_PLUS_ACCESSIBLE,
  FT_PI_PROMO_CODE_LANDING_PAGE,
  FT_PI_PROMO_CODE_SITE_WIDE,
  FT_PI_BB_CCUI_ROOMS_DISCLAIMER,
  FT_PI_SORT_ORDER_DROPDOWN,
  FT_PI_BB_CCUI_CHOOSE_ROOM_TYPE,
  FT_PI_BB_CCUI_BARRIER_FREE_LABEL,
  FT_PI_PRICE_PER_NIGHT,
  FT_PI_BB_NON_GUARANTEED_REMINDER,
  FT_PI_ROOM_UPGRADE_POPUP,
  FT_PI_KILL_SWITCH_CHAT_BOX,
  FT_PI_SHOW_CHAT_BOT_ALL_PAGES,
  FT_PI_SUMMER_SALE_PROMO_BANNER,
  FT_PI_BB_CANCELLATION_POLICY,
  FT_PI_SIGNUP_IN_HEADER,
  FT_PI_BB_CCUI_COUNTRY_SELECTOR_FILTERABLE,
  FT_PI_BB_CCUI_SHOW_MEALS_FREE,
  FT_PI_CCUI_CONSOLIDATE_MOBILE_LANDLINE,
  FT_PI_BOOKING_STEPS_WITH_TITLE,
  FT_PI_BB_CCUI_HDP_IMAGE_GALLERY_REDESIGN,
  FT_PI_BB_CCUI_SRP_MULTIPLE_IMAGES,
  FT_PI_PRICE_FINDER_SEO_NOINDEX,
  FT_PI_BB_BOOKING_HISTORY_REDESIGN,
  FT_PI_SHOW_PROMOTION_BOX,
  FT_PI_BASKET_IDS_COOKIE_VALIDATION,
  FT_PI_NO_ROOM_TYPE_SEARCH,
  FT_PI_PIB_CCUI_SHOW_LOWEST_PRICE_MONTH_TAB,
  FT_PI_PIB_CCUI_SHOW_FILTER_ROOM_TYPES,
  FT_PI_TWO_MONTH_SEARCH,
  FT_PI_BOOKING_STATUS_IN_BIC_HEADER,
  FT_PI_DISPLAY_SOFT_BUNDLES,
  FT_PI_PIB_SWAP_PAYMENT_OPTIONS,
  FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN,
  FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN_ANCILLARIES_GDP_PAYMENT,
  FT_PI_PIB_CCUI_CITY_TAX_AMEND,
  FT_PI_PIB_PAYMENT_BACK_TO_OPTIONS_LINK,
  FT_PI_ADD_TO_WALLET,
  FT_PI_AUTH0_LOGIN,
  FT_PI_PIB_CCUI_ENABLE_HUB_HOTELS_POA,
  FT_PI_PIB_BIC_DOWNLOAD_INVOICE,
  FT_PI_BB_CONTROLS_MOBILE_DISPLAY,
  FT_PIB_LOGIN_REDIRECT,
  FT_PI_BB_SHOW_GOOGLE_STATIC_MAP,
  FT_PI_ANALYTICS_DEBOUNCE,
  FT_PI_ROOM_DETAILS_DRAWER,
  FT_SRP_DYNAMIC_FILTERS,
  FT_PI_SRP_SPLIT_MAP_VIEW,
  FT_PI_HDP_URGENCY_BANNER,
  FT_PI_REMOVE_PII_DATA_FROM_LOCAL_STORAGE,
  FT_PI_CCUI_BB_PROMOTION_BOX_CODE_COOKIE,
  FT_SEMANTIC_TYPOGRAPHY_TOKENIZATION,
  FT_PI_BB_CCUI_PROMOTIONS_IN_HOTELAVAILABILITY,
  FT_PI_DATATRANS_INTEGRATION,
  FT_PI_REDIS_RQ_CACHE,
  FT_MOBILE_PREREGISTERED_REPURPOSE,
} from '@whitbread-eos/api';

export const PAYMENT_NAVIGATION_SOURCE_QUERY_PARAM = 'from';
export const PAYMENT_NAVIGATION_SOURCE_GUEST_DETAILS = 'guest-details';

//  A collection of feature toggles that are common to both HDP and SRP.
const commonFeatureToggles = {
  [FT_PI_BB_CCUI_TRIP_ADVISOR]: false,
  [FT_PI_GROUP_BOOKING_FORM]: false,
  [FT_PI_WEB_PUSH_NOTIFICATIONS]: false,
  [FT_PI_HREFLANG_ATTRIBUTE]: false,
  [FT_PI_BREAKFAST_PROMO_CODE]: false,
  [FT_PI_META_CLASS_RATE_SEARCH]: false,
  [FT_PI_DISCOUNT_RATE]: false,
  [FT_PI_NEW_DLP_FILTERS]: false,
  [FT_PI_BB_CCUI_NONSILENT_SUBSTITUTION_PER_ROOMCLASS]: false,
  [FT_PI_CCUI_BB_PREM_PLUS_ACCESSIBLE]: false,
  [FT_PI_PROMO_CODE_LANDING_PAGE]: false,
  [FT_PI_PROMO_CODE_SITE_WIDE]: false,
  [FT_PI_BB_CCUI_ROOMS_DISCLAIMER]: false,
  [FT_PI_SORT_ORDER_DROPDOWN]: false,
  [FT_PI_BB_CCUI_CHOOSE_ROOM_TYPE]: false,
  [FT_PI_BB_CCUI_BARRIER_FREE_LABEL]: false,
  [FT_PI_PRICE_PER_NIGHT]: false,
  [FT_PI_ROOM_UPGRADE_POPUP]: false,
  [FT_PI_KILL_SWITCH_CHAT_BOX]: false,
  [FT_PI_SHOW_CHAT_BOT_ALL_PAGES]: false,
  [FT_PI_SUMMER_SALE_PROMO_BANNER]: false,
  [FT_PI_SIGNUP_IN_HEADER]: false,
  [FT_PI_BB_CCUI_HDP_IMAGE_GALLERY_REDESIGN]: false,
  [FT_PI_CCUI_BB_PROMOTION_BOX_CODE_COOKIE]: false,
  [FT_PI_NO_ROOM_TYPE_SEARCH]: false,
  [FT_PI_TWO_MONTH_SEARCH]: false,
  [FT_PI_DISPLAY_SOFT_BUNDLES]: false,
  [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN]: false,
  [FT_PI_AUTH0_LOGIN]: false,
  [FT_PIB_LOGIN_REDIRECT]: false,
  [FT_PI_BB_CCUI_PROMOTIONS_IN_HOTELAVAILABILITY]: false,
};

const globalFeatureToggles = {
  [FT_DYNATRACE_RUM_COOKIE_CONSENT]: false,
  [FT_ONE_TRUST_COOKIE_CONSENT]: false,
  [FT_PI_ANALYTICS_DEBOUNCE]: false,
  [FT_PI_REDIS_RQ_CACHE]: false,
  [FT_SEMANTIC_TYPOGRAPHY_TOKENIZATION]: false,
};

export const PAGE = {
  AMEND: {
    DETAILS: {
      featureToogles: {
        appPage: 'pi:amend:details',
        flagsWithFallback: {
          ...globalFeatureToggles,
          [FT_PI_AMEND_GUEST_ADDRESS]: false,
          [FT_PI_AMEND_DELETE_REG_CARD]: false,
          [FT_PI_DISCOUNT_RATE]: false,
          [FT_PI_BB_CCUI_MAXROOMS_AMEND]: false,
          [FT_PI_BB_NON_GUARANTEED_REMINDER]: false,
          [FT_PI_KILL_SWITCH_CHAT_BOX]: false,
          [FT_PI_SHOW_CHAT_BOT_ALL_PAGES]: false,
          [FT_PI_BB_CCUI_SHOW_MEALS_FREE]: false,
          [FT_PI_SIGNUP_IN_HEADER]: false,
          [FT_PI_PROMO_CODE_LANDING_PAGE]: false,
          [FT_PI_PROMO_CODE_SITE_WIDE]: false,
          [FT_PI_AUTH0_LOGIN]: false,
          [FT_PI_FREE_FNB_AND_EXTRAS]: false,
          [FT_PI_BB_CCUI_PROMOTIONS_IN_HOTELAVAILABILITY]: false,
          [FT_MOBILE_PREREGISTERED_REPURPOSE]: false,
          [FT_PI_PIB_CCUI_CITY_TAX_AMEND]: false,
        },
      },
    },
  },
  AEM_PAGE: {
    featureToogles: {
      appPage: 'PI | AEM | AEM Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_AEM_PAGE_CSR_ONLY]: false,
        [FT_PI_AEM_PAGE_NO_SANITIZE]: false,
        [FT_PI_KILL_SWITCH_CHAT_BOX]: false,
        [FT_PI_SHOW_CHAT_BOT_ALL_PAGES]: false,
        [FT_PI_SIGNUP_IN_HEADER]: false,
        [FT_PI_AUTH0_LOGIN]: false,
      },
    },
  },
  GUEST_DETAILS: {
    featureToogles: {
      appPage: 'PI | GDP | Guest Details Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_GDP_BILLING_ADDRESS]: false,
        [FT_PI_ADDITIONAL_INFORMATION]: false,
        [FT_PI_GDP_PAGE_DESIGN_CHANGE]: false,
        [FT_PI_BB_CCUI_COMPANY_NAME_SPECIAL_CHARACTERS]: false,
        [FT_PI_ACCOMPANYING_GUEST_DETAILS]: false,
        [FT_PI_DISCOUNT_RATE]: false,
        [FT_PI_BB_ACCOUNT_SERV_TO_SERV]: false,
        [FT_PI_KILL_SWITCH_CHAT_BOX]: false,
        [FT_PI_SHOW_CHAT_BOT_ALL_PAGES]: false,
        [FT_PI_SIGNUP_IN_HEADER]: false,
        [FT_PI_CCUI_CONSOLIDATE_MOBILE_LANDLINE]: false,
        [FT_PI_BOOKING_STEPS_WITH_TITLE]: false,
        [FT_PI_PROMO_CODE_LANDING_PAGE]: false,
        [FT_PI_PROMO_CODE_SITE_WIDE]: false,
        [FT_PI_DISPLAY_SOFT_BUNDLES]: false,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN]: false,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN_ANCILLARIES_GDP_PAYMENT]: false,
        [FT_PI_AUTH0_LOGIN]: false,
        [FT_PI_FREE_FNB_AND_EXTRAS]: false,
        [FT_PI_REMOVE_PII_DATA_FROM_LOCAL_STORAGE]: false,
      },
    },
  },
  PRE_CHECK_IN: {
    featureToogles: {
      appPage: 'PI | Pre Check-In Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_PRE_CHECK_IN]: false,
        [FT_PI_KILL_SWITCH_CHAT_BOX]: false,
        [FT_PI_SHOW_CHAT_BOT_ALL_PAGES]: false,
        [FT_PI_SIGNUP_IN_HEADER]: false,
        [FT_PI_AUTH0_LOGIN]: false,
        [FT_MOBILE_PREREGISTERED_REPURPOSE]: false,
      },
    },
  },
  REGISTER: {
    featureToogles: {
      appPage: 'PI | Register Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_RECAPTCHA_REGISTER]: false,
        [FT_PI_BB_CCUI_COMPANY_NAME_SPECIAL_CHARACTERS]: false,
        [FT_PI_KILL_SWITCH_CHAT_BOX]: false,
        [FT_PI_SHOW_CHAT_BOT_ALL_PAGES]: false,
        [FT_PI_SIGNUP_IN_HEADER]: false,
        [FT_PI_BB_CCUI_COUNTRY_SELECTOR_FILTERABLE]: false,
        [FT_PI_BASKET_IDS_COOKIE_VALIDATION]: false,
        [FT_PI_AUTH0_LOGIN]: false,
      },
    },
  },
  DASHBOARD: {
    featureToogles: {
      appPage: 'PI | Dashboard Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_BB_NON_GUARANTEED_REMINDER]: false,
        [FT_PI_KILL_SWITCH_CHAT_BOX]: false,
        [FT_PI_SHOW_CHAT_BOT_ALL_PAGES]: false,
        [FT_PI_BB_CCUI_SHOW_MEALS_FREE]: false,
        [FT_PI_SIGNUP_IN_HEADER]: false,
        [FT_PI_PROMO_CODE_LANDING_PAGE]: false,
        [FT_PI_PROMO_CODE_SITE_WIDE]: false,
        [FT_PI_BB_BOOKING_HISTORY_REDESIGN]: false,
        [FT_PI_NO_ROOM_TYPE_SEARCH]: false,
        [FT_PI_TWO_MONTH_SEARCH]: false,
        [FT_PI_BOOKING_STATUS_IN_BIC_HEADER]: false,
        [FT_PI_DISPLAY_SOFT_BUNDLES]: false,
        [FT_PI_AUTH0_LOGIN]: false,
        [FT_PI_PIB_BIC_DOWNLOAD_INVOICE]: false,
        [FT_PI_FREE_FNB_AND_EXTRAS]: false,
        [FT_PI_BB_CCUI_PROMOTIONS_IN_HOTELAVAILABILITY]: false,
      },
    },
  },
  HDP: {
    featureToggles: {
      appPage: 'PI | HDP | Hotel Details Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        ...commonFeatureToggles,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN]: false,
        [FT_PI_BB_SHOW_GOOGLE_STATIC_MAP]: false,
        [FT_PI_ROOM_DETAILS_DRAWER]: false,
        [FT_PI_FREE_FNB_AND_EXTRAS]: false,
        [FT_PI_HDP_URGENCY_BANNER]: false,
        [FT_PI_SHOW_PROMOTION_BOX]: false,
      },
    },
  },
  SRP: {
    featureToggles: {
      appPage: 'PI | SRP | Search Results Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        ...commonFeatureToggles,
        [FT_PI_BB_CCUI_SRP_MULTIPLE_IMAGES]: false,
        [FT_PI_BB_CONTROLS_MOBILE_DISPLAY]: false,
        [FT_PI_FREE_FNB_AND_EXTRAS]: false,
        [FT_SRP_DYNAMIC_FILTERS]: false,
        [FT_PI_SRP_SPLIT_MAP_VIEW]: false,
      },
    },
  },
  ANCILLARIES: {
    featureToogles: {
      appPage: 'PI | Ancillaries Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_BREAKFAST_PROMO_CODE]: false,
        [FT_PI_DISCOUNT_RATE]: false,
        [FT_PI_KILL_SWITCH_CHAT_BOX]: false,
        [FT_PI_SHOW_CHAT_BOT_ALL_PAGES]: false,
        [FT_PI_BB_CANCELLATION_POLICY]: false,
        [FT_PI_BB_CCUI_SHOW_MEALS_FREE]: false,
        [FT_PI_SIGNUP_IN_HEADER]: false,
        [FT_PI_BOOKING_STEPS_WITH_TITLE]: false,
        [FT_PI_PROMO_CODE_LANDING_PAGE]: false,
        [FT_PI_PROMO_CODE_SITE_WIDE]: false,
        [FT_PI_DISPLAY_SOFT_BUNDLES]: false,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN]: false,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN_ANCILLARIES_GDP_PAYMENT]: false,
        [FT_PI_AUTH0_LOGIN]: false,
        [FT_PI_FREE_FNB_AND_EXTRAS]: false,
      },
    },
  },
  GROUP_BOOKING_FORM: {
    featureToogles: {
      appPage: 'PI | Group Booking Form Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_GROUP_WEB_SSR_REST_CALL]: false,
        [FT_PI_KILL_SWITCH_CHAT_BOX]: false,
        [FT_PI_SHOW_CHAT_BOT_ALL_PAGES]: false,
        [FT_PI_SIGNUP_IN_HEADER]: false,
        [FT_PI_PROMO_CODE_LANDING_PAGE]: false,
        [FT_PI_PROMO_CODE_SITE_WIDE]: false,
        [FT_PI_AUTH0_LOGIN]: false,
      },
    },
  },
  PAYMENT: {
    featureToggles: {
      appPage: 'PI | Payment Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_BB_CCUI_COMPANY_NAME_SPECIAL_CHARACTERS]: false,
        [FT_PI_DISCOUNT_RATE]: false,
        [FT_PI_ENABLE_PAYPAL]: false,
        [FT_PI_ENABLE_PAYMENT_REDESIGN]: false,
        [FT_PI_BB_CCUI_DISABLE_PAYMENTS]: false,
        [FT_PI_BB_NON_GUARANTEED_REMINDER]: false,
        [FT_PI_KILL_SWITCH_CHAT_BOX]: false,
        [FT_PI_SHOW_CHAT_BOT_ALL_PAGES]: false,
        [FT_PI_SIGNUP_IN_HEADER]: false,
        [FT_PI_BOOKING_STEPS_WITH_TITLE]: false,
        [FT_PI_PROMO_CODE_LANDING_PAGE]: false,
        [FT_PI_PROMO_CODE_SITE_WIDE]: false,
        [FT_PI_PIB_SWAP_PAYMENT_OPTIONS]: false,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN]: false,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN_ANCILLARIES_GDP_PAYMENT]: false,
        [FT_PI_PIB_PAYMENT_BACK_TO_OPTIONS_LINK]: false,
        [FT_PI_AUTH0_LOGIN]: false,
        [FT_PI_PIB_CCUI_ENABLE_HUB_HOTELS_POA]: false,
        [FT_PI_FREE_FNB_AND_EXTRAS]: false,
        [FT_PI_REMOVE_PII_DATA_FROM_LOCAL_STORAGE]: false,
        [FT_PI_DATATRANS_INTEGRATION]: false,
      },
    },
  },
  CONFIRMATION: {
    featureToggles: {
      appPage: 'PI | Confirmation Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_CP_CREATE_ACCOUNT]: false,
        [FT_PI_DISCOUNT_RATE]: false,
        [FT_PI_BB_NON_GUARANTEED_REMINDER]: false,
        [FT_PI_KILL_SWITCH_CHAT_BOX]: false,
        [FT_PI_SHOW_CHAT_BOT_ALL_PAGES]: false,
        [FT_PI_SIGNUP_IN_HEADER]: false,
        [FT_PI_BOOKING_STEPS_WITH_TITLE]: false,
        [FT_PI_PROMO_CODE_LANDING_PAGE]: false,
        [FT_PI_PROMO_CODE_SITE_WIDE]: false,
        [FT_PI_BASKET_IDS_COOKIE_VALIDATION]: false,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN]: false,
        [FT_PI_AUTH0_LOGIN]: false,
        [FT_PI_BB_SHOW_GOOGLE_STATIC_MAP]: false,
        [FT_PI_FREE_FNB_AND_EXTRAS]: false,
      },
    },
  },
  CHOOSE_BATHROOM: {
    featureToggles: {
      appPage: 'PI | Choose Bathroom Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_CCUI_BB_PREM_PLUS_ACCESSIBLE]: false,
        [FT_PI_KILL_SWITCH_CHAT_BOX]: false,
        [FT_PI_SHOW_CHAT_BOT_ALL_PAGES]: false,
        [FT_PI_SIGNUP_IN_HEADER]: false,
        [FT_PI_PROMO_CODE_LANDING_PAGE]: false,
        [FT_PI_PROMO_CODE_SITE_WIDE]: false,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN]: false,
        [FT_PI_AUTH0_LOGIN]: false,
      },
    },
  },
  CHOOSE_ROOMTYPE: {
    featureToggles: {
      appPage: 'PI | Choose Roomtype Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_CCUI_BB_PREM_PLUS_ACCESSIBLE]: false,
        [FT_PI_BB_CCUI_CHOOSE_ROOM_TYPE]: false,
        [FT_PI_KILL_SWITCH_CHAT_BOX]: false,
        [FT_PI_SHOW_CHAT_BOT_ALL_PAGES]: false,
        [FT_PI_SIGNUP_IN_HEADER]: false,
        [FT_PI_PROMO_CODE_LANDING_PAGE]: false,
        [FT_PI_PROMO_CODE_SITE_WIDE]: false,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN]: false,
        [FT_PI_AUTH0_LOGIN]: false,
      },
    },
  },
  CHOOSE_TWINROOM: {
    featureToggles: {
      appPage: 'PI | Choose Twinroom Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_KILL_SWITCH_CHAT_BOX]: false,
        [FT_PI_SHOW_CHAT_BOT_ALL_PAGES]: false,
        [FT_PI_SIGNUP_IN_HEADER]: false,
        [FT_PI_PROMO_CODE_LANDING_PAGE]: false,
        [FT_PI_PROMO_CODE_SITE_WIDE]: false,
        [FT_PI_PIB_CCUI_CITY_TAX_BREAKDOWN]: false,
        [FT_PI_AUTH0_LOGIN]: false,
      },
    },
  },
  OPERA_SHARED: {
    HEADER: {
      featureToggles: {
        appPage: 'PI | Opera Shared | Header',
        flagsWithFallback: {
          ...globalFeatureToggles,
          ...commonFeatureToggles,
          [FT_PI_AUTH0_LOGIN]: false,
        },
      },
    },
    FOOTER: {
      featureToggles: {
        appPage: 'PI | Opera Shared | Footer',
        flagsWithFallback: {
          ...globalFeatureToggles,
          ...commonFeatureToggles,
        },
      },
    },
  },
  PRICE_FINDER: {
    featureToggles: {
      appPage: 'PI | Price Finder Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_SIGNUP_IN_HEADER]: false,
        [FT_PI_PRICE_FINDER_SEO_NOINDEX]: false,
        [FT_PI_PIB_CCUI_SHOW_LOWEST_PRICE_MONTH_TAB]: false,
        [FT_PI_PIB_CCUI_SHOW_FILTER_ROOM_TYPES]: false,
        [FT_PI_AUTH0_LOGIN]: false,
      },
    },
  },
  ADD_TO_WALLET: {
    featureToggles: {
      appPage: 'PI | Add to Wallet Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_ADD_TO_WALLET]: false,
      },
    },
  },
  RESET_PASSWORD: {
    featureToggles: {
      appPage: 'PI | Reset Password Page',
      flagsWithFallback: {
        ...globalFeatureToggles,
        [FT_PI_AUTH0_LOGIN]: false,
      },
    },
  },
};
