query MyQuery(
    $hotelId: String    
    $companyName: String   
    $limit: Int 
) {
    searchCompanies(
        searchCompaniesCriteria: {
            companyName: $companyName           
            limit: $limit   
            hotelId: $hotelId
        }
    ) {
        companies {
            name
            arNumber
            address {
                addressLine1
                addressLine2
                addressLine3
                addressLine4
                country
                postalCode
            }
            telephoneNumber
            corpId
            companyId
            profileType
            language
            active
            restricted
            negotiatedRateEnabled
        }
    }
}