query getUpcomingBookings(
    $country: String!
    $language: String!
    $channel: String!
    $subchannel: String!
  ) {
    getUpcomingBookings(
      upcomingBookingsRequest: {
        country: $country
        language: $language
        channel: $channel
        subchannel: $subchannel
      }
    ) {
      arrivalDate
      arrivalTime
      bookingReference
      bookings
      brand
      departureDate
      departureTime
      galleryImages {
        alt
        imageSrc
      }
      hotelName
      stays
    }
  }