query getWorldlineUserPreferences(
    $tetheredUserGuids: [String]!
) {
    getWorldlineUserPreferences(tetheredUserGuids: $tetheredUserGuids) {
        tetheredUserGuid
        settings {
            smsTypeId
            isSmsSelected
            smsTypeDescription
            smsType
        }
        details {
            showSmsStopsToCardholder
            sendCardsToCardholder
            accountName
            roleId
            accountNumber
            roleDescription
        }
    }
}