package uk.co.whitbread.reservation;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * Errors map.The Error's message is used by the globalTxtErrTemplate.
 */

@RequiredArgsConstructor
@Getter
public enum ErrorCode {

  DIGITAL_RESERVATION_CHARGES_EXCEPTION(Constants.RESOURCE_NOT_FOUND_EXCEPTION, 55),
  DIGITAL_RESERVATION_ID_EXCEPTION(Constants.RESOURCE_NOT_FOUND_EXCEPTION, 56),
  DIGITAL_UPDATE_ROOM_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 58),
  DIGITAL_INCONSISTENT_BASKET_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 59),
  DIGITAL_INCONSISTENT_DATES_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 60),
  DIGITAL_INCONSISTENT_PACKAGES_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 61),
  DIGITAL_INCONSISTENT_BOOKING_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 62),
  DIGITAL_NON_REFUNDABLE_BOOKING_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 63),
  DIGITAL_BASKET_EXPIRED_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 64),
  DIGITAL_WRONG_ROOM_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 65),
  DIGITAL_BASKET_REMOVE_RELOAD_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 66),
  DIGITAL_NULL_ROOM_REMOVAL_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 67),
  DIGITAL_ROOM_REMOVAL_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 68),
  DIGITAL_ROOM_NOT_IN_BASKET_REMOVAL(Constants.GENERIC_VALIDATION_EXCEPTION, 69),
  DIGITAL_LAST_ROOM_REMOVAL(Constants.GENERIC_VALIDATION_EXCEPTION, 70),
  DIGITAL_BASKET_ADD_RELOAD_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 71),
  DIGITAL_BASKET_ADD_ROOM_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 72),
  DIGITAL_BASKET_ADD_WRONG_ROOM_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 73),
  DIGITAL_RESERVATION_EXTIDS_EXCEPTION(Constants.RESOURCE_NOT_FOUND_EXCEPTION, 74),
  DIGITAL_RESERVATION_CONF_EXCEPTION(Constants.RESOURCE_NOT_FOUND_EXCEPTION, 75),
  DIGITAL_TEMP_BASKET_HAS_EXPIRED_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 76),
  DIGITAL_NO_RESERVATION_BASKET_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 77),
  DIGITAL_NULL_OPERA_RESERVATIONS_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 78),
  DIGITAL_OPERA_RESERVATIONS_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 79),
  DIGITAL_BASKET_RIGHT_STATUS_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 80),
  DIGITAL_BASKET_ATTACHED_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 81),
  DIGITAL_ON_HOLD_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 82),
  DIGITAL_CANCELLED_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 83),
  DIGITAL_AMEND_DATE_EXCEPTION(Constants.AMEND_DATE_EXCEPTION, 84),
  DIGITAL_AMEND_REVERT_EXCEPTION(Constants.AMEND_REVERT_EXCEPTION, 85),
  DIGITAL_AMEND_CONFIRM_EXCEPTION(Constants.AMEND_CONFIRM_EXCEPTION, 86),
  DIGITAL_AMEND_DEPOSIT_REVERT_EXCEPTION(Constants.AMEND_REVERT_EXCEPTION, 87),
  DIGITAL_AMEND_DEPOSIT_FOLIOS_EXCEPTION(Constants.AMEND_DEPOSIT_FOLIOS_EXCEPTION, 88),
  DIGITAL_AMEND_DELETE_RESERV_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 89),
  DIGITAL_NR_NIGHTS_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 90),
  DIGITAL_INVALID_SOURCE_EXCEPTION(Constants.INVALID_SOURCE_CODE, 91),
  DIGITAL_NOT_FOUND_SOURCE_EXCEPTION(Constants.INVALID_SOURCE_CODE, 92),
  DIGITAL_CLONE_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 93),
  DIGITAL_DELETE_BASKET_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 94),
  DIGITAL_REFUND_REQUEST_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 95),
  DIGITAL_AMOUNT_REFUND_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 96),
  DIGITAL_CANCEL_POLICIES_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 97),
  DIGITAL_ADD_NEW_ROOM_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 98),
  DIGITAL_CANCEL_MIGRATED_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 99),
  DIGITAL_BASKET_ITEM_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 100),
  DIGITAL_FIND_BASKET_ITEM_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 101),
  DIGITAL_AMEND_LOGIC_REFUND_EXCEPTION(Constants.AMEND_REFUND_EXCEPTION, 102),
  DIGITAL_RESERVATION_BASKET_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 103),
  DIGITAL_OPERA_DOWN_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 104),
  DIGITAL_INVALID_TEMPBOOKING_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 105),
  DIGITAL_INVALID_ROOM_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 106),
  DIGITAL_INVALID_OCCUPANCY_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 107),
  DIGITAL_INVALID_LEAD_GUEST_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 108),
  DIGITAL_INVALID_INFO_LEAD_GUEST_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 109),
  DIGITAL_INVALID_EMAIL_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 110),
  DIGITAL_INVALID_ROOMTYPE_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 111),
  DIGITAL_INVALID_CHANNEL_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 112),
  DIGITAL_INVALID_CHANNEL_SUBCHANNEL_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 113),
  DIGITAL_EXTRACT_BASKET_BODY_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 114),
  DIGITAL_EXTRACT_ETAG_HEADERS_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 115),
  DIGITAL_BUSINESS_NOTES_FORMATTING_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 116),
  DIGITAL_BUSINESS_NOTES_FORMATTING2_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 117),
  DIGITAL_BUSINESS_NOTES_FORMATTING3_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 118),
  DIGITAL_INVALID_TOKEN1(Constants.INVALID_TOKEN, 119),
  DIGITAL_INVALID_TOKEN2(Constants.INVALID_TOKEN, 120),
  DIGITAL_INVALID_TOKEN3(Constants.INVALID_TOKEN, 121),
  DIGITAL_CANCEL_RESERVATION(Constants.INTERNAL_SERVER_EXCEPTION, 122),
  DIGITAL_INVALID_IATA_NUMBER_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 123),
  DIGITAL_BASKET_NOT_FOUND(Constants.RESOURCE_NOT_FOUND_EXCEPTION, 229),
  OPERA_RESERVATION_ID_EXCEPTION(Constants.RESOURCE_NOT_FOUND_EXCEPTION, 223),
  DIGITAL_CANCEL_REFUND_EXCEPTION(Constants.CANCEL_REFUND_EXCEPTION, 231),
  DIGITAL_PACKAGES_ORDER(Constants.GENERIC_VALIDATION_EXCEPTION, 235),
  DIGITAL_EXPIRED_BASKET(Constants.GENERIC_VALIDATION_EXCEPTION, 236),
  DIGITAL_DATE_AMEND_EXCEPTION(Constants.AMEND_DATE_EXCEPTION, 238),
  DIGITAL_INCORRECT_SCHEDULE_PACKAGES_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 239),
  DIGITAL_INVALID_WBTOKEN(Constants.INVALID_TOKEN, 259),
  DIGITAL_INVALID_OTA_EXCEPTION(Constants.THIRD_PARTY_INVALID_EXCEPTION, 291),
  DIGITAL_NOT_MATCH_OTA_EXCEPTION(Constants.THIRD_PARTY_INVALID_DETAIL_EXCEPTION, 292),
  DIGITAL_PROMOTION_ALREADY_USED_EXCEPTION(Constants.INVALID_PROMOTION, 294),
  DIGITAL_PROMOTION_EXPIRED_EXCEPTION(Constants.INVALID_PROMOTION, 295),
  DIGITAL_PROMOTION_NOT_FOUND(Constants.RESOURCE_NOT_FOUND_EXCEPTION, 296),
  DIGITAL_UL_UNAUTHORIZED_ERROR_CODE(Constants.INVALID_TOKEN, 7011);

  private final String message;
  private final int code;

  public static class Constants {

    public static final String INTERNAL_SERVER_EXCEPTION = "internal.server.exception";
    public static final String GENERIC_VALIDATION_EXCEPTION = "generic.validation.exception";
    public static final String RESOURCE_NOT_FOUND_EXCEPTION = "resource.not.found.exception";
    public static final String INVALID_TOKEN = "invalid.token";
    public static final String INVALID_SOURCE_CODE = "invalid.source.code";
    public static final String AMEND_CONFIRM_EXCEPTION = "AMEND_CONFIRM_EXCEPTION";
    public static final String AMEND_DEPOSIT_FOLIOS_EXCEPTION = "AMEND_DEPOSIT_FOLIOS_EXCEPTION";
    public static final String AMEND_REFUND_EXCEPTION = "AMEND_REFUND_EXCEPTION";
    public static final String AMEND_REVERT_EXCEPTION = "AMEND_REVERT_EXCEPTION";
    public static final String AMEND_DATE_EXCEPTION = "amend.date.exception";
    public static final String CANCEL_REFUND_EXCEPTION = "CANCEL_REFUND_EXCEPTION";
    public static final String THIRD_PARTY_INVALID_EXCEPTION = "third.party.error.invalid";
    public static final String THIRD_PARTY_INVALID_DETAIL_EXCEPTION = "third.party.error.invalid.details";
    public static final String INVALID_PROMOTION = "promotion.invalid";

    private Constants() {
    }
  }
}