import type { GuestDetailsFormStateLocalType } from '@whitbread-eos/api';

export const INITIAL_GUEST_DETAILS_FORM_DATA: GuestDetailsFormStateLocalType = {
  reasonForStay: '',
  title: '',
  firstName: '',
  lastName: '',
  email: '',
  phone: '',
  landline: '',
  companyName: '',
  addressLine1: '',
  addressLine2: '',
  addressLine3: '',
  addressLine4: '',
  postalCode: '',
  cityName: '',
  postcodeAddress: '',
  addressSelection: '',
  countryCode: '',
  manualAddressToggle: '',
  basketReferenceId: '',
  leadGuest: [],
  bookingForSomeoneElse: false,
  updateProfileConsent: false,
  billing: {
    address: {
      countryCode: '',
      companyName: '',
      addressLine1: '',
      addressLine2: '',
      addressLine3: '',
      addressLine4: '',
      postalCode: '',
      addressType: '',
    },
    title: '',
    firstName: '',
    lastName: '',
    email: '',
    telephone: '',
    differentBillingAddress: false,
  },
  whoBookerIsTabs: 'MYSELF',
  dateOfBirth: '',
  nationality: '',
  passport: '',
};
