import {
  BIGGER_ROOM_CODE,
  NEW_HOTEL_MESSAGING_FLAG_TEXT,
  NEW_ROOMS_MESSAGING_FLAG_TEXT,
  OPENING_SOON_MESSAGING_FLAG_TEXT,
  PREMIER_EXTRA_CODE,
  PREMIER_PLUS_FACILITY_CODE,
  STANDARD_EXTRA_FACILITY_CODE,
  MLOS,
} from './badges';
import { DATE_FORMAT } from './bookingHistory';
import { INITIAL_GUEST_DETAILS_FORM_DATA } from './guest-details';
import {
  TRIP_ADVISOR_RATING_IMAGE_URL_PART1,
  TRIP_ADVISOR_RATING_IMAGE_URL_PART2,
  TRIP_ADVISOR_SCHEMA_REVIEW_URL,
  TRIP_ADVISOR_SCHEMA_ORGANIZATION_URL,
  TRIP_ADVISOR_SCHEMA_RATING_URL,
  TRIP_ADVISOR_SCHEMA_PERSON_URL,
} from './hotel-details';

export { INITIAL_GUEST_DETAILS_FORM_DATA };
export {
  PREMIER_PLUS_FACILITY_CODE,
  STANDARD_EXTRA_FACILITY_CODE,
  BIGGER_ROOM_CODE,
  NEW_HOTEL_MESSAGING_FLAG_TEXT,
  NEW_ROOMS_MESSAGING_FLAG_TEXT,
  OPENING_SOON_MESSAGING_FLAG_TEXT,
  PREMIER_EXTRA_CODE,
  MLOS,
};
export { DATE_FORMAT };
export {
  TRIP_ADVISOR_RATING_IMAGE_URL_PART1,
  TRIP_ADVISOR_RATING_IMAGE_URL_PART2,
  TRIP_ADVISOR_SCHEMA_REVIEW_URL,
  TRIP_ADVISOR_SCHEMA_ORGANIZATION_URL,
  TRIP_ADVISOR_SCHEMA_RATING_URL,
  TRIP_ADVISOR_SCHEMA_PERSON_URL,
};
