<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>uk.co.whitbread</groupId>
    <artifactId>digital-monorepo-service-parent</artifactId>
    <version>${revision}</version>
    <relativePath>../../../parents/service-parent/pom.xml</relativePath>
  </parent>

  <artifactId>address-lookup-entity-service</artifactId>
  <packaging>jar</packaging>

  <properties>
    <application.port>9111</application.port>
    <sonar.coverage.jacoco.xmlReportPaths>${project.basedir}/target/site/jacoco-all/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
    <sonar.coverage.exclusions>
      **/AddressLookupServiceApplication*,
      **/generated/**,
      **/model/**,
      **/config/**,
      **/exceptions/**,
      **/properties/**
    </sonar.coverage.exclusions>
  </properties>

  <name>address-lookup-entity-service</name>
  <description>Whitbread Address Lookup Entity Service</description>

  <dependencies>
    <!-- Whitbread -->
    <dependency>
      <groupId>commons-validator</groupId>
      <artifactId>commons-validator</artifactId>
    </dependency>

    <dependency>
      <groupId>uk.co.whitbread.shared</groupId>
      <artifactId>commons-logging</artifactId>
      <exclusions>
        <exclusion>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-databind</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>uk.co.whitbread.shared</groupId>
      <artifactId>qas-address-lookup-lib</artifactId>
      <exclusions>
        <exclusion>
          <groupId>jakarta.jws</groupId>
          <artifactId>jakarta.jws-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>org.apache.httpcomponents.client5</groupId>
      <artifactId>httpclient5</artifactId>
    </dependency>

    <!-- Spring/SpringBoot -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web-services</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>

    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
    </dependency>

    <!-- Test -->
    <dependency>
      <groupId>org.wiremock.integrations</groupId>
      <artifactId>wiremock-spring-boot</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
    </dependency>

    <dependency>
      <groupId>org.openapitools</groupId>
      <artifactId>jackson-databind-nullable</artifactId>
    </dependency>

    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-core</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-micrometer-tracing-brave</artifactId>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <jvmArguments>-Dspring.application.admin.enabled=true</jvmArguments>
        </configuration>
        <executions>
          <execution>
            <id>pre-integration-test</id>
            <goals>
              <goal>start</goal>
            </goals>
          </execution>
          <execution>
            <id>post-integration-test</id>
            <goals>
              <goal>stop</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>integration-test</id>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <apiDocsUrl>http://localhost:${application.port}/v3/api-docs.yaml</apiDocsUrl>
          <outputFileName>${project.name}-openApi.yaml</outputFileName>
          <outputDir>${basedir}/docs/openApi</outputDir>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>**/uk/co/whitbread/**/AddressLookupServiceApplication*</exclude>
            <exclude>**/uk/co/whitbread/**/model/**</exclude>
            <exclude>**/uk/co/whitbread/**/config/**</exclude>
            <exclude>**/uk/co/whitbread/**/exceptions/**</exclude>
            <exclude>**/uk/co/whitbread/**/properties/**</exclude>
            <exclude>**/uk/co/whitbread/**/generated/**</exclude>
            <exclude>**/*MapperImpl*</exclude>
          </excludes>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-contract-maven-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <baseClassForTests>uk.co.whitbread.address.lookup.ContractVerifierBaseTest</baseClassForTests>
          <basePackageForTests>uk.co.whitbread.address.lookup</basePackageForTests>
          <nameSuffixForTests>IT</nameSuffixForTests>
          <testFramework>JUNIT5</testFramework>
        </configuration>
      </plugin>

    </plugins>
  </build>

</project>
