<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>uk.co.whitbread</groupId>
    <artifactId>digital-monorepo-service-parent</artifactId>
    <version>${revision}</version>
    <relativePath>../../../parents/service-parent/pom.xml</relativePath>
  </parent>

  <artifactId>rules-manager-entity-service</artifactId>
  <packaging>jar</packaging>

  <description>Whitbread Rules Manager Entity Service</description>
  <name>rules-manager-entity-service</name>

  <properties>
    <application.port>9105</application.port>
    <sonar.coverage.exclusions>
      **/uk/co/whitbread/**/**/model/**,
      **/uk/co/whitbread/**/**/config/**,
      **/uk/co/whitbread/**/**/exceptions/**,
      **/uk/co/whitbread/**/**/properties/**,
      **/uk/co/whitbread/**/*MapperImpl*,
      **/uk/co/whitbread/**/RulesManagerServiceApplication*
    </sonar.coverage.exclusions>
  </properties>

  <dependencies>
    <!-- Whitbread -->
    <dependency>
      <groupId>uk.co.whitbread.shared</groupId>
      <artifactId>commons-exceptions</artifactId>
    </dependency>

    <!-- Spring/SpringBoot -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web-services</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-micrometer-tracing-brave</artifactId>
    </dependency>

    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>

    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-liquibase</artifactId>
    </dependency>

    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-core</artifactId>
    </dependency>

    <!-- Test -->
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>**/uk/co/whitbread/**/model/**</exclude>
            <exclude>**/uk/co/whitbread/**/exceptions/**</exclude>
            <exclude>**/uk/co/whitbread/**/config/**</exclude>
            <exclude>**/uk/co/whitbread/**/properties/**</exclude>
            <exclude>**/uk/co/whitbread/**/RulesManagerServiceApplication*</exclude>
          </excludes>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.pitest</groupId>
        <artifactId>pitest-maven</artifactId>
        <configuration>
          <excludedClasses>
            <param>uk.co.whitbread.rules.manager.RulesManagerServiceApplication</param>
          </excludedClasses>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
