<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="Implementation" targetNamespace="worldline.mst.bsm.api.b2b.pi.messages.v1.1"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy"
                  xmlns:wsa10="http://www.w3.org/2005/08/addressing"
                  xmlns:tns="worldline.mst.bsm.api.b2b.pi.messages.v1.1"
                  xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
                  xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"
                  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import namespace="worldline.mst.bsm.api.b2b.pi.messages.v1.1" location="mex.wsdl"/>
  <wsdl:types/>
  <wsdl:binding name="BasicHttpBinding_IB2BPIAPI" type="tns:IB2BPIAPI">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="cnpCheckMemorableWord">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/cnpCheckMemorableWord"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="cnpCheckTelephoneBooking">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/cnpCheckTelephoneBooking"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="cnpCheckTetheredUser">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/cnpCheckTetheredUser"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="endSession">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/endSession"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="loginTetheredUser">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/loginTetheredUser"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="refreshSession">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/refreshSession"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="registrationAuthenticate">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/registrationAuthenticate"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="registrationGetInfo">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/registrationGetInfo"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="registrationSubmit">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/registrationSubmit"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="tetherByAccountNumber">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/tetherByAccountNumber"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="tetherByCardNumber">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/tetherByCardNumber"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="updateMemorableWord">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/updateMemorableWord"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="customerAccountViewCurrentBalances">
      <soap:operation
              soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/customerAccountViewCurrentBalances"
              style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="customerAccountViewTransactions">
      <soap:operation
              soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/customerAccountViewTransactions"
              style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="cnpHostedPageInitiate">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/cnpHostedPageInitiate"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="cnpHostedPageResult">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/cnpHostedPageResult"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="creditProposeNewLimit">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/creditProposeNewLimit"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="creditProposeNewLimitGetStatus">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/creditProposeNewLimitGetStatus"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="customerAccountCardActivate">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/customerAccountCardActivate"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="customerAccountCardAdd">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/customerAccountCardAdd"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="customerAccountCardCancel">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/customerAccountCardCancel"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="customerAccountCardInvite">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/customerAccountCardInvite"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="customerAccountCardList">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/customerAccountCardList"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="customerAccountCardRenew">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/customerAccountCardRenew"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="customerAccountCardUpdate">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/customerAccountCardUpdate"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="customerAccountCardView">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/customerAccountCardView"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="customerAccountInvoiceDownload">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/customerAccountInvoiceDownload"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="customerAccountInvoiceList">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/customerAccountInvoiceList"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="customerAccountRegisteredUserList">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/customerAccountRegisteredUserList"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="tetheredUserDetailsGet">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/tetheredUserDetailsGet"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="customerAccountCostCentreList">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/customerAccountCostCentreList"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="cnpGetDigitsForCheckTelephoneBooking">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/cnpGetDigitsForCheckTelephoneBooking"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="cnpCheckTelephoneBookingBySessionID">
      <soap:operation soapAction="worldline.mst.bsm.api.b2b.pi.messages.v1.1/IB2BPIAPI/cnpCheckTelephoneBookingBySessionID"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Implementation">
    <wsdl:port name="BasicHttpBinding_IB2BPIAPI" binding="tns:BasicHttpBinding_IB2BPIAPI">
      <soap:address location="https://test-premierinn.worldline.global/b2b.pi.v1.1/b2bpiapi.svc"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
