# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx10248m -XX:MaxPermSize=256m
org.gradle.jvmargs=-Xms4096m -Xmx8192m -XX:MaxMetaspaceSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
org.gradle.parallel=true

org.gradle.daemon=true

android.builder.sdkDownload=true
android.useAndroidX=true
android.enableJetifier=true
android.debug.obsoleteApi=true
kapt.incremental.apt=true
android.nonTransitiveRClass=true
android.nonFinalResIds=false
dagger.hilt.disableModulesHaveInstallInCheck=true
-Adagger.hilt.disableModulesHaveInstallInCheck=true
-Adagger.hilt.disableCrossCompilationRootValidation=true

# Enable build cache for faster incremental builds (speed boost)
org.gradle.caching=true

#TODO: When ready Enable and work through the plugin issues (if any) to use configuration cache:
# Enables the Configuration Cache to skip the expensive configuration phase on subsequent runs.
#org.gradle.configuration-cache=true

# If your build fails, uncomment this line to turn errors into warnings.
# This allows the build to continue using the cache, even if plugins violate the rules, allowing us
# to find the culprit plugins to fix.
# org.gradle.configuration-cache.problems=warn

# Enables parallel cache loading (huge speed boost)
# Loads the configuration cache across multiple CPU cores for faster startup on large projects.
# //Use once org.gradle.configuration-cache=true is stable with all existing plugins
#org.gradle.configuration-cache.parallel=true

