package uk.co.whitbread.payapp;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum ErrorCode {
  USER_EMAIL_MISMATCH_ERROR(Constants.GENERIC_VALIDATION_EXCEPTION, 253),
  WORLDLINE_APP_INIT_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 254),
  WORLDLINE_APP_FETCH_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 255),
  TOKEN_CANNOT_BE_PARSED(Constants.GENERIC_VALIDATION_EXCEPTION, 256),
  WORLDLINE_APP_CONTACT_DETAILS_UPDATE_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 257),
  CDH_APPLICATION_NOT_FOUND_ERROR(Constants.RESOURCE_NOT_FOUND_EXCEPTION, 258),
  WORLDLINE_APP_CANCEL_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 260),
  CDH_APP_CANCEL_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 261),
  APPLICATION_ACCESS_DENIED(Constants.GENERIC_VALIDATION_EXCEPTION, 262),
  WORLDLINE_APP_LOOKUP_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 263),
  WORLDLINE_USER_PREFERENCES_FETCH_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 264),
  WORLDLINE_COMPANY_DETAILS_LOOKUP_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 265),
  WORLDLINE_APP_COMPANY_DETAILS_UPDATE_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 266),
  COMPANY_GET_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 267),
  WORLDLINE_APP_ADD_CARD_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 268),
  USER_ROLE_MISMATCH_ERROR(Constants.GENERIC_VALIDATION_EXCEPTION, 269),
  WORLDLINE_APP_CARD_DELETE_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 270),
  WORLDLINE_APP_CARDS_GET_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 271),
  WORLDLINE_APP_SUBMIT_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 273),
  WORLDLINE_APP_PRE_CHECK_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 274),
  WORLDLINE_HOSTED_PAGE_APP_INIT_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 275),
  APP_ALREADY_SHARED_WITH_PARTICIPANT(Constants.GENERIC_VALIDATION_EXCEPTION, 277),
  EMPLOYEE_NOT_IN_COMPANY_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 278),
  WORLDLINE_BANK_DETAILS_STATUS_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 280),
  CDH_GET_EMPLOYEE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 542);

  private final String message;
  private final int code;

  public static class Constants {

    public static final String INTERNAL_SERVER_EXCEPTION = "internal.server.exception";
    public static final String GENERIC_VALIDATION_EXCEPTION = "generic.validation.exception";
    public static final String RESOURCE_NOT_FOUND_EXCEPTION = "resource.not.found.exception";

    private Constants() {}
  }
}
