package uk.co.whitbread.wallet;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum ErrorCode {
  DIGITAL_PASS_JSON_CREATION_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 220),
  DIGITAL_WALLET_SIGNATURE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 221),
  DIGITAL_WALLET_CREATION_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 222),
  DIGITAL_COULD_NOT_FIND_FILE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 225),
  DIGITAL_COULD_NOT_READ_PASS_INPUT_STREAM_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 226),
  DIGITAL_COULD_NOT_RESOLVE_DIRECTORY_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 227),
  DIGITAL_BAD_TEMPLATE_CONFIGURATION_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 228),
  DIGITAL_BOOKING_NOT_FOUND_FOR_RESERVATION_EXCEPTION(Constants.RESOURCE_NOT_FOUND_EXCEPTION, 232),
  DIGITAL_DETAILS_NOT_FOUND_FOR_BASKET_EXCEPTION(Constants.RESOURCE_NOT_FOUND_EXCEPTION, 233),
  DIGITAL_HOTEL_INFO_NOT_FOUND_EXCEPTION(Constants.RESOURCE_NOT_FOUND_EXCEPTION, 234),
  DIGITAL_COULD_NOT_RETRIEVE_FILE_FROM_S3(Constants.INTERNAL_SERVER_EXCEPTION, 240),
  DIGITAL_COULD_NOT_SAVE_FILE_LOCALLY(Constants.INTERNAL_SERVER_EXCEPTION, 241),
  DIGITAL_CERTIFICATE_LOADING_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 242);



  private final String message;
  private final int code;

  public static class Constants {

    public static final String INTERNAL_SERVER_EXCEPTION = "internal.server.exception";
    public static final String RESOURCE_NOT_FOUND_EXCEPTION = "resource.not.found.exception";


    private Constants() {
    }

  }
}