FROM 327347623470.dkr.ecr.eu-west-1.amazonaws.com/whitbreaddigital/java-jdk-opera:17.0.18_8-jre-alpine-base-0750d04

ARG APP_NAME
ARG APP_VERSION
ARG JAVA_OPTS
ARG JAR_FILE="/target/${APP_NAME}-${APP_VERSION}.jar"

VOLUME /tmp
ADD $JAR_FILE app.jar

CMD exec java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /app.jar