import { RegistrationQuestionWithAnswer, EmployeeQuestionType } from './employeeQuestions';
import { validateGroupBookingParams } from './groupBooking';
import {
  AddressGuestInput,
  backendDataType,
  GDPersonalDetails,
  Guest as GuestDetails,
  GuestDetailsFormStateLocalResetType,
  GuestDetailsFormStateLocalType,
  ManualGuest,
  Suggestion,
  validateFormParams,
  TitleDropdownOption,
} from './guestDetails';
import { AddressInput, RegisterPersonalDetails, validateRegisterFormParams } from './register';

export type { RegistrationQuestionWithAnswer, EmployeeQuestionType };

export type {
  GDPersonalDetails,
  GuestDetailsFormStateLocalType,
  GuestDetailsFormStateLocalResetType,
  backendDataType,
  validateFormParams,
  GuestDetails,
  Suggestion,
  ManualGuest,
  RegisterPersonalDetails,
  validateRegisterFormParams,
  AddressInput,
  TitleDropdownOption,
  validateGroupBookingParams,
};

export type { CompanyResults, CompanyData, CompanyProfile, CompanyAddress } from './company';

export type AddressGuestInputWithCountry = AddressGuestInput & {
  country?: string;
  billingAddressSelection?: string;
};

export * from './innBusiness';
export * from './hotelInformation';
export * from './ancillariesPackages';
export * from './bookingConfirmation';
export * from './bookingInformation';
export * from './analyticsData';
export * from './footer';
export * from './header';
export * from './bookingSummary';
export * from './common';
export * from './dashboard';
export * from './confirmation';
export * from './payment';
export * from './amend';
export * from './search';
export * from './general';
export * from './searchBookings';
export * from './searchResults';
export * from './searchAccount';
export * from './override';
export * from './bookingHistory';
export * from './staticContent';
export * from './agentMemo';
export * from './references';
export * from './changeLog';
export * from './destination';
export * from './filterByLabels';
// TODO: export type individually until we export all
export type {
  RoomCodes,
  BookingChannelCriteria,
  FindBooking,
  FindBookingCriteria,
  QueryHotelInformationArgs,
  HotelInformation,
  AncillaryCloseout,
  Items,
  BookingInformation,
  ReservationById,
  RoomStay,
  RateExtraInfo,
  AccessibleRoom,
  BillingResponse,
  StayingGuestDetails,
  Guest,
  QueryBookingInformationArgs,
  RoomReservation,
  BookingHistory,
  Booking,
  Price,
  BookingHistoryRequest,
  Query,
  HotelInformationBySlug,
  FacilityItem,
  MessagingFlag,
  Breadcrumb,
  ContactDetails,
  Faq,
  FaqItem,
  ImageItem,
  Address,
  Company,
  RestaurantInfo,
  Menu,
  RoomConfiguration,
  TabGroup,
  TabItem,
  Facts,
  Announcement,
  ImportantInfo,
  InfoItem,
  TripAdvisorReviews,
  Reviews,
  SubRatings,
  Awards,
  BookingFlow,
  BookingFlowItem,
  AccessibilityInfo,
  Coordinates,
  FactItem,
  AmendPaymentPageResponse,
  PaymentOptionsCriteria,
  SearchBooking,
  SearchBookingBooker,
  SearchBookingStayingGuest,
  ResultsCcui,
  CurrencyAmountType,
  BartPackage,
  BartBookingInformation,
  BartRoomStay,
  HotelsSearchCriteria,
  HotelDistance,
  AvailabilitiesSearchCriteria,
  SingleHotelAvailability,
  LowestRoomRate,
  HotelInformationOptional,
  Room,
  Place,
  SrpApi,
  SrpLabel,
  SrpCode,
  SrpFilter,
  DynamicFilters,
  SrpInfo,
  SrpMenu,
  SearchInformation,
  SrpBrand,
  Brand,
  SrpResult,
  PackagesCriteria,
  Packages,
  MealItem,
  MealKids,
  RoomSelection,
  PackageSelection,
  PackagesResponse,
  PrivacyPolicy,
  SecurityInfoItem,
  Restaurant,
  PaymentMethodsCriteria,
  PaymentMethod,
  AcceptedCardType,
  PaymentOption,
  Card,
  ReservationDetails,
  Rooms,
  PackageDetails,
  CancellationInfoResponse,
  CountryInnB,
  ContentInnB,
  InnBusinessHeader,
  MenuInnB,
  HomeInnB,
  SidebarInnB,
  ExtrasItem,
  FormInnB,
  ChevronInnB,
  GlobalInnB,
  NotificationInnB,
  CreateGroupBookingCriteria,
  Footer,
  Tabs,
  Columns,
  LinkItems,
  SocialMediaIcons,
  StayingGuest,
  GuestAddress,
  CustomerAccountDetails,
  CountryInformation,
  EmployeeDetails,
  AnonymousNewsletterPreferences,
  UserDefinedQuestionAnswered,
  AnsweredQuestions,
  PartialAddress,
  AddressInfo,
  CountryDetails,
  FormattedAddress,
  EmployeeCriteria,
  Dlp,
  DlpItem,
  DlpInformation,
  ThingsToDo,
  ToDoItem,
  Promo,
  QueryGetHotelsInformationArgs,
  OrderedHotelCode,
  RoomClassOrder,
  CustomerAddress,
  Customer,
  CompanyDetailsResponse,
  ManagementInformationQuestion,
  CurrentBalanceItem,
  RegistrationRoles,
  Currency as CurrencyGraphql,
  Scheme,
  ManagementInformationAnswer as ManagementInformationAnswerType,
  InnBAccountPibaCards,
  InnBusinessPayCard,
  InitializeApplicationResponse,
  UpcomingBookingsRequest,
  UpcomingBookingsResponse,
  BookingAllowancesCriteria,
  AccountUpcomingSpendingResponse,
  PaymentCardInnB,
  PayApplicationsResponse,
  PayApplicationDetails,
  ApplicationDetailsResponse,
  ApplicationAddress,
  NotificationsResponse,
  UpdateAppContactDetailsCriteria,
  UpdateAppCompanyDetailsCriteria,
  CompanyDetailsLookup,
  AppLookupData,
  RegistrationCodeInfo,
  PibaRegistrationRole,
  AuthenticationAnswer,
  AuthenticationQuestion,
  RegistrationPrePopulatedItems,
  PaymentCardInfo,
  ApplicationParticipant,
  SearchEmployeeResponse,
  ApproveRejectRequest,
  RegistrationDetails,
  AddApplicationCardDetails,
  ForgottenPasswordRequest,
  ResetPasswordRequest,
  ValidateResetKeyRequest,
  ValidateResetKeyResponse,
  Payments as SpendingPayments,
  PaymentValue as SpendingPaymentValue,
  ThumbnailImage,
  InnBpibaCardDetails,
  HotelAvailabilityRoomRate,
  CostCentreData,
  SoftBundles,
  SoftBundle,
  UpdatePreferencesRequest,
  EmployeeSpendCriteria,
  ContactBanner,
} from './graphql';
export {
  UserType,
  Channel,
  PaymentType,
  EmployeeStatus,
  AccessLevel,
  AnswerType as BBAnswerType,
  RegistrationRole,
  QuestionLocation as QuestionLocationType,
  AddressType,
  AddressCorrespondenceEnum,
  DirectDebitOption,
} from './graphql';
