{{- if and .Values.service (ne (.Values.service).create false) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.applicationName }}
    whitbread.services/name: {{ .Values.applicationName }}
    helm.sh/chart: {{ .Chart.Version }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app: {{ .Values.applicationName }}
    whitbread.services/name: {{ .Values.applicationName }}
{{- end -}}