package uk.co.whitbread.domain.exceptions;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum ErrorCode {
  DIGITAL_ROOM_OCCUPANCY_RULE_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 178),
  DIGITAL_NO_AVAILABILITY_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 179),
  DIGITAL_NO_AVAILABILITY_2_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 180),
  DIGITAL_NO_AVAILABILITY_3_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 181),
  DIGITAL_NO_AVAILABILITY_4_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 182),
  DIGITAL_REQUEST_NOT_PROCESSED_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 183),
  DIGITAL_MAX_ROOM_RULE_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 184),
  DIGITAL_MAX_NIGHT_RULE_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 185),
  DIGITAL_ROOM_OCCUPANCY_RULE_2_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 186),
  DIGITAL_INVALID_CHANNEL_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 187),
  DIGITAL_INVALID_CHANNEL_2_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 188),
  DIGITAL_INVALID_LOCATION_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 189),
  DIGITAL_INVALID_LOCATION_2_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 190),
  DIGITAL_NO_AVAILABILITY_5_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 191),
  DIGITAL_NOT_MATCH_REQUEST_ROOM_SUBSTITUTION_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 192),
  DIGITAL_LOWEST_ROOM_RATE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 193),
  DIGITAL_NO_RATE_PLAN_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 194),
  DIGITAL_NO_HOTEL_FOUND_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 195),
  DIGITAL_NO_LOCATION_FOUND_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 196),
  DIGITAL_NO_HOTELS_FOUND_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 197),
  DIGITAL_NO_HOTELS_FOUND_2_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 198),
  DIGITAL_ITEMS_INVENTORY_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 199),
  DIGITAL_PACKAGES_NOT_CONFIGURED_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 200),
  DIGITAL_PROMOTION_ALREADY_USED_EXCEPTION(Constants.INVALID_PROMOTION, 294),
  DIGITAL_PROMOTION_EXPIRED_EXCEPTION(Constants.INVALID_PROMOTION, 295),


  RESOURCE_NOT_FOUND_SNOWDROP_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 512),
  RESOURCE_NOT_FOUND_SNOWDROP_2_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 513),
  SNOWDROP_INTERNAL_ERROR(Constants.INTERNAL_SERVER_EXCEPTION, 546),
  MIGRATION_STATUS_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 514),
  CREATE_HOTEL_AVAILABILITIES_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 515),
  CREATE_HOTEL_AVAILABILITIES_V1_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 516),
  CREATE_HOTEL_AVAILABILITIES_V1_DISTR_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 517),

  GET_SUPPRESSED_COMPANY_RATES_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 545),
  GET_COMPANIES_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 547),
  GET_COMPANY_BY_ID_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 548);

  private final String message;
  private final int code;

  public static class Constants {

    public static final String INTERNAL_SERVER_EXCEPTION = "internal.server.exception";
    public static final String GENERIC_VALIDATION_EXCEPTION = "generic.validation.exception";
    public static final String INVALID_PROMOTION = "promotion.invalid";

    private Constants() {
    }
  }
}
