@startuml
'https://plantuml.com/class-diagram

package uk.co.whitbread.availabilitycacheservice.adapters {
class HotelAvailabilitiesPostProcessorService {
- List<Hotel> updateLimitedAvailability(SearchCriteria criteria, List<Hotel> hotels, List<HotelAvailabilitiesResultSet> hoteslFrmDB)
}
}

package uk.co.whitbread.hotelsearch.service {
class AggregateSearchService {
- List<ShortHotelAvailability> executeRoutingEvaluator()
}
class uk.co.whitbread.hotelsearch.service.availabilitycache {
class AvailabilityCacheService {
-
}
}

}

@enduml