<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>uk.co.whitbread</groupId>
		<artifactId>digital-monorepo-library-parent</artifactId>
		<version>${revision}</version>
		<relativePath>../../../parents/library-parent/pom.xml</relativePath>
	</parent>

	<groupId>uk.co.whitbread.shared</groupId>
	<artifactId>commons-azure-email-service</artifactId>
	<version>${revision}</version>
	<packaging>jar</packaging>

	<name>commons-azure-email-service</name>
	<description>SDK for integration with Azure email service.</description>

	<properties>
		<wsdl.dir>${basedir}/src/main/resources/wsdl</wsdl.dir>
		<sonar.coverage.exclusions>
			**/config/**,**/api/**
		</sonar.coverage.exclusions>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.ws</groupId>
			<artifactId>spring-ws-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.xml.ws</groupId>
			<artifactId>jakarta.xml.ws-api</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.ws</groupId>
			<artifactId>jaxws-rt</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.ws</groupId>
			<artifactId>jaxws-ri</artifactId>
			<type>pom</type>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<!-- Library-specific: Generating classes from WSDL -->
			<plugin>
				<groupId>com.sun.xml.ws</groupId>
				<artifactId>jaxws-maven-plugin</artifactId>
				<version>4.0.3</version>
				<configuration>
					<wsdlDirectory>${wsdl.dir}</wsdlDirectory>
					<extension>true</extension>
				</configuration>
				<executions>
					<execution>
						<id>email-api-wsdl</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>wsimport</goal>
						</goals>
						<configuration>
							<wsdlFiles>
								<wsdlFile>${wsdl.dir}/ws.Azure.PTIEmailService_20220322.wsdl</wsdlFile>
							</wsdlFiles>
							<wsdlLocation>classpath:wsdl/ws.Azure.PTIEmailService_20220322.wsdl</wsdlLocation>
							<packageName>uk.co.whitbread.shared.azureemail.api</packageName>
							<bindingFiles>
								<bindingFile>${wsdl.dir}/../datetime-bindings.xjb</bindingFile>
							</bindingFiles>
							<extension>true</extension>
							<vmArgs>
								<vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
							</vmArgs>
							<args>
								<arg>-verbose</arg>
							</args>
						</configuration>
					</execution>
					<execution>
						<id>generic-email-wsdl</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>wsimport</goal>
						</goals>
						<configuration>
							<wsdlFiles>
								<wsdlFile>${wsdl.dir}/ws.Azure.EmailService_20220705.wsdl</wsdlFile>
							</wsdlFiles>
							<wsdlLocation>classpath:wsdl/ws.Azure.EmailService_20220705.wsdl</wsdlLocation>
							<packageName>uk.co.whitbread.shared.azureemail.genericEmail.api</packageName>
							<bindingFiles>
								<bindingFile>${wsdl.dir}/../datetime-bindings.xjb</bindingFile>
							</bindingFiles>
							<extension>true</extension>
							<vmArgs>
								<vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
							</vmArgs>
							<args>
								<arg>-verbose</arg>
							</args>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
