package uk.co.whitbread.rules.agent.domain.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum ErrorCode {
  DIGITAL_NOT_AMENDABLE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 207),
  DIGITAL_NO_LANGUAGE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 208),
  DIGITAL_CHANNEL_RULE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 209),
  DIGITAL_CHANNEL_RULE_SOURCE_ID_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 210),
  DIGITAL_MAX_ROOM_OCCUPANCY_RULE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 211),
  DIGITAL_MAX_NIGHT_RULE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 212),
  DIGITAL_MAX_ROOM_RULE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 213),
  DIGITAL_MAX_ARRIVAL_DATE_RULE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 214),
  DIGITAL_NO_BUSINESS_ALLOWANCE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 215),
  DIGITAL_RATE_SUPPRESSION_RULE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 216),
  DIGITAL_ROOM_SUBSTITUTION_RULE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 217),
  DIGITAL_VAT_RULE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 218),
  DIGITAL_NO_BASE_RATE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 219);

  private final String message;
  private final int code;

  public static class Constants {

    public static final String INTERNAL_SERVER_EXCEPTION = "internal.server.exception";

    private Constants() {}
  }

}
