package uk.co.whitbread.reservation.infrastructure.rest.controller.reservation.model.in;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotEmpty;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
@Schema(requiredProperties = {"basketReference", "customerAccountId"})
public class LinkReservationToLeisureCustomerRequestDto {

  @NotEmpty
  @Schema(description = "Digital basket reference", example = "BKS-1234a567-qq7b-2024-123s-aa5ssbn557gh")
  private String basketReference;

  @NotEmpty
  @Valid
  @Schema(description = "Customer Account ID generated by CDH")
  private String customerAccountId;
}
