#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Fri Jun 03 15:18:10 BST 2016
apiSecret=04c1dcabd8209741b58c2a9a2ea6f7892fa82b0e62bf17ce79491704f0bdb7bd
