FROM 327347623470.dkr.ecr.eu-west-1.amazonaws.com/whitbreaddigital/java-jdk-opera:25.0.2_10-jre-alpine-base-2cf500f

ARG APP_NAME
ARG APP_VERSION
ARG JAVA_OPTS
ARG JAR_FILE="${APP_NAME}-${APP_VERSION}.jar"

VOLUME /tmp
ADD $JAR_FILE app.jar

CMD exec java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /app.jar