@startuml
class PibaMultiTetheredGuidResponse {
  #pibaTetheredGuidResponses : List<PibaTetheredGuidResponse>
}
class PibaTetheredGuidResponse {
    #companyId : String
    #employeeId: String
    #tetheredGuid:List<String>
    #scheme : String
}
@enduml