export enum ActionContextKeys {
  MULTI_HOTEL_AVAILABILITIES = 'MULTI_HOTEL_AVAILABILITIES',
  MULTI_HOTEL_INFORMATION = 'MULTI_HOTEL_INFORMATION',
  HOTEL_AVAILABILITY = 'HOTEL_AVAILABILITIES',
  RATE_INFORMATION = 'RATE_INFORMATION',
  ROOM_TYPE_INFORMATION = 'ROOM_TYPE_INFORMATION',
  ROOM_CLASS_CONFIG = 'ROOM_CLASS_CONFIG'
}
