schema {
    query: Query
}

type Query {
    donations(bookingFlowCriteria: BookingFlowCriteria!): DonationResponse
}

input BookingFlowCriteria {
    bookingChannel:String
    hotelId: String!
    language: String!
    country: String!
    rateCode: String!
}

type DonationResponse {
    name: String
    description: String
    informationBox: String
    imageSrc: String
    donationPackages: [DonationPackage]
}

type DonationPackage {
    code: String
    unitPrice: Float
    currency: String
}