package uk.co.whitbread.booking.domain.model.exceptions;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * Errors map.The Error's message is used by the globalTxtErrTemplate.
 */

@RequiredArgsConstructor
@Getter
public enum ErrorCode {
  DIGITAL_INVALID_AUTHORIZATION_TOKEN_EXCEPTION(Constants.INVALID_AUTHORIZATION_TOKEN, 173),
  DIGITAL_CANCEL_BOOKING_INVALID_AUTHORIZATION_EXCEPTION(Constants.INVALID_AUTHORIZATION_TOKEN, 174),
  DIGITAL_GET_TOKEN_EXCEPTION(Constants.INVALID_AUTHORIZATION_TOKEN, 175),
  DIGITAL_GET_ACCESS_LEVEL_EXCEPTION(Constants.INVALID_AUTHORIZATION_TOKEN, 176),
  DIGITAL_GET_OPERA_BOOKING_EXCEPTION(Constants.BAD_REQUEST, 177),

  BOOKING_INVOICE_INVALID_REQUEST(Constants.BAD_REQUEST, 302),
  BOOKING_INVOICE_NOT_FOUND(Constants.BAD_REQUEST, 303),
  BOOKING_INVOICE_UNSUPPORTED_CHANNEL(Constants.BAD_REQUEST, 304),
  BOOKING_INVOICE_CDH_EMPTY_RESPONSE(Constants.INTERNAL_SERVER_EXCEPTION, 305),

  PDF_RENDER_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 301),

  SEND_BOOKING_EMAL_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 505),
  RESEND_BOOKING_INVOICE_EMAIL_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 506),
  MIGRATION_STATUS_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 507),
  MIGRATION_BULK_HOTELS_STATUS_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 508),
  CUSTOMER_BOOKING_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 509),
  ACCOUNTS_BOOKING_INFO_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 510),
  ACCOUNTS_BOOKING_CANCEL_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 511),
  CDH_EMPTY_RESPONSE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 543),

  AWS_S3_UPLOAD_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 2000);

  private final String message;
  private final int code;

  public static class Constants {

    public static final String INTERNAL_SERVER_EXCEPTION = "internal.server.exception";
    public static final String INVALID_AUTHORIZATION_TOKEN = "invalid.authorization.token";
    public static final String BAD_REQUEST = "bad.request";

    private Constants() {
    }
  }
}