server:
  port: 9100
  servlet:
    contextPath: "/ohip/"
  shutdown: graceful

swagger:
  api:
    version: "@project.version@"

info:
  build:
    groupId: "@project.groupId@"
    artifact: "@project.artifactId@"
    description: "@project.description@"
    version: "@project.version@"
    git:
      originUrl: "@git.remote.origin.url@"
      branch: "@git.branch@"
      commit:
        id: "@git.commit.id@"
        time: "@git.commit.time@"
        message: "@git.commit.message.short@"

io:
  getunleash:
    app-name: "${spring.application.name}"
    instance-id: "@project.version@"
    environment: "${UNLEASH_ENVIRONMENT}"
    api-url: "${UNLEASH_URL}"
    api-token: "${UNLEASH_TOKEN}"
    send-metrics-connect-timeout: "${UNLEASH_SEND_METRICS_CONNECT_TIMEOUT:5s}"
    send-metrics-read-timeout: "${UNLEASH_SEND_METRICS_READ_TIMEOUT:5s}"
    send-metrics-interval: "${UNLEASH_SEND_METRICS_INTERVAL:60s}"

springdoc:
  show-actuator: true
  writer-with-order-by-keys: true

management:
  tracing:
    propagation:
      type: w3c
    baggage:
      correlation:
        fields:
          - x-amzn-trace-id
          - flow-code
          - wb-session-id
        enabled: true
      enabled: true
      remote-fields:
        - x-amzn-trace-id
        - flow-code
        - wb-session-id
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, caches, metrics, prometheus
  metrics:
    enable:
      all: true
    distribution:
      percentiles:
        http.server.requests: [ 0.95, 0.99 ]
      percentiles-histogram:
        http.server.requests: true
      maximum-expected-value:
        http.server.requests: 2000ms

  endpoint:
    health:
      probes:
        enabled: true
  health:
    redis:
      enabled: false
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  configuration:
    debug:
      enabled: true
      exclusions:
        - .*/actuator.*
    mask:
      enabled: true
      fields:
        - Authorization
        - phoneNumber
        - cardNumber
        - cardId
        - cardNo
        - bankAccount
        - visaNumber
        - chargeCardNumber
        - cardHolderName
        - nameOnCard
        - personName
        - name
        - fullName
        - firstName
        - lastName
        - givenName
        - middleName
        - surname
        - surName
        - address
        - telephone
        - email
        - emailAddress
        - contactValue
        - addressLine
        - idNumber
        - companyName
        - expirationDate
        - postalCode
        - mobile
        - landline
        - addressLine1
        - addressLine2
        - addressLine3
        - addressLine4
        - passportNumber
        - line1
        - line2
        - line3
        - line4
  pattern:
    # Logging pattern containing traceId and spanId; no longer provided through Sleuth by default
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    brave: WARN
    org.springframework.cache: warn
    io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor: ERROR
    io:
      getunleash: TRACE

spring:
  cache:
    type: ${CACHE_TYPE:redis}
    redis:
      key-prefix: "Ohip-Adapter-Service"
      use-key-prefix: true
  data:
    redis:
      ssl:
        enabled: true
      cluster:
        max-redirects: 5
        nodes: ${REDIS_ENDPOINT:localhost:6379}
      client-type: lettuce
      lettuce:
        cluster:
          refresh:
            period: 5m
            adaptive: true
  lifecycle:
    timeout-per-shutdown-phase: 1m

config:
  httpClient:
    connectionTimeout: ${HTTP_CONNECTION_TIMEOUT:10000}
    responseTimeout: ${HTTP_RESPONSE_TIMEOUT:30}
  service:
    token-service:
      host: ${TOKEN_SERVICE_HOST:http://localhost:9136}
      tokenEndpoint: ${TOKEN_SERVICE_TOKEN_ENDPOINT:/v1/tokens/opera/access-token}
    ohip:
      isClientCredentialsEnabled: ${ENABLE_CLIENT_CREDENTIALS:false}
      wireTapAccessToken: ${WIRE_TAP_ACCESS_TOKEN:false}
      host: ${OPERA_HOST}
      authEndpoint: ${OPERA_AUTH_ENDPOINT:oauth/v1/tokens}
      appKey: ${OPERA_APP_KEY}
      enterpriseId: ${ENTERPRISE_ID}
      clientId: ${OPERA_CLIENT_ID}
      clientSecret: ${OPERA_CLIENT_SECRET}
      username: ${OPERA_USERNAME}
      password: ${OPERA_PASSWORD}
      hubId: ${OPERA_HUB_ID:DFLT_WHBOC001}
      defaultHotelId: ${DEFAULT_HOTEL_ID:MANOLD}
      scope: ${OPERA_SCOPE:}
      defaultProfileId: 44236
      contextId: WB_DIGITAL
      amadeusDistributionContextId: "Amadeus_GDS"
      travelPortDistributionContextId: "Travelport_GDS"
      guaranteeCode: O9ONHOLD
      maxConcurrency: 1
      nonDigitalThreadSleep: 10000
      updateCcAgentIdThreadSleep: 3000
      fetchReservationThreadSleep: ${FETCH_RESERVATION_THREAD_SLEEP:1000}
      maxAvailabilityConcurrency: 20
      maxRequestedDays: 90
      maxRequestedDaysRateInfo: 21
      confirmationGuaranteeCode: CC
      depositReceivedGuaranteeCode: DRV
      nonGuaranteeCode: NON
      companyGuaranteeCode: CO
      defaultPaymentMethod: CA
      defaultPaymentMethodDs: DS
      folio: 1
      depositCashierId: 463 #464 for SIT env
      cotSpecialRequest: COTR
      defaultMarketCode: OTH
      tokenRefreshClockSkew: ${OPERA_TOKEN_REFRESH_SKEW:15}
      nonDigitalPaymentHotels: ${NON_DIGITAL_PAYMENT_HOTELS:}
      availabilityEndpoint: "/par/v1/hotels/{hotelId}/availability"
      rateInfoEndpoint: "/rsv/v1/hotels/{hotelId}/reservations/rateInfo"
      reservationEndpoint: "/rsv/v1/hotels/{hotelId}/reservations"
      reservationIdEndpoint: "/rsv/v1/hotels/{hotelId}/reservations/{reservationId}"
      cancellationPoliciesEndpoint: "/rsv/v1/hotels/{hotelId}/reservations/{reservationId}/cancellationPolicies"
      cancellationEndpoint: "/rsv/v1/hotels/{hotelId}/reservations/{reservationId}/cancellations"
      activityLogEndpoint: "/rsv/v1/hotels/{hotelId}/reservations/activityLog"
      packagesEndpoint: "/rtp/v1/packages"
      enterpriseEndpoint: "/ent/config/v1/hotels/{hotelId}"
      depositFoliosEndpoint: "/csh/v1/hotels/{hotelId}/reservations/{reservationId}/depositFolios"
      packageGroupsEndpoint: "/rtp/v1/hotels/{hotelId}/packageGroups"
      ratePlansEndpoint: "/rtp/v1/ratePlans"
      ratePlanPromoEndpoint: "/rtp/v1/hotels/{hotelId}/ratePlans/{ratePlanCode}"
      promotionCodeEndpoint: "/rtp/v1/hotels/{hotelId}/promotionCodes"
      itemsInventoryEndpoint: "/inv/v1/hotels/{hotelId}/itemInventory"
      itemInventoryHoldEndpoint: "/inv/v1/hotels/{hotelId}/itemInventoryHold"
      hotelInventoryEndpoint: "/inv/v1/hotels/{hotelId}/hotelInventory"
      hotelInventoryStatisticsEndpoint: "/inv/v1/hotels/{hotelId}/inventoryStatistics"
      roomTypesEndpoint: "/rm/config/v1/hotels/{hotelId}/roomTypes"
      hotelConfigEndpoint: "/ent/config/v1/hotels/{hotelId}"
      hotelDetailsEndpoint: "/ent/config/v1/hotels/{hotelId}/hotelDetails"
      profilesEndpoint: "/crm/v1/profiles"
      companiesEndpoint: "/crm/v1/companies/{corporateId}"
      companiesByCompanyIdEndpoint: "/crm/v1/profiles/{companyId}"
      externalReservationEndpoint: "/rsv/v1/reservations"
      multiHotelAvaEndpoint: "/par/v1/availability"
      cancellationReasonsEndpoint: "/lov/v1/listOfValues/{name}"
      depositsEndpoint: "/csh/v1/hotels/{hotelId}/depositFolio"
      creditCardInfoEndpoint: "/fof/config/v1/creditCardInfo"
      cancelPoliciesEndpoint: "/rsv/config/v1/cancelpolicies"
      policySchedulesEndpoint: "/rsv/config/v1/hotels/{hotelId}/policyschedules"
      deleteReservationEndpoint: "/rsv/v1/hotels/{hotelId}/reservations/{reservationId}"
      vacantRoomsEndpoint: "/fof/v1/hotels/{HotelId}/rooms"
      roomsAssignmentEndpoint: "/fof/v1/hotels/{HotelId}/reservations/{ReservationId}/roomAssignments"
      addProfileEndpoint: "/rsv/v1/hotels/{HotelId}/reservations/{ReservationId}"
      checkInEndpoint: "/fof/v1/hotels/{HotelId}/reservations/{ReservationId}/checkIns"
      reservationGuestEndpoint: "/rsv/v1/hotels/{hotelId}/reservations/{reservationId}"
      routingInstructions: "/csh/v1/hotels/{HotelId}/reservations/{ReservationId}/routingInstructions"
      minimumRateAvaEndpoint: "/parext/v1/hotels/minimumRateAvailability"
      multiRoomRateAvaEndpoint: "/parext/v1/hotels/multiRoomRateAvailability"
      getHousekeeping: "/hsk/v1/hotels/{HotelId}/housekeepingOverview"
      negotiatedRatesByProfileIdEndpoint: "/rtp/v1/profiles/{profileId}/negotiatedRates"
      foliosEndPoint: "/csh/v1/hotels/{hotelId}/reservations/{reservationId}/folios"
      fileAttachmentEndpoint: "/med/config/v1/fileAttachments"
      preCheckInStatusEndpoint: "/rsv/v1/hotels/{hotelId}/reservations/{reservationId}/preCheckIn"
      deleteFileAttachmentEndpoint: "/rsv/v1/hotels/{hotelId}/reservations/{reservationId}/attachments/{attachmentId}"
      restrictionsByDateRangeEndpoint: "/par/v1/hotels/{hotelId}/restrictions"
      isUdf08Enabled: ${IS_UDF08_ENABLED:false}
      languages:
        "en": E
        "de": DE
      preferencesEndpoint: "/crm/config/v1/hotels/{HotelId}/preferences"
      restrictions:
        parallelThreads: ${RESTRICTIONS_PARALLEL_THREADS:5}
    rules-agent:
      host: ${RULES_AGENT_PROTOCOL:http://}${RULES_AGENT_HOST:localhost:9108}/v1/rules
      roomSubstitutionEndpoint: "/room-substitutions"
      bookingChannelInfo: "/channel-info"
      vatCodesEndpoint: "/vat-codes"
      channelSourceInfoEndpoint: "/source-info"
      baseRateEndpoint: "/baseRate"
      wbRoomTypes:
        - "DB"
        - "SB"
        - "FAM"
        - "DIS"
        - "TWIN"
      businessAllowanceEndpoint: "/allowances"


config-endpoints:
  reservation: rsv/v1/hotels
  availability: par/v1/hotels
  availabilityPathParam: availability
  reservationPathParam: reservations/rateInfo

packages:
  fetch-instructions:
    - Header
    - CalculatedPrice
    - Items
    - PostingRules
  donation-fetch-instructions:
    - Header
    - CalculatedPrice
    - Items
    - PostingRules
    - Details
  free-kids-breakfast:
    - BFADBF
    - MDP
  packageGroupsLimit: "50"

enterprise:
  fetch-instructions:
    - Dining

meals:
  config:
    "BDB":
      breakfast: true
      dinner: false
      meal-name: Premier Inn Breakfast
    "BMD":
      breakfast: true
      dinner: true
      meal-name: Meal Deal

availability:
  minimumAvailability: 10

hotels:
  noOfAllowedHotels: 200

integration-tests:
  feature-flag-overrides:
    enabled: ${INTEGRATION_TESTS_FEATURE_FLAG_OVERRIDES_ENABLED:false}

feature-flags:
  deposit-folio-post-after-disable-on-hold:
    key: "release_deposit_folio_post_after_disable_on_hold"
    fallback: false
  piba-booking:
    key: "release_pi_bb_ccui_distr_piba_booking"
    fallback: false
  fixed-Rate:
    key: "release_pi_bb_ccui_distr_fixed_rate"
    fallback: false
  capture-billing-address-bb:
    key: "release_bb_capture_billing_address"
    fallback: false
  no-duplicate-profile-creation-bb:
    key: "release_bb_no_duplicate_profile_creation"
    fallback: false
  no-duplicate-profile-creation-ccui:
    key: "release_ccui_no_duplicate_profile_creation"
    fallback: false
  no-duplicate-profile-creation-pi:
    key: "release_pi_no_duplicate_profile_creation"
    fallback: false
  availability-from-different-room-classes:
    key: "release_availability_from_different_room_classes"
    fallback: false
  flex-rate-strikethrough-bb:
    key: "release_bb_flex_rate_strikethrough"
    fallback: false
  use-token-service:
    key: "release_ohip_use_token_service"
    fallback: false
  mobile_accepts_ota_booking:
    key: "mobile_accepts_ota_booking"
    fallback: false
  distribution_booking_fee:
    key: "release_distr_booking_fee"
    fallback: false
  create-reservation-with-soft-bundles:
    key: "release_create_reservation_with_soft_bundles"
    fallback: false
  use-token-refresh-skew:
    key: "release_ohip_use_token_refresh_skew"
    fallback: false
  consumption-details-default-quantity:
    key: "consumption_details_default_quantity"
    fallback: false
  mobile-preRegistered-repurpose:
    key: "mobile_preRegistered_repurpose"
    fallback: false
  set-cnpBooking-alerts:
    key: "release_set_cnp_booking_alerts"
    fallback: false
  set-defaultPaymentMethod-DS:
    key: "release_set_default_payment_method_DS"
    fallback: false
  deposit-folio-creation-verification:
    key: "release_deposit_folio_creation_verification"
    fallback: false
promotion:
  promotionalRate: ${PROMOTIONAL_RATE:}
  promotionalPackage: ${PROMOTIONAL_PACKAGE:}

threadpool:
  availability:
    coreSize: ${AVAILABILITY_EXECUTOR_CORE_SIZE:8}
    maxSize: ${AVAILABILITY_EXECUTOR_MAX_SIZE:16}
    queueSize: ${AVAILABILITY_EXECUTOR_QUEUE_SIZE:50}
  apiLimits:
    coreSize: ${API_LIMITS_EXECUTOR_CORE_SIZE:8}
    maxSize: ${API_LIMITS_EXECUTOR_MAX_SIZE:16}
    queueSize: ${API_LIMITS_EXECUTOR_QUEUE_SIZE:50}

---
spring:
  config:
    activate:
      on-profile:
        - opera-perf
        - opera-dev
        - opera-qa
        - local

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

---
spring:
  config:
    activate:
      on-profile:
        - local

logging:
  configuration:
    logger: default

io:
  getunleash:
    app-name: "${spring.application.name}"
    instance-id: "@project.version@"
    environment: local
    api-url: 'http://localhost:4242/api'
    api-token: 'dummy-value'

config:
  service:
    ohip:
      wire-tap-access-token: true
