@startuml
'https://plantuml.com/class-diagram

package uk.co.whitbread.availabilitycacheservice.infrastructure.model{
class SearchCriteria
enum SortType
enum CountryCode
enum LanguageCode
}

package uk.co.whitbread.availabilitycacheservice.domain.validation{
class HotelCodeValidator
}

package uk.co.whitbread.availabilitycacheservice.domain.ports.primary{
interface HotelCodeConstraint
}

package jakarta.validation {
interface ConstraintValidator
}

class SearchCriteria {
- int[] hotelCodes
- String arrival
- String departure
- int[] adults
- int[] children
- boolean cot
- String type
- int rooms
- SortType sort
- CountryCode country
- LanguageCode language
}

class HotelCodeValidator {
+ boolean : checkHotelCodeForSortByDistance()
+ boolean : checkHotelCodeForSortByPrice()
}

interface HotelCodeConstraint extends ConstraintValidator
class HotelCodeValidator implements HotelCodeConstraint

SearchCriteria --> SortType
SearchCriteria --> CountryCode
SearchCriteria --> LanguageCode

enum SortType {
DISTANCE
PRICE
}
enum CountryCode{
GB
DE
}
enum LanguageCode{
EN
DE
}

@enduml