@startuml
'https://plantuml.com/class-diagram

package uk.co.whitbread.availabilitycacheservice.infrastructure.rest.response {
class LeastPricedHotelsDto
class LeastPricedHotelDto
class PriceDto
}
class LeastPricedHotelsDto {
- List<LeastPricedHotelDto> leastPricedHotels
}
class LeastPricedHotelDto {
- String placeId
- String hotelCode
- PriceDto leastPrice
}
class PriceDto {
- BigDecimal amount
- String currency
}

LeastPricedHotelsDto --> LeastPricedHotelDto
LeastPricedHotelDto --> PriceDto

@enduml