//
//  DoorKeyInteractor.swift
//  PremierInn
//
//
//  Created Georgios Aikaterinakis on 21/09/2021.
//  Copyright © 2021 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import Foundation
import SimpleNetwork

class DoorKeyInteractor {
    private var reservationDetails: ReservationDetails?
    private var deviceId: String?
    private var authenticationCode: String?

    private let requestsManager: DoorKeyInteractorRequestsManager

    init(reservationDetails: ReservationDetails) {
        self.requestsManager = RequestsManager()

        self.reservationDetails = reservationDetails
//        deviceId = KeyManager.shared.deviceID
    }
}

extension RequestsManager: DoorKeyInteractorRequestsManager {}

extension DoorKeyInteractor: DoorKeyInteractorProtocol {
    var viewModel: DoorKeyViewModel? {
        nil // DoorKeyViewModel(
    }

    func getKey() {
//        guard let reservationDetails = reservationDetails else { return }
//        guard let deviceId = KeyManager.shared.deviceID else { return }
//
//        requestsManager.getDoorKey(reservationDetails: reservationDetails, deviceId: deviceId, authenticationCode: authenticationCode) { keyId, error in
//
//            guard error != nil else {
//
//                print(error.debugDescription)
//                return
//            }
//
//            guard let keyId = keyId else { return }
//
//            KeyManager.shared.fetchKey(with: keyId)
//        }
    }
}
