//
//  DoorKeyPresenter.swift
//  PremierInn
//
//
//  Created Georgios Aikaterinakis on 21/09/2021.
//  Copyright © 2021 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import Foundation

class DoorKeyPresenter {
    weak var view: DoorKeyViewProtocol?

    var interactor: DoorKeyInteractorProtocol?
    var router: DoorKeyRouterProtocol?
}

extension DoorKeyPresenter: DoorKeyViewEventHandler {
    func viewIsReady() {
        guard let viewModel = interactor?.viewModel else { return }
        view?.update(with: viewModel)
    }

    func getKeyDidTap() {
        interactor?.getKey()
    }
}
