//
//  DoorKeyModule.swift
//  PremierInn
//
//  Created Georgios Aikaterinakis on 21/09/2021.
//  Copyright © 2021 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit
import SimpleNetwork

enum DoorKeyModule {
    static func build(reservationDetails: ReservationDetails) -> UIViewController {
        let controller = DoorKeyView()

        controller.eventHandler = {
            let presenter = DoorKeyPresenter()

            let router = DoorKeyRouter()
            router.view = controller

            let interactor = DoorKeyInteractor(reservationDetails: reservationDetails)

            presenter.view = controller
            presenter.interactor = interactor
            presenter.router = router

            return presenter
        }()

        return controller
    }
}

protocol DoorKeyViewModel {
    var reservationDetails: ReservationDetails { get }
}

protocol DoorKeyViewProtocol: AnyObject {
    func update(with viewModel: DoorKeyViewModel)
}

protocol DoorKeyViewEventHandler {
    func viewIsReady()
    func getKeyDidTap()
}

protocol DoorKeyInteractorProtocol {
    var viewModel: DoorKeyViewModel? { get }

    func getKey()
}

protocol DoorKeyRouterProtocol {
}

protocol DoorKeyInteractorRequestsManager {
    func getDoorKey(
        reservationDetails: ReservationDetails,
        deviceId: String,
        authenticationCode: String?,
        completion: @escaping (_ keyId: String?, _ error: Error?) -> Void
    )
}
