//
//  DoorKeyView.swift
//  PremierInn
//
//  V is for "View" 🌁, and "Vote" 🙋‍♂️
//
//  Created Georgios Aikaterinakis on 21/09/2021.
//  Copyright © 2021 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit

class DoorKeyView: UIViewController {
    @IBOutlet weak var cardView: UIView!

    var eventHandler: DoorKeyViewEventHandler?

    init() {
        super.init(nibName: String(describing: DoorKeyView.self), bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func viewDidLoad() {
        super.viewDidLoad()

        cardView.backgroundColor = .BasePurple

        cardView.layer.shadowColor = UIColor.black.cgColor
        cardView.layer.shadowOpacity = 1
        cardView.layer.shadowOffset = .zero
        cardView.layer.shadowRadius = 10

        let getKeyTapRecognizer = UITapGestureRecognizer(target: self, action: #selector(getKeyTapped))
        view.addGestureRecognizer(getKeyTapRecognizer)

        eventHandler?.viewIsReady()
    }

    @objc func getKeyTapped() {
        eventHandler?.getKeyDidTap()
    }
}

extension DoorKeyView: DoorKeyViewProtocol {
    func update(with viewModel: DoorKeyViewModel) {
    }
}
