//
//  DoorKeyRouter.swift
//  PremierInn
//
//  R is for "Router" 🚦, and "Rancid" 😷
//
//  Created Georgios Aikaterinakis on 21/09/2021.
//  Copyright © 2021 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit

class DoorKeyRouter {
    var view: UIViewController?
}

extension DoorKeyRouter: DoorKeyRouterProtocol {
}
