export const styles = {
  passwordContainerWrap: {
    p: '0 1.5rem 2.5rem',
  },
  formContainerStyle: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    maxWidth: '27.625rem',
    margin: '1.5rem auto 0',
  },
  titleStyles: {
    color: 'darkGrey1',
    textAlign: 'center',
    fontSize: { mobile: '1.4375rem', lg: '1.625rem' },
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: '120%',
  },
  descriptionStyles: {
    color: 'darkGrey2',
    textAlign: 'center',
    fontSize: '0.875rem',
    fontWeight: '400',
    lineHeight: '1.5rem',
    maxW: '34.125rem',
    m: '1.5rem auto 1.5rem',
  },
  timerStyles: {
    fontSize: '0.8125rem',
    fontWeight: '600',
    mt: '0.5rem',
    mb: '0.5rem',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 'sm',
  },
  timeStyles: {
    color: 'primary',
    fontSize: '1rem',
  },
  expiredStyles: {
    color: 'alert',
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: '600',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 'sm',
    mt: '0.5rem',
    mb: '1rem',
  },
  passwordWrapStyles: {
    w: '100%',
    p: '1rem',
    maxH: '63px',
    borderRadius: '4px',
    border: '1px solid #979797',
    background: 'lightGrey5',
    justifyContent: 'space-between',
  },
  passwordStyles: {
    w: '90%',
    textAlign: 'center',
    letterSpacing: '0.3em',
    fontWeight: '600',
    fontSize: { mobile: '1.25rem', lg: '1.625rem' },
  },
  copyIcon: {
    cursor: 'pointer',
  },
  resendTextStyles: {
    color: 'darkGrey1',
    textAlign: 'center',
    fontSize: '0.8125rem',
  },
  showResendMobile: {
    display: { mobile: 'block', md: 'none' },
  },
  showResendDesktop: {
    display: { mobile: 'none', md: 'block' },
  },
  resendStyles: {
    color: 'tertiary',
    fontSize: '0.875rem',
    fontWeight: '600',
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
    textDecoration: 'underline',
    ml: '0.25rem',
    lineHeight: '1rem',
    cursor: 'pointer',
    textUnderlineOffset: '1px',
    textUnderlinePosition: 'from-font',
  },
  submitButton: {
    fontSize: '1rem',
    m: '1.5rem auto',
    w: '100%',
  },
  downloadTestIconStyles: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 'sm',
  },
  downloadTextStyles: {
    color: 'baseWhite',
    fontSize: '1.125rem',
    fontWeight: '600',
  },
  downloadFileWrapStyles: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 'sm',
    mb: '1.5rem',
    color: 'success',
  },
  downloadFileTextStyles: {
    textAlign: 'center',
    fontSize: '1.25rem',
    fontWeight: '700',
  },
  copiedTextWrap: {
    w: '20%',
    display: 'flex',
    justifyContent: 'flex-end',
  },
  copiedText: {
    fontSize: 'sm',
    color: 'green.500',
  },
};
