<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>uk.co.whitbread.shared</groupId>
    <artifactId>bart-shared-lib</artifactId>
    <version>${revision}</version>

    <parent>
        <groupId>uk.co.whitbread</groupId>
        <artifactId>digital-monorepo-library-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../../../parents/library-parent/pom.xml</relativePath>
    </parent>

    <properties>
        <wsdl.dir>${basedir}/src/main/resources/wsdl</wsdl.dir>
        <xsd.dir>${basedir}/src/main/resources/xsd</xsd.dir>
        <cxf-xjc-plugin.version>4.0.0</cxf-xjc-plugin.version>
        <cxf-codegen-plugin.version>4.2.0</cxf-codegen-plugin.version>
        <build-helper-maven-plugin.version>3.6.0</build-helper-maven-plugin.version>
        <sonar.exclusions>
            **/**
        </sonar.exclusions>
    </properties>

    <build>
        <plugins>
            <!--Generating classes from xsd-->
            <plugin>
                <groupId>org.apache.cxf</groupId>
                <artifactId>cxf-xjc-plugin</artifactId>
                <version>${cxf-xjc-plugin.version}</version>
                <goals>
                    <goal>xsdtojava</goal>
                </goals>
                <configuration>
                    <extensions>
                        <extension>org.apache.cxf.xjcplugins:cxf-xjc-dv:${cxf-xjc-plugin.version}</extension>
                    </extensions>
                </configuration>
                <executions>
                    <execution>
                        <id>cxf-xsd</id>
                        <goals>
                            <goal>xsdtojava</goal>
                        </goals>
                        <configuration>
                            <sourceRoot>${basedir}/target/generated-sources/xjc</sourceRoot>
                            <xsdOptions>
                                <xsdOption>
                                    <xsd>${xsd.dir}/bart-common.xsd</xsd>
                                    <packagename>uk.co.whitbread.bart.common</packagename>
                                    <bindingFile>${xsd.dir}/../datetime-bindings.xjb</bindingFile>
                                </xsdOption>
                            </xsdOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!--Generating classes from WSDL-->
            <plugin>
                <groupId>org.apache.cxf</groupId>
                <artifactId>cxf-codegen-plugin</artifactId>
                <version>${cxf-codegen-plugin.version}</version>
                <executions>
                    <execution>
                        <id>cxf-wsdl</id>
                        <goals>
                            <goal>wsdl2java</goal>
                        </goals>
                        <configuration>
                            <sourceRoot>${basedir}/target/generated-sources/cxf</sourceRoot>
                            <wsdlOptions>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.Booking.BookingService3_2022_12_14.wsdl</wsdl>
                                    <wsdlLocation>classpath:wsdl/ws.Booking.BookingService3_2022_12_14.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.booking.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.CheckIn.CheckInService_20190329.wsdl</wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.CheckIn.CheckInService_20190329.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.checkin.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.CancelBooking.CancelBookingService_20190329.wsdl</wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.CancelBooking.CancelBookingService_20190329.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.cancellation.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.CheckBooking.CheckBookingService_20190329.wsdl</wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.CheckBooking.CheckBookingService_20190329.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.checkbookingconfirmation.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.RegisteredGuest.RegisteredGuestService_20190329.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.RegisteredGuest.RegisteredGuestService_20190329.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.registeredguest.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.RegisteredGuest.GuestDetailsService_20210427.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.RegisteredGuest.GuestDetailsService_20210427.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.registeredguest.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.RegisteredGuest.PastStaysService_20190329.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.RegisteredGuest.PastStaysService_20190329.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.paststays.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.RegisteredGuest.FutureStaysService_20190329.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.RegisteredGuest.FutureStaysService_20190329.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.registeredguest.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.UnifiedSystems.UnifiedSystemsDataService_20190329.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.UnifiedSystems.UnifiedSystemsDataService_20190329.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.unified.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.Corporate.RegistrationService_20161123.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Corporate.RegistrationService_20161123.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <!--<extraarg>uk.co.whitbread.bart.cbt.register.api</extraarg>-->
                                        <extraarg>cbt.register.bart.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/etframework_20161123.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/etframework_20161123.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>exacttarget.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.Booking.CardService_20190329.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Booking.CardService_20190329.wsdl.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.booking.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.Corporate.MPIBBService_20170131.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Corporate.MPIBBService_20170131.wsdl.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.business.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.Corporate.UtilityService_20170301.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Corporate.UtilityService_20170301.wsdl.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.business.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.Corporate.SelfRegistrationService_20170522.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Corporate.SelfRegistrationService_20170522.wsdl.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.selfregister.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.Corporate.DashboardService_20170118.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Corporate.DashboardService_20170118.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.business.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.ElectronicMagazine.ElectronicMagazineService2015_20190329.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.ElectronicMagazine.ElectronicMagazineService2015_20190329.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.marketing.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.Corporate.GuestDetailsService_20210427.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Corporate.GuestDetailsService_20210427.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.business.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.Corporate.CompanyService_20170706.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Corporate.CompanyService_20170706.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.business.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.Corporate.ProfileService_20170822.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Corporate.ProfileService_20170822.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.business.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.Corporate.BusinessAccountService_24_06_2020.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Corporate.BusinessAccountService_24_06_2020.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.business.corporate.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.Business.AccountService_20171215.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Business.AccountService_20171215.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.business.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.Corporate.AccountService_20171215.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Corporate.AccountService_20171215.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.business.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.Corporate.ReportingService_20171215.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Corporate.ReportingService_20171215.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.businessbooker.reporting.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.Corporate.SalesService_20171215.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Corporate.SalesService_20171215.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.businessbooker.sales.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.InRoomApp.InRoomAppService_20200423.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.InRoomApp.InRoomAppService_20200423.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.hub.inroomapp.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.Corporate.FindEmployeeService_24_08_2020.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Corporate.FindEmployeeService_24_08_2020.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.business.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.RegisteredGuest.Auth0Service_20220110.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.RegisteredGuest.Auth0Service_20220110.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.auth0.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${wsdl.dir}/ws.Corporate.Auth0Service_20220110.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Corporate.Auth0Service_20220110.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.bart.business.auth0.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>
                                        ${wsdl.dir}/ws.Azure.PTIEmailService_20220322.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Azure.PTIEmailService_20220322.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.azure.email.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>
                                        ${wsdl.dir}/ws.Azure.EmailService_20220705.wsdl
                                    </wsdl>
                                    <wsdlLocation>
                                        classpath:wsdl/ws.Azure.EmailService_20220705.wsdl
                                    </wsdlLocation>
                                    <extraargs>
                                        <extraarg>-verbose</extraarg>
                                        <extraarg>-autoNameResolution</extraarg>
                                        <extraarg>-p</extraarg>
                                        <extraarg>uk.co.whitbread.azure.genericEmail.api</extraarg>
                                        <extraarg>-xjc-b,${wsdl.dir}/../datetime-bindings.xjb</extraarg>
                                    </extraargs>
                                </wsdlOption>
                            </wsdlOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>${build-helper-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>target/generated-sources/xjc</source>
                                <source>target/generated-sources/cxf</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>uk.co.whitbread.shared</groupId>
            <artifactId>commons-exceptions</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web-services</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.sun.xml.ws</groupId>
            <artifactId>jaxws-rt</artifactId>
            <type>pom</type>
        </dependency>

        <dependency>
            <groupId>com.github.dozermapper</groupId>
            <artifactId>dozer-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.dozermapper</groupId>
            <artifactId>dozer-spring4</artifactId>
        </dependency>

    </dependencies>
</project>
