package uk.co.whitbread.content.domain.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * Errors map.The Error's message is used by the globalTxtErrTemplate.
 */

@RequiredArgsConstructor
@Getter
public enum ErrorCode {
  DIGITAL_LABEL_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 1),
  DIGITAL_MULTIPLE_LABELS_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 2),
  DIGITAL_HOTEL_SLUG_NOT_FOUND_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 3),
  DIGITAL_INVALID_CATEGORY_EXCEPTION(Constants.VALIDATION_ERROR_FORM, 4),
  DIGITAL_INVALID_CATEGORY_TO_STRING_EXCEPTION(Constants.VALIDATION_ERROR_FORM, 5),
  DIGITAL_SEO_MISSING_REQUIRED_FIELD(Constants.VALIDATION_ERROR_FORM, 6),
  DIGITAL_SEO_MISSING_HOTEL_ID_REQUIRED_FIELD(Constants.VALIDATION_ERROR_FORM, 7),
  DIGITAL_SEO_MISSING_BOOKING_FLOW_ID(Constants.VALIDATION_ERROR_FORM, 8),
  DIGITAL_SEO_UNSUPORTED_PAGE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 9),
  DIGITAL_EXTRAS_LABEL_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 224),
  DIGITAL_APPS_HOMEPAGE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 248),
  DIGITAL_APPS_HOMEPAGE_SUBCHANNEL_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 249),
  DIGITAL_PROMO_STRATEGY_CONFIGURATION_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 298),
  DIGITAL_PROMO_STRATEGY_NOT_FOUND_EXCEPTION(Constants.PROMOTION_STRATEGY_NOT_FOUND, 299),

  TRIPADVISOR_HOTEL_INFORMATION_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 500),
  SNOWDROP_HOTEL_SEARCH_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 512),

  AEM_BOOKING_INFORMATION_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 800),
  AEM_RATE_INFORMATION_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 801),
  AEM_BOOKING_INFORMATION_HOTEL_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 802),
  AEM_RATES_OVERRIDE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 803),
  AEM_LABELS_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 804),
  AEM_ALL_HOTELS_DETAILS_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 805),
  AEM_INDEX_HEADER_DATA_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 806),
  AEM_SEARCH_RESULT_DATA_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 807),
  AEM_HOTELS_INFORMATION_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 808),
  AEM_ROOM_TYPE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 809),
  AEM_MEALS_INFO_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 810),
  AEM_FOOTER_INFO_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 811),
  AEM_COUNTIES_INFO_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 812),
  AEM_COOKIE_POLICIES_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 813),
  AEM_BUSINESS_NOTE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 814),
  AEM_GET_LABELS_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 815),
  AEM_LAYOUT_INFO_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 816),
  AEM_HEADER_CONTENT_INFO_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 817),
  AEM_COMMON_ICONS_INFO_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 818),
  AEM_CARD_MANAGEMENT_INFO_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 819),
  AEM_PAGE_DATA_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 820),
  AEM_SEARCH_RULES_DATA_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 821),
  AEM_ROOM_CLASS_CONFIG_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 822),
  AEM_DLP_INFORMATION_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 823),
  AEM_GLOBAL_CONFIG_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 824),
  AEM_APPS_HOMEPAGE_CONFIG_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 825),
  AEM_PRICE_FINDER_CONFIG_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 826),;

  private final String message;
  private final int code;

  private static class Constants {
    public static final String INTERNAL_SERVER_EXCEPTION = "internal.server.exception";
    public static final String VALIDATION_ERROR_FORM = "validation.error.form";
    public static final String PROMOTION_STRATEGY_NOT_FOUND = "promotion.strategy.not.found";
  }
}