version: "3.8"
services:
  redis-single-node-cluster:
    image: docker.io/bitnami/redis-cluster:7.0
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_REPLICAS=0'
      - 'REDIS_NODES=127.0.0.1 127.0.0.1 127.0.0.1'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
    ports:
      - '6379:6379'
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '9999:5432'
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--username=postgres",
          "--host=127.0.0.1",
          "--port=5432"
        ]
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 10s
  unleash:
    image: unleashorg/unleash-server:latest
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres/postgres"
      # Disable SSL for database connections.
      DATABASE_SSL: "false"
      # Changing log levels:
      LOG_LEVEL: "warn"
      INIT_CLIENT_API_TOKENS: "default:development.unleash-insecure-api-token,default:production.unleash-insecure-api-token"
      ENABLE_OAS: true
    depends_on:
      postgres:
        condition: service_healthy
    command: [ "node", "index.js" ]
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
  edge:
    image: unleashorg/unleash-edge:latest
    ports:
      - "3063:3063"
    command:
      - edge
    environment:
      TOKENS: "default:development.unleash-insecure-api-token,default:production.unleash-insecure-api-token"
      UPSTREAM_URL: "http://unleash:4242"
    depends_on:
      unleash:
        condition: service_healthy
    healthcheck:
      test: unleash-edge health
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
