<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>uk.co.whitbread</groupId>
    <artifactId>digital-monorepo-service-parent</artifactId>
    <version>${revision}</version>
    <relativePath>../../../parents/service-parent/pom.xml</relativePath>
  </parent>

  <artifactId>availability-business-events-service-opera</artifactId>
  <packaging>jar</packaging>

  <name>availability-business-events-service-opera</name>
  <description>Availability business events Microservice</description>

  <properties>
    <sonar.coverage.exclusions>
      **/domain/model/**,
      **/domain/ports/**,
      **/exception/**,
      **/properties/**,
      **/infrastructure/config/**,
      **/infrastructure/adapters/**,
      **/infrastructure/entity/**,
      **/infrastructure/enums/**,
      **/infrastructure/mapper/**,
      **/infrastructure/model/**,
      **/infrastructure/repository/**,
      **/infrastructure/util/**,
      <!-- Temporary exclusions until resolving Test Coverage issue for the microservice -->
      **/infrastructure/utils/**,
      **/infrastructure/client/content/**,
      **/infrastructure/client/ocd/**,
      **Application*
    </sonar.coverage.exclusions>
    <wsdl.dir>${basedir}/src/main/resources/wsdl</wsdl.dir>
  </properties>

  <dependencies>

    <!-- Graph qul dependency start -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-graphql</artifactId>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webflux</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webclient</artifactId>
    </dependency>

    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-core</artifactId>
    </dependency>

    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-test</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.springframework.graphql</groupId>
      <artifactId>spring-graphql-test</artifactId>
      <scope>test</scope>
    </dependency>

    <!-- Graph qul dependency end -->

    <dependency>
      <groupId>commons-validator</groupId>
      <artifactId>commons-validator</artifactId>
    </dependency>

    <dependency>
      <groupId>uk.co.whitbread.shared</groupId>
      <artifactId>commons-exceptions</artifactId>
    </dependency>

    <dependency>
      <groupId>io.getunleash</groupId>
      <artifactId>springboot-unleash-starter</artifactId>
    </dependency>

    <!-- other dependencies -->
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-collections4</artifactId>
    </dependency>

    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>

    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>postgresql</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
    </dependency>

    <!-- Spring/SpringBoot -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-openfeign</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
      <scope>runtime</scope>
      <optional>true</optional>
    </dependency>

    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-micrometer-tracing</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-micrometer-tracing-brave</artifactId>
    </dependency>

    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
      <scope>runtime</scope>
    </dependency>

    <dependency>
      <groupId>org.openapitools</groupId>
      <artifactId>jackson-databind-nullable</artifactId>
    </dependency>

    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>**/uk/co/whitbread/avail/business/events/AvailabilityBusinessEventApplication*</exclude>
            <exclude>**/uk/co/whitbread/avail/business/events/domain/model/**</exclude>
          </excludes>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>content</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <skipValidateSpec>true</skipValidateSpec>
              <inputSpec>
                ${project.basedir}/src/main/resources/openapi/content-entity-service-openApi.yaml
              </inputSpec>
              <generatorName>spring</generatorName>
              <modelPackage>uk.co.whitbread.content.entity.service.generated.models.content
              </modelPackage>
              <typeMappings>
                <typeMapping>OffsetDateTime=Date</typeMapping>
              </typeMappings>
              <importMappings>
                <importMapping>java.time.OffsetDateTime=java.util.Date</importMapping>
              </importMappings>
              <generateApis>false</generateApis>
              <generateApiDocumentation>false</generateApiDocumentation>
              <generateModelDocumentation>false</generateModelDocumentation>
              <generateSupportingFiles>false</generateSupportingFiles>
            </configuration>
          </execution>
          <execution>
            <id>ocdadapter</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <skipValidateSpec>true</skipValidateSpec>
              <inputSpec>
                ${project.basedir}/src/main/resources/openapi/ocd-adapter-service-openApi.yaml
              </inputSpec>
              <generatorName>spring</generatorName>
              <modelPackage>uk.co.whitbread.ocd.adapter.service.generated.models
              </modelPackage>
              <typeMappings>
                <typeMapping>OffsetDateTime=Date</typeMapping>
              </typeMappings>
              <importMappings>
                <importMapping>java.time.OffsetDateTime=java.util.Date</importMapping>
              </importMappings>
              <generateApis>false</generateApis>
              <generateApiDocumentation>false</generateApiDocumentation>
              <generateModelDocumentation>false</generateModelDocumentation>
              <generateSupportingFiles>false</generateSupportingFiles>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>com.google.code.maven-replacer-plugin</groupId>
        <artifactId>replacer</artifactId>
        <executions>
          <execution>
            <id>replace-import-javax-by-jakarta</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>replace</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <basedir>
            ${project.basedir}/target/generated-sources
          </basedir>
          <includes>
            <include>**/*.java</include>
          </includes>
          <replacements>
            <replacement>
              <token>import javax</token>
              <value>import jakarta</value>
            </replacement>
          </replacements>
        </configuration>
      </plugin>

      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <argLine>
            @{argLine}
            --add-opens java.base/java.time=ALL-UNNAMED
          </argLine>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.pitest</groupId>
        <artifactId>pitest-maven</artifactId>
        <configuration>
          <excludedClasses>
            <param>uk.co.whitbread.avail.business.events.AvailabilityBusinessEventApplication</param>
          </excludedClasses>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
