schema {
    query: Query
}

type Query {
    bookingInformation(basketReference: String!, country: String!, language: String!, upgradeToEmployeeRate: Boolean, bookingChannelCriteria: BookingChannelCriteria!): BookingInformation
}

input BookingChannelCriteria {
    channel: Channel!
    subchannel: String!
    language: String
}

enum Channel {
    PI
    BB
    CCUI
    DISTR
    EMPLOYEE
}

type BookingInformation {
    reservationByIdList: [ReservationById]
    previousTotal: Float
    balanceOutstanding: Float
    newTotal: Float
    totalCost: Float
    totalCostWoDiscount: Float
    discount: Float
    policyCode: String
    hotelId: String
    hotelName: String
    currencyCode: String
    bookingFlowId: String
    infoMessages: [String]
    upgradeToFlex: UpgradeToFlex
    hasCityTax: Boolean
    cityTaxTotal: Float
}

type ReservationById {
    reservationId: String
    reservationGuestList: [Guest]
    roomStay: RoomStay
    additionalGuestInfo: AdditionalGuestInfo!
    depositPolicies: [DepositPolicy]
    billing: BillingResponse
    preferences: [Preference]
}

type Guest  {
    givenName: String
    surName: String
    nameTitle: String
    email: String
    address: ReservationGuestAddress
    homeAddress: ReservationGuestAddress
    additionalDetails: StayersAdditionalDetails
    isAccompanyingGuest: Boolean
    profileId: String
    sameAsBooker: Boolean
}

type ReservationGuestAddress  {
    addressType: String
    addressLine1: String
    addressLine2: String
    addressLine3: String
    addressLine4: String
    postalCode: String
    cityName: String
    countryCode: String
    addressId: String
}

type StayersAdditionalDetails  {
    dob: String
    passportNumber: String
    nationality: String
}

type RoomStay {
    adultsNumber: Int
    childrenNumber: Int
    roomType: String
    ratePlanCode: String
    arrivalDate: String
    departureDate: String
    checkInTime: String
    checkOutTime: String
    rateExtraInfo: RateExtraInfo
    roomExtraInfo: RoomExtraInfo
    accessibleRoom: AccessibleRoom
}

type RateExtraInfo  {
    rateClassification: String!
    ratePlanCode: String
    rateOrder: String
    rateName: String!
    rateDescription: String
    rateLongDescription: String
    additionalDescription: String
    rateNotes: String
    rateCategory: String
}

type RoomExtraInfo  {
    roomType: String!
    roomName: String!
    roomDescription: String!
    groupId: String
}

type AccessibleRoom  {
    phoneNumber: String
    isAccessible: Boolean
}

type AdditionalGuestInfo  {
    purposeOfStay: String!
    acceptFutureMailing: Boolean
}

type DepositPolicy  {
    amountPaid: CurrencyAmountType
    amountDue: CurrencyAmountType
    policyCode: String
}

type CurrencyAmountType  {
    amount: Float
    currencyCode: String
}

type BillingResponse  {
    address: Address!
    email: String!
    firstName: String!
    lastName: String!
    telephone: String
    landline: String
    title: String
}

type Address  {
    addressType: String
    companyName: String
    addressLine1: String!
    addressLine2: String!
    addressLine3: String!
    addressLine4: String
    cityName: String
    countryCode: String
    country: String!
    postalCode: String!
}

type Preference  {
    code: String
    preferenceType: String
}

type UpgradeToFlex  {
    flexRateCode: String
    amount: Float
    currency: String
}