openapi: 3.1.0
info:
  description: Company Entity Service API Documentation
  title: company-entity-service API Documentation
  version: 3.0.0
servers:
- description: Generated server url
  url: http://localhost:9118
tags:
- description: Monitor and interact
  externalDocs:
    description: Spring Boot Actuator Web API Documentation
    url: https://docs.spring.io/spring-boot/docs/current/actuator-api/html/
  name: Actuator
paths:
  /v1/companies:
    get:
      operationId: getCompaniesFromCdh
      parameters:
      - in: query
        name: companyName
        required: true
        schema:
          type: string
          minLength: 1
      - in: query
        name: negotiatedRateCompanies
        required: false
        schema:
          type: boolean
      - in: query
        name: offset
        required: false
        schema:
          type: integer
          format: int32
          minimum: 1
      - in: query
        name: limit
        required: false
        schema:
          type: integer
          format: int32
          minimum: 1
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompaniesResponseDto"
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: 'Error Occurred '
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Resource Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal Server Error
      summary: Retrieves Companies as a result
      tags:
      - companies-controller
  /v1/companies/actuator:
    get:
      operationId: links
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
          description: OK
      summary: Actuator root web endpoint
      tags:
      - Actuator
  /v1/companies/actuator/health:
    get:
      operationId: health
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
          description: OK
      summary: Actuator web endpoint 'health'
      tags:
      - Actuator
  /v1/companies/actuator/info:
    get:
      operationId: info
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
          description: OK
      summary: Actuator web endpoint 'info'
      tags:
      - Actuator
  /v1/companies/actuator/metrics:
    get:
      operationId: listNames
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
          description: OK
      summary: Actuator web endpoint 'metrics'
      tags:
      - Actuator
  /v1/companies/actuator/metrics/{requiredMetricName}:
    get:
      operationId: metric
      parameters:
      - in: path
        name: requiredMetricName
        required: true
        schema:
          type: string
      - in: query
        name: tag
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
          description: OK
        "404":
          description: Not Found
      summary: Actuator web endpoint 'metrics-requiredMetricName'
      tags:
      - Actuator
  /v1/companies/actuator/prometheus:
    get:
      operationId: scrape
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - CONTENT_TYPE_004
          - CONTENT_TYPE_OPENMETRICS_100
          - CONTENT_TYPE_PROTOBUF
      - in: query
        name: includedNames
        schema:
          type: string
      responses:
        "200":
          content:
            application/openmetrics-text;version=1.0.0;charset=utf-8:
              schema:
                type: object
            application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited:
              schema:
                type: object
            text/plain;version=0.0.4;charset=utf-8:
              schema:
                type: object
          description: OK
      summary: Actuator web endpoint 'prometheus'
      tags:
      - Actuator
  /v1/companies/id/{id}:
    get:
      operationId: getCompanyById
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompanyResponseDto"
          description: OK
      tags:
      - companies-controller
  /v1/companies/profile:
    get:
      operationId: getCompaniesProfile
      parameters:
      - in: query
        name: hotelId
        required: true
        schema:
          type: string
          minLength: 1
      - in: query
        name: companyName
        required: false
        schema:
          type: string
      - in: query
        name: arNumber
        required: false
        schema:
          type: string
      - in: query
        name: limit
        required: false
        schema:
          type: integer
          format: int32
          minimum: 1
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompaniesResponseDto"
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: 'Error Occurred '
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Resource Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal Server Error
      summary: Retrieve Company details for given company id
      tags:
      - companies-controller
  /v1/companies/{corporateId}:
    get:
      operationId: getCompany
      parameters:
      - in: path
        name: corporateId
        required: true
        schema:
          type: string
      - in: query
        name: excludeNegotiatedRates
        required: false
        schema:
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompanyResponseDto"
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: 'Error Occurred '
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Resource Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal Server Error
      summary: Retrieve Company details for given company id
      tags:
      - companies-controller
components:
  schemas:
    AddressDto:
      type: object
      properties:
        addressLine1:
          type: string
        addressLine2:
          type: string
        addressLine3:
          type: string
        addressLine4:
          type: string
        city:
          type: string
        companyName:
          type: string
        country:
          type: string
        postalCode:
          type: string
    CompaniesResponseDto:
      type: object
      properties:
        companies:
          type: array
          items:
            $ref: "#/components/schemas/CompanyResponseDto"
        hasMore:
          type: boolean
        limit:
          type: integer
          format: int32
        offset:
          type: integer
          format: int32
        page:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        totalResults:
          type: integer
          format: int32
    CompanyResponseDto:
      type: object
      properties:
        active:
          type: boolean
        address:
          $ref: "#/components/schemas/AddressDto"
        arNumber:
          type: string
        companyId:
          type: string
        corpId:
          type: string
        language:
          type: string
        name:
          type: string
        negotiatedRateEnabled:
          type: boolean
        profileType:
          type: string
        restricted:
          type: boolean
        restrictedReason:
          type: string
        telephoneNumber:
          type: string
    ErrorResponse:
      type: object
      properties:
        debugMessage:
          type: string
        details:
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"
        errCode:
          type: integer
          format: int32
        globalErrTextTemplate:
          type: string
    Link:
      type: object
      properties:
        href:
          type: string
        templated:
          type: boolean
    ValidationError:
      type: object
      properties:
        elementId:
          type: string
        errTextTemplate:
          type: string
