export enum ActionContextKeys {
  BOOKING_FLOW_ID = 'BOOKING_FLOW_ID',
  BOOKING_INFORMATION = 'BOOKING_INFORMATION',
  DONATION_PACKAGES_OPERA = 'DONATION_PACKAGES_OPERA',
  RATE_INFORMATION = 'RATE_INFORMATION',
  HOTEL_INFORMATION = 'HOTEL_INFORMATION'
}
