configMap:
  aem_url: https://www.restaurantname.co.uk/en-gb
  zonal_url: https://api.liveres.co.uk
  label_url: https://www.premierinn.com/etc/designs/global/dictionaries/restaurants/i18n.jsondict.en