<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>uk.co.whitbread</groupId>
        <artifactId>digital-monorepo-service-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../../../parents/service-parent/pom.xml</relativePath>
    </parent>

    <artifactId>basket-service</artifactId>
    <packaging>jar</packaging>

    <properties>
        <application.port>9104</application.port>
        <spring.boot.jmx.port>9105</spring.boot.jmx.port>
        <sonar.coverage.exclusions>
            **/model/**,
            **/properties/**,
            **/config/**,
            **/mapper/**,
            **/exception/**,
            **/exceptions/**,
            **/properties/**,
            **/generated/**,
            **BasketServiceApplication*
        </sonar.coverage.exclusions>
        <sonar.cpd.exclusions>
            **/model/in/**
        </sonar.cpd.exclusions>
        <enforcer.skip>true</enforcer.skip>
    </properties>

    <name>basket-service</name>
    <description>Whitbread Basket Microservice</description>

    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-micrometer-tracing-brave</artifactId>
        </dependency>

        <!-- Micrometer tracing -->
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
        </dependency>

        <!-- Whitbread -->
        <dependency>
            <groupId>commons-validator</groupId>
            <artifactId>commons-validator</artifactId>
        </dependency>

        <dependency>
            <groupId>uk.co.whitbread.shared</groupId>
            <artifactId>commons-entity-validators</artifactId>
        </dependency>

        <dependency>
            <groupId>uk.co.whitbread.shared</groupId>
            <artifactId>common-auth0</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
        </dependency>

        <!-- Spring/SpringBoot -->
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations-jakarta</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web-services</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webclient</artifactId>
        </dependency>

        <!--Veracode vulnerabilities-->
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
        </dependency>

        <!-- DB -->
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>dynamodb</artifactId>
        </dependency>

        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>dynamodb-enhanced</artifactId>
        </dependency>

        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>sts</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-messaging</artifactId>
        </dependency>

        <dependency>
            <groupId>io.getunleash</groupId>
            <artifactId>springboot-unleash-starter</artifactId>
        </dependency>

        <!-- Test -->
        <dependency>
            <groupId>org.wiremock.integrations</groupId>
            <artifactId>wiremock-spring-boot</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-contract-stub-runner</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.dropwizard.metrics</groupId>
            <artifactId>metrics-core</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <!--spring-boot-maven-plugin is needed by springdoc-openapi-maven-plugin to generate OpenAPI yaml description -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <jmxPort>${spring.boot.jmx.port}</jmxPort>
                    <jvmArguments>-Dspring.application.admin.enabled=true</jvmArguments>
                </configuration>
                <executions>
                    <execution>
                        <id>pre-integration-test</id>
                        <goals>
                            <goal>start</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>post-integration-test</id>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!--Used to generate OpenAPI yaml description -->
            <plugin>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>integration-test</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <apiDocsUrl>http://localhost:${application.port}/v3/api-docs.yaml</apiDocsUrl>
                    <outputFileName>${project.name}-openApi.yaml</outputFileName>
                    <outputDir>${basedir}/docs/openApi</outputDir>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>**/uk/co/whitbread/basket/BasketServiceApplication*</exclude>
                        <exclude>**/uk/co/whitbread/**/model/**</exclude>
                        <exclude>**/uk/co/whitbread/**/config/**</exclude>
                        <exclude>**/uk/co/whitbread/**/mapper/**</exclude>
                        <exclude>**/uk/co/whitbread/**/exception/**</exclude>
                        <exclude>**/uk/co/whitbread/**/exceptions/**</exclude>
                        <exclude>**/uk/co/whitbread/**/generated/**</exclude>
                        <exclude>**/uk/co/whitbread/**/properties/**</exclude>
                    </excludes>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-contract-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <baseClassForTests>uk.co.whitbread.basket.ContractVerifierBaseTest
                    </baseClassForTests>
                    <basePackageForTests>uk.co.whitbread.basket</basePackageForTests>
                    <nameSuffixForTests>IT</nameSuffixForTests>
                    <testFramework>JUNIT5</testFramework>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>payments</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/openapi/payments-service-openapi.yaml
                            </inputSpec>
                            <generatorName>spring</generatorName>
                            <modelPackage>uk.co.whitbread.basket.generated.models.payments</modelPackage>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=Date</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>java.time.OffsetDateTime=java.util.Date</importMapping>
                            </importMappings>
                            <generateApis>false</generateApis>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <modelNameSuffix>Dto</modelNameSuffix>
                            <configOptions>
                                <useJakartaEe>true</useJakartaEe>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
                                </additionalModelTypeAnnotations>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>reservation</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/openapi/reservation-service-openapi.yaml
                            </inputSpec>
                            <generatorName>spring</generatorName>
                            <modelPackage>uk.co.whitbread.basket.generated.models.reservation</modelPackage>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=Date</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>java.time.OffsetDateTime=java.util.Date</importMapping>
                            </importMappings>
                            <generateApis>false</generateApis>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <configOptions>
                                <useJakartaEe>true</useJakartaEe>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
                                </additionalModelTypeAnnotations>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>content</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/openapi/content-service-openapi.yaml
                            </inputSpec>
                            <generatorName>spring</generatorName>
                            <modelPackage>uk.co.whitbread.basket.generated.models.content</modelPackage>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=Date</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>java.time.OffsetDateTime=java.util.Date</importMapping>
                            </importMappings>
                            <generateApis>false</generateApis>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <configOptions>
                                <useJakartaEe>true</useJakartaEe>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
                                </additionalModelTypeAnnotations>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>hotel-info</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/openapi/hotel-info-openapi.yaml
                            </inputSpec>
                            <generatorName>spring</generatorName>
                            <modelPackage>uk.co.whitbread.basket.generated.models.hotel</modelPackage>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=Date</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>java.time.OffsetDateTime=java.util.Date</importMapping>
                            </importMappings>
                            <generateApis>false</generateApis>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <configOptions>
                                <useJakartaEe>true</useJakartaEe>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
                                </additionalModelTypeAnnotations>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>marketing</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/openapi/marketing-service-openapi.yaml
                            </inputSpec>
                            <generatorName>spring</generatorName>
                            <modelPackage>uk.co.whitbread.basket.generated.models.marketing</modelPackage>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=Date</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>java.time.OffsetDateTime=java.util.Date</importMapping>
                            </importMappings>
                            <generateApis>false</generateApis>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <configOptions>
                                <useJakartaEe>true</useJakartaEe>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
                                </additionalModelTypeAnnotations>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>rules-agent</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/openapi/rules-agent-service-openapi.yaml
                            </inputSpec>
                            <generatorName>spring</generatorName>
                            <modelPackage>uk.co.whitbread.basket.generated.models.rules</modelPackage>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=Date</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>java.time.OffsetDateTime=java.util.Date</importMapping>
                            </importMappings>
                            <generateApis>false</generateApis>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <configOptions>
                                <useJakartaEe>true</useJakartaEe>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
                                </additionalModelTypeAnnotations>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>ohip-adapter</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/openapi/ohip-adapter-service-openApi.yaml
                            </inputSpec>
                            <generatorName>spring</generatorName>
                            <modelPackage>uk.co.whitbread.basket.generated.models.ohip</modelPackage>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=Date</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>java.time.OffsetDateTime=java.util.Date</importMapping>
                            </importMappings>
                            <generateApis>false</generateApis>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <configOptions>
                                <useJakartaEe>true</useJakartaEe>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
                                </additionalModelTypeAnnotations>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>cdh-adapter</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/openapi/cdh-adapter-service-openApi.yaml
                            </inputSpec>
                            <generatorName>spring</generatorName>
                            <modelPackage>uk.co.whitbread.basket.generated.models.cdh</modelPackage>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=Date</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>java.time.OffsetDateTime=java.util.Date</importMapping>
                            </importMappings>
                            <generateApis>false</generateApis>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <configOptions>
                                <useJakartaEe>true</useJakartaEe>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
                                </additionalModelTypeAnnotations>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>promotion</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/openapi/promo-service-openapi.yaml
                            </inputSpec>
                            <generatorName>spring</generatorName>
                            <modelPackage>uk.co.whitbread.basket.generated.models.promotion</modelPackage>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=Date</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>java.time.OffsetDateTime=java.util.Date</importMapping>
                            </importMappings>
                            <generateApis>false</generateApis>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <configOptions>
                                <useJakartaEe>true</useJakartaEe>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
                                </additionalModelTypeAnnotations>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <configuration>
                    <excludedClasses>
                        <param>uk.co.whitbread.basket.BasketServiceApplication</param>
                    </excludedClasses>
                    <excludedTestClasses>
                        <excludedTestClass>
                            uk.co.whitbread.reservation.architecture.ArchUnitTests
                        </excludedTestClass>
                    </excludedTestClasses>
                </configuration>
            </plugin>

        </plugins>
    </build>

</project>
