//
//  BusinessBookerIntroModule.swift
//  PremierInn
//
//  Created Freddie Parks on 30/09/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit

enum BusinessBookerIntroModule {
    static func build(with routerDelegate: BusinessBookerIntroRouterDelegate) -> UIViewController {
        let controller = BusinessBookerIntroView()

        controller.eventHandler = {
            let presenter = BusinessBookerIntroPresenter()

            let router = BusinessBookerIntroRouter()
            router.delegate = routerDelegate
            router.view = controller

            let interactor = BusinessBookerIntroInteractor()

            presenter.view = controller
            presenter.interactor = interactor
            presenter.router = router

            return presenter
        }()

        return controller
    }
}

protocol BusinessBookerIntroViewModel {
    var iconImage: UIImage { get }
    var primaryText: String { get }
    var secondaryText: String { get }
    var bbSignInTitle: String { get }
    var shouldShowPlebButton: Bool { get }
    var plebSignInTitle: String { get }
    var skipTitle: String { get }
}

protocol BusinessBookerIntroViewProtocol: AnyObject {
    func update(with viewModel: BusinessBookerIntroViewModel)
    func showSignOutAlert()
}

protocol BusinessBookerIntroViewEventHandler {
    func viewIsReady()
    func bbSignInButtonDidTap()
    func normalSignInButtonDidTap()
    func skipButtonDidTap()
    func userIsHappyToBeLoggedOutToSignInWithBusinessBooker()
}

protocol BusinessBookerIntroInteractorProtocol {
    var viewModel: BusinessBookerIntroViewModel? { get }
    var userIsLoggedIn: Bool { get }

    func updateViewDidDisplay()
}

protocol BusinessBookerIntroRouterProtocol {
    func dismiss(with completion: @escaping () -> Void?)
    func selectedLogin(isBusiness: Bool)
}

protocol BusinessBookerIntroRouterDelegate: AnyObject {
    func selectedLogin(isBusiness: Bool, andIsFromSplashScreen isFromSplashScreen: Bool)
}
