//
//  BusinessBookerIntroRouter.swift
//  PremierInn
//
//  R is for "Router" 🚦, and "Rancid" 😷
//
//  Created Freddie Parks on 30/09/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit

class BusinessBookerIntroRouter {
    var view: UIViewController?

    weak var delegate: BusinessBookerIntroRouterDelegate?
}

extension BusinessBookerIntroRouter: BusinessBookerIntroRouterProtocol {
    func dismiss(with completion: @escaping () -> Void?) {
        view?.dismiss(animated: true) {
            completion()
        }
    }

    func selectedLogin(isBusiness: Bool) {
        dismiss(with: {
            self.delegate?.selectedLogin(isBusiness: isBusiness, andIsFromSplashScreen: true)
        })
    }
}
