//
//  BusinessBookerIntroView.swift
//  PremierInn
//
//  V is for "View" 🌁, and "Vote" 🙋‍♂️
//
//  Created Freddie Parks on 30/09/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit

class BusinessBookerIntroView: UIViewController {
    @IBOutlet weak var icon: UIImageView!
    @IBOutlet weak var primaryText: UILabel! {
        didSet {
            primaryText.accessibilityIdentifier = AccessibilityIdentifiers.BBIntro.businessBookerSpashScreenTitle
            primaryText.font = .LargeTitle()
        }
    }
    @IBOutlet weak var secondaryText: UILabel! {
        didSet {
            secondaryText.accessibilityIdentifier = AccessibilityIdentifiers.BBIntro.businessBookerSpashScreenContent
            secondaryText.font = .Body()
        }
    }
    @IBOutlet weak var bbButton: RoundedCornersButton! {
        didSet {
            bbButton.accessibilityIdentifier = AccessibilityIdentifiers.BBIntro.signInBusinessBookerButton
            bbButton.titleLabel?.font = .Heading3_Semibold()
            bbButton.setTitleColor(.BaseWhite, for: .normal)
            bbButton.backgroundColor = .Tint1
        }
    }
    @IBOutlet weak var normalButton: RoundedCornersButton! {
        didSet {
            normalButton.accessibilityIdentifier = AccessibilityIdentifiers.BBIntro.normalSignInButton
            normalButton.titleLabel?.font = .Heading3_Semibold()
        }
    }
    @IBOutlet weak var skipButton: UnderlinedTitleButton! {
        didSet {
            skipButton.titleFont = .Heading3_Regular()
            skipButton.accessibilityIdentifier = AccessibilityIdentifiers.BBIntro.skipButton
        }
    }

    var eventHandler: BusinessBookerIntroViewEventHandler?

    init() {
        super.init(nibName: "BusinessBookerIntroView", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        configureModalNavigationBar()
        eventHandler?.viewIsReady()
    }

    override var preferredStatusBarStyle: UIStatusBarStyle {
        .lightContent
    }

    @IBAction func bbButtonDidTap(_ sender: Any) {
        eventHandler?.bbSignInButtonDidTap()
    }

    @IBAction func normalButtonDidTap(_ sender: Any) {
        eventHandler?.normalSignInButtonDidTap()
    }

    @IBAction func skipButtonDidTap(_ sender: Any) {
        eventHandler?.skipButtonDidTap()
    }
}

extension BusinessBookerIntroView: BusinessBookerIntroViewProtocol {
    func update(with viewModel: BusinessBookerIntroViewModel) {
        icon.image = viewModel.iconImage
        primaryText.text = viewModel.primaryText
        secondaryText.text = viewModel.secondaryText
        bbButton.setTitle(viewModel.bbSignInTitle, for: .normal)
        normalButton.setTitle(viewModel.plebSignInTitle, for: .normal)
        normalButton.isHidden = !viewModel.shouldShowPlebButton
        skipButton.setTitle(viewModel.skipTitle, for: .normal)
    }

    func showSignOutAlert() {
        let controller = UIAlertController(
            title: PILocalizedString("businessBookerSplashSignOutWarningTitle"),
            message: PILocalizedString("businessBookerSplashSignOutWarningMessage"),
            preferredStyle: .alert
        )
        controller.addAction(UIAlertAction(
            title: PILocalizedString("businessBookerSplashSignOutWarningCancelButtonTitle"),
            style: .cancel,
            handler: nil
        ))
        controller.addAction(UIAlertAction(
            title: PILocalizedString("businessBookerSplashSignOutWarningContinueButtonTitle"),
            style: .default
        ) { [unowned self] _ in
            eventHandler?.userIsHappyToBeLoggedOutToSignInWithBusinessBooker()
        })

        present(controller, animated: true)
    }
}
