//
//  BusinessBookerIntroPresenter.swift
//  PremierInn
//
//
//  Created Freddie Parks on 30/09/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import Foundation

class BusinessBookerIntroPresenter {
    weak var view: BusinessBookerIntroViewProtocol?

    var interactor: BusinessBookerIntroInteractorProtocol?
    var router: BusinessBookerIntroRouterProtocol?
}

extension BusinessBookerIntroPresenter: BusinessBookerIntroViewEventHandler {
    func viewIsReady() {
        guard let viewModel = interactor?.viewModel else { return }
        view?.update(with: viewModel)

        interactor?.updateViewDidDisplay()
    }

    func bbSignInButtonDidTap() {
        if (interactor?.userIsLoggedIn ?? false) == true {
            view?.showSignOutAlert()
            return
        }

        router?.selectedLogin(isBusiness: true)
    }

    func normalSignInButtonDidTap() {
        router?.selectedLogin(isBusiness: false)
    }

    func skipButtonDidTap() {
        router?.dismiss(with: {})
    }

    func userIsHappyToBeLoggedOutToSignInWithBusinessBooker() {
        router?.selectedLogin(isBusiness: true)
    }
}
