//
//  BusinessBookerIntroInteractor.swift
//  PremierInn
//
//
//  Created Freddie Parks on 30/09/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit
import SimpleNetwork

class BusinessBookerIntroInteractor {
}

extension BusinessBookerIntroInteractor: BusinessBookerIntroInteractorProtocol {
    struct ViewModel: BusinessBookerIntroViewModel {
        let iconImage: UIImage
        let primaryText: String
        let secondaryText: String
        let bbSignInTitle: String
        let plebSignInTitle: String
        let shouldShowPlebButton: Bool
        let skipTitle: String
    }

    var userIsLoggedIn: Bool {
        UserSessionManager.sharedInstance.currentUser != nil
    }

    var viewModel: BusinessBookerIntroViewModel? {
        ViewModel(
            iconImage: UIImage(named: "briefcase") ?? UIImage(),
            primaryText: PILocalizedString("bbSplashScreenTitle"),
            secondaryText: PILocalizedString("bbSplashScreenText"),
            bbSignInTitle: PILocalizedString("bbSplashScreenBBButton"),
            plebSignInTitle: PILocalizedString("bbSplashScreenNormalButton"),
            shouldShowPlebButton: UserSessionManager.sharedInstance.currentUser == nil,
            skipTitle: PILocalizedString("Skip")
        )
    }

    func updateViewDidDisplay() {
        UserDefaults.standard.set(true, forKey: Constants.shownBBIntroKey)
    }
}
