bart:
  password: password
  username: username
  initSession:
    username: initSessionUsername
    password: initSessionPassword
  host: http://localhost:${wiremock.server.port:0}
  service:
    pi.guestService:
      url: ${bart.host}/csp/sql/ws.RegisteredGuest.RegisteredGuestService.cls
    pi.initSession.auth0Service:
      url: ${bart.host}/csp/sql/ws.RegisteredGuest.Auth0Service.cls
    bb.clientService:
      url: ${bart.host}/csp/sql/ws.Corporate.DashboardService.cls
    bb.initSession.auth0Service:
      url: ${bart.host}/csp/sql/ws.Corporate.Auth0Service.cls
    booking:
      url: ${bart.host}/csp/sql/ws.Booking.BookingService.cls

session:
  security:
    encryptionEnabled: true
    encryptionKey: "OJs67WE8z4Mfe/iuIDkbMFr1e5t5EsCrqFfJaJUFvNQ="
    whitelistingEnabled: true
    # Auth0 servers addresses
    whitelistedAddresses:
      - 52.28.56.226
      - 52.28.45.240
      - 52.16.224.164
      - 52.16.193.66
      - 34.253.4.94
      - 52.50.106.250
      - 52.211.56.181
      - 52.213.38.246
      - 52.213.74.69
      - 52.213.216.142
      - 35.156.51.163
      - 35.157.221.52
      - 52.28.184.187
      - 52.28.212.16
      - 52.29.176.99
      - 52.57.230.214
      - 54.76.184.103
      - 52.210.122.50
      - 52.208.95.174
      - 52.210.122.50
      - 52.208.95.174
      - 54.76.184.103

swagger:
  api:
    version: "1.4"
    path: https://api.swaggerhub.com/apis/whitbread/Login-API/${swagger.api.version}/swagger.yaml
    token: 146309c1-633f-4a57-8d94-79bbb16e0c2e

logging:
  level:
    org.springframework.ws.client.MessageTracing: trace
    uk.co.whitbread: debug

auth:
  management:
    domain: test.eu.auth0.com
    clientId: testId
    clientSecret: testSecret
    audience: https://test.eu.auth0.com/api/v2/
    lazy-migration-enabled: false
  encryption:
    key: aZCGss97HqRj4r8XraMV+6XO15T7q+yxN3q1TTLoqOU=
