package uk.co.whitbread.reservation.infrastructure.config;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.PropertyAccessor;
import org.springframework.boot.jackson.autoconfigure.JsonMapperBuilderCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Configures Jackson to accept package-private constructors (e.g., those generated by Lombok @Builder).
 * Jackson 3 (Spring Boot 4.0) is stricter about constructor visibility than Jackson 2.
 */
@Configuration
public class JacksonConfig {

  @Bean
  public JsonMapperBuilderCustomizer creatorVisibilityCustomizer() {
    return builder -> builder.changeDefaultVisibility(
        vc -> vc.withVisibility(PropertyAccessor.CREATOR, JsonAutoDetect.Visibility.ANY));
  }
}
