export const styles = {
  containerWrapper: {
    maxW: { base: '100%', md: 'conainer.xl' },
    mx: 'auto',
    my: { md: '5.5rem' },
    px: '0px',
  },
  container: {
    boxShadow: { base: 'none', md: `0 0.125rem 0.5rem rgba(0,0,0,0.2)` },
    border: { base: 'none', md: '1px solid lightGrey2' },
    borderRadius: '0.25rem',
  },
  headerRow: {
    justifyContent: 'space-between',
    alignItems: 'center',
    px: { base: '1rem', md: '2rem' },
    py: '2rem',
    bg: 'primaryShadow',
    borderRadius: '0.5rem 0.5rem 0 0',
    gap: '1rem',
    flexWrap: 'wrap',
  },
  sectionTitle: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
  },
  generateBatchBtn: {
    width: { base: '100%', md: 'auto' },
    height: '2.75rem',
    px: '2rem',
    borderRadius: '0.25rem',
    color: 'baseWhite',
    gap: '0.5rem',
    fontWeight: 'semibold',
    lineHeight: '120%',
    fontSize: '1rem',
  },
  desktopTableWrapper: {
    display: { base: 'none', md: 'block' },
    width: '100%',
    overflowX: 'scroll',
    minHeight: '260px',
    position: 'relative',
  },
  tableHeader: {
    color: 'darkGrey1',
    fontSize: '1rem',
    fontWeight: 'semibold',
    lineHeight: '1.5rem',
    textTransform: 'none',
    height: '4.25rem',
  },
  sortByField: {
    borderColor: 'lightGrey3',
    background: 'lightGrey5',
    transition: 'background-color 0.2s',
  },
  rowStyle: {
    color: 'darkGrey1',
    fontSize: '1rem',
    fontWeight: 'normal',
    lineHeight: '2.5rem',
    height: '4.375rem',
  },
  mobileCardWrapper: { display: { base: 'block', md: 'none' }, mt: '1.25rem', px: '1rem' },
  mobileCard: {
    bg: 'baseWhite',
    borderRadius: '0.5rem',
    mb: '1rem',
    boxShadow: '0 0.125rem 0.5rem rgba(0,0,0,0.2)',
  },
  mobileRow: {
    display: 'grid',
    gridTemplateColumns: '40% 60%',
    alignItems: 'center',

    '&:first-of-type > .mobileDesc': {
      fontWeight: '600',
    },
  },
  mobileLabel: {
    fontSize: '0.75rem',
    fontWeight: '600',
    px: '1.5rem',
    pt: '1rem',
    background: 'lightGrey5',

    '&:last-of-type': {
      pb: '1rem',
    },
  },
  mobileDesc: {
    fontSize: '0.875rem',
    pl: '1.375rem',
    pt: '0.8rem',
  },
  statusFlex: {
    gap: '0.2rem',
    alignItems: 'center',
    pl: { base: '1.375rem', md: '0' },
  },
  statusText: {
    fontWeight: 'semibold',
    color: 'baseBlack',
  },
  downloadButton: {
    width: { base: '100%', md: '10.875rem' },
    maxHeight: '2.75rem',
    borderRadius: '0.25rem',
    border: '1px solid tertiary',
    background: 'tertiary',
    color: 'baseWhite',
    justifyContent: 'center',
  },
  disabledButton: {
    width: { base: '100%', md: '10.875rem' },
    color: 'lightGrey1',
    textAlign: 'center',
    fontSize: '1rem',
    fontWeight: 'medium',
    lineHeight: '2.5rem',
    maxHeight: '2.75rem',
    cursor: 'not-allowed',
  },
  downloadButtonWrapper: { p: '1rem' },
  loadingCell: { height: '28.125rem' },
  paginationWrapper: {
    my: '1.25rem',
    minH: '3.75rem',
    minW: '18.75rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 1,
    transition: 'opacity 0.2s ease-in-out',
  },
  nodata: {
    wrapper: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      my: '5.5rem',
    },
    circle: {
      width: '5.5rem',
      height: '5.5rem',
      bg: 'primaryShadow',
      borderRadius: 'full',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      mb: '1.25rem',
    },
    text: {
      mt: '0.75rem',
      color: 'primary',
      fontFamily: 'body',
      fontSize: '1rem',
      fontWeight: 'semibold',
      lineHeight: '1.5rem',
      fontStyle: 'normal',
    },
  },
  mobileSortWrapper: {
    display: { base: 'flex', md: 'none' },
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '0.5rem',
    width: '100%',
    border: 0,
    px: { base: '1rem', md: '2rem' },
  },
  mobileSortText: {
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 1,
    flex: '1 0 0',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    color: 'darkGrey1',
    fontFamily: 'body',
    fontSize: '1rem',
    fontWeight: 'normal',
    lineHeight: '1.5rem',
    fontStyle: 'normal',
  },
  mobileSortSelect: {
    appearance: 'none',
    WebkitAppearance: 'none',
    MozAppearance: 'none',
    border: '1px solid #333333',
    borderRadius: '0.25rem',
    height: '3.5rem',
    mt: '0.75rem',
    mb: '0.75rem',

    _focus: {
      border: '1px solid #333333',
      boxShadow: 'none',
    },

    _hover: {
      border: '1px solid #333333',
    },
  },
  sticky: {
    position: 'sticky',
    top: 0,
    zIndex: 1,
    background: 'baseWhite',
    border: '1px solid darkGrey1',
  },
  tableMinHeight: {
    minH: '28.34375rem',
  },

  eligibilityHeaderWrapper: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    alignItems: 'center',
  },
  eligibilityTitle: {
    borderBottom: '1px solid',
    borderColor: 'lightGrey3',
    width: '100%',
    textAlign: 'center',
  },
  eligibilitySubHeaderGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    textAlign: 'center',
    columnGap: '1rem',
    px: '1.2rem',
  },
  eligibilityCellWrapper: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
  },
  eligibilityRowGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    width: '100%',
    textAlign: 'center',
    alignItems: 'center',
    fontSize: '0.82rem',

    '&:not(:last-child)': {
      borderBottom: '1px solid',
      borderColor: 'lightGrey3',
    },

    '& > *:not(:last-child)': {
      borderRight: '1px solid',
      borderColor: 'lightGrey3',
    },
  },
  eligibilityRowText: {
    lineHeight: '1rem !important',
    whiteSpace: 'normal',
    px: '0.1rem',
  },
};
