<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>uk.co.whitbread</groupId>
    <artifactId>digital-monorepo-service-parent</artifactId>
    <version>${revision}</version>
    <relativePath>../../../parents/service-parent/pom.xml</relativePath>
  </parent>

  <artifactId>refund-request-processor</artifactId>
  <packaging>jar</packaging>

  <properties>
    <application.port>9113</application.port>
    <sonar.coverage.exclusions>
      **/model/**,
      **/properties/**,
      **/config/**,
      **/mapper/**,
      **/exception/**,
      **/exceptions/**,
      **/properties/**,
      **/generated/**,
      **RefundRequestProcessorApplication*
    </sonar.coverage.exclusions>
  </properties>

  <name>refund-request-processor</name>
  <description>Whitbread Refund Request Processor</description>

  <dependencies>

    <!-- Whitbread -->
    <dependency>
      <groupId>commons-validator</groupId>
      <artifactId>commons-validator</artifactId>
    </dependency>

    <!-- Spring/SpringBoot -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web-services</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webclient</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.kafka</groupId>
      <artifactId>spring-kafka</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-micrometer-tracing-brave</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.retry</groupId>
      <artifactId>spring-retry</artifactId>
    </dependency>

    <dependency>
      <groupId>org.openapitools</groupId>
      <artifactId>jackson-databind-nullable</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
    </dependency>

    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.kafka</groupId>
      <artifactId>spring-kafka-test</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>io.zipkin.brave</groupId>
      <artifactId>brave-instrumentation-kafka-clients</artifactId>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <jvmArguments>-Dspring.application.admin.enabled=true</jvmArguments>
        </configuration>
        <executions>
          <execution>
            <id>pre-integration-test</id>
            <goals>
              <goal>start</goal>
            </goals>
          </execution>
          <execution>
            <id>post-integration-test</id>
            <goals>
              <goal>stop</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>integration-test</id>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <apiDocsUrl>http://localhost:${application.port}/v3/api-docs.yaml</apiDocsUrl>
          <outputFileName>${project.name}-openApi.yaml</outputFileName>
          <outputDir>${basedir}/docs/openApi</outputDir>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>**/uk/co/whitbread/**/RefundRequestProcessorApplication*</exclude>
            <exclude>**/uk/co/whitbread/**/model/**</exclude>
            <exclude>**/uk/co/whitbread/**/config/**</exclude>
            <exclude>**/uk/co/whitbread/**/mapper/**</exclude>
            <exclude>**/uk/co/whitbread/**/exception/**</exclude>
            <exclude>**/uk/co/whitbread/**/exceptions/**</exclude>
            <exclude>**/uk/co/whitbread/**/properties/**</exclude>
            <exclude>**/uk/co/whitbread/**/generated/**</exclude>
          </excludes>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>payments</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <configOptions>
                <useJakartaEe>true</useJakartaEe>
              </configOptions>
              <skipValidateSpec>true</skipValidateSpec>
              <inputSpec>
                ${project.basedir}/src/main/resources/openapi/payments-service-openapi.yaml
              </inputSpec>
              <generatorName>spring</generatorName>
              <modelPackage>uk.co.whitbread.refund.processor.generated.models.payments</modelPackage>
              <typeMappings>
                <typeMapping>OffsetDateTime=Date</typeMapping>
              </typeMappings>
              <importMappings>
                <importMapping>java.time.OffsetDateTime=java.util.Date</importMapping>
              </importMappings>
              <generateApis>false</generateApis>
              <generateApiDocumentation>false</generateApiDocumentation>
              <generateModelDocumentation>false</generateModelDocumentation>
              <generateSupportingFiles>false</generateSupportingFiles>
              <modelNameSuffix>Dto</modelNameSuffix>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.google.code.maven-replacer-plugin</groupId>
        <artifactId>replacer</artifactId>
        <executions>
          <execution>
            <id>replace-import-javax-by-jakarta</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>replace</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <basedir>
            ${project.basedir}/target/generated-sources
          </basedir>
          <includes>
            <include>**/*.java</include>
          </includes>
          <replacements>
            <replacement>
              <token>import javax</token>
              <value>import jakarta</value>
            </replacement>
          </replacements>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.pitest</groupId>
        <artifactId>pitest-maven</artifactId>
        <configuration>
          <excludedClasses>
            <param>uk.co.whitbread.refund.processor.RefundRequestProcessorApplication</param>
          </excludedClasses>
          <excludedTestClasses>
            <excludedTestClass>
              uk.co.whitbread.reservation.architecture.ArchUnitTests
            </excludedTestClass>
          </excludedTestClasses>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
