<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>uk.co.whitbread</groupId>
        <artifactId>digital-monorepo-service-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../../../parents/service-parent/pom.xml</relativePath>
    </parent>

    <artifactId>hotel-account-service-opera</artifactId>
    <packaging>jar</packaging>

    <name>hotel-account-service-opera</name>
    <description>Hotel Account Microservice Opera</description>

    <properties>
        <application.port>9020</application.port>
        <sonar.coverage.exclusions>
            **/model/**,
            **/properties/**,
            **/config/**,
            **/exceptions/**,
            **HotelAccountMicroserviceApplication*
        </sonar.coverage.exclusions>
    </properties>

    <dependencies>
        <!-- Whitbread -->
        <dependency>
            <groupId>uk.co.whitbread.shared</groupId>
            <artifactId>commons-validators</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.co.whitbread.shared</groupId>
            <artifactId>commons-cdh-lib</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.co.whitbread.shared</groupId>
            <artifactId>commons-azure-email-service</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.co.whitbread.shared</groupId>
            <artifactId>common-auth0</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.co.whitbread.shared</groupId>
            <artifactId>commons-entity-validators</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>uk.co.whitbread.shared</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- Spring -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web-services</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webclient</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-json</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-micrometer-tracing-brave</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
        </dependency>

        <!-- Other dependencies -->
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-okhttp</artifactId>
        </dependency>
        <dependency>
            <!-- Required to use PATCH. -->
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-httpclient</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-validator</groupId>
            <artifactId>commons-validator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>io.getunleash</groupId>
            <artifactId>springboot-unleash-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.google.errorprone</groupId>
                    <artifactId>error_prone_annotations</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
        </dependency>

        <!-- OpenAPI -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-common</artifactId>
        </dependency>

        <!-- Test -->
        <dependency>
            <groupId>io.github.benas</groupId>
            <artifactId>random-beans</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.wiremock</groupId>
            <artifactId>wiremock-standalone</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-inline</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-contract-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <baseClassForTests>uk.co.whitbread.hotel.account.controller.ContractVerifierBaseTest</baseClassForTests>
                    <nameSuffixForTests>IT</nameSuffixForTests>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>cdh-adapter</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>${project.basedir}/src/main/resources/openapi/cdh-adapter-service-openApi.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <modelPackage>uk.co.whitbread.cdh.adapter.service.generated.models.reservationSearch</modelPackage>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=Date</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>java.time.OffsetDateTime=java.util.Date</importMapping>
                            </importMappings>
                            <generateApis>false</generateApis>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <configOptions>
                                <useJakartaEe>true</useJakartaEe>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- Spring Boot start/stop is required for SpringDoc generation. -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <jvmArguments>-Dspring.application.admin.enabled=true</jvmArguments>
                    <maxAttempts>240</maxAttempts>
                </configuration>
                <executions>
                    <execution>
                        <id>pre-integration-test</id>
                        <goals>
                            <goal>start</goal>
                        </goals>
                        <configuration>
                            <profiles>
                                <profile>integration</profile>
                            </profiles>
                        </configuration>
                    </execution>
                    <execution>
                        <id>post-integration-test</id>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>integration-test</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <apiDocsUrl>http://localhost:${application.port}/v3/api-docs.yaml</apiDocsUrl>
                    <outputFileName>${project.name}-openApi.yaml</outputFileName>
                    <outputDir>${basedir}/docs/openApi</outputDir>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <configuration>
                    <excludedClasses>
                        <param>uk.co.whitbread.**.model.**</param>
                        <param>uk.co.whitbread.**.config.**</param>
                        <param>uk.co.whitbread.**.mapper.**</param>
                        <param>uk.co.whitbread.**.constants.**</param>
                        <param>uk.co.whitbread.**.exception.**</param>
                        <param>uk.co.whitbread.**.exceptions.**</param>
                        <param>uk.co.whitbread.**.properties.**</param>
                        <param>uk.co.whitbread.**.generated.**</param>
                        <param>uk.co.whitbread.hotel.account.HotelAccountMicroserviceApplication</param>
                    </excludedClasses>
                    <excludedTestClasses>
                        <excludedTestClass>uk.co.whitbread.reservation.architecture.ArchUnitTests</excludedTestClass>
                    </excludedTestClasses>
                    <mutators>
                        <mutator>CONDITIONALS_BOUNDARY</mutator>
                        <mutator>INCREMENTS</mutator>
                        <mutator>INVERT_NEGS</mutator>
                        <mutator>NEGATE_CONDITIONALS</mutator>
                        <mutator>EMPTY_RETURNS</mutator>
                        <mutator>FALSE_RETURNS</mutator>
                        <mutator>TRUE_RETURNS</mutator>
                        <mutator>NULL_RETURNS</mutator>
                        <mutator>PRIMITIVE_RETURNS</mutator>
                        <mutator>REMOVE_CONDITIONALS</mutator>
                        <mutator>REMOVE_INCREMENTS</mutator>
                    </mutators>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
