export const mockMultipleBookings = [
  {
    arrivalDate: '2023-04-19',
    bookedBy: 'Test Donations',
    leadGuest: 'Mr Test Donations',
    bookingReference: 'GAPR40674',
    historyRecordNumber: '0',
    bookingStatus: 'FUTURE',
    hotelName: 'Alpha2 Frankfurt City Centre ',
    noOfNights: '3',
    sourceSystem: 'OPERA',
    totalCost: {
      amount: 234.5,
      currency: 'EUR',
    },
    leadGuestSurname: 'Donations',
    hotelCode: 'FRAHOF',
  },
  {
    arrivalDate: '2023-04-27',
    bookedBy: 'Test Donations',
    leadGuest: 'Mr Test Donations',
    bookingReference: 'BAKR212068',
    historyRecordNumber: '0',
    bookingStatus: 'FUTURE',
    hotelName: 'Alpha2 London Leicester Square',
    noOfNights: '1',
    sourceSystem: 'BART',
    totalCost: {
      amount: 291.5,
      currency: 'GBP',
    },
    leadGuestSurname: 'Donations',
    hotelCode: 'LONLEI',
  },
  {
    arrivalDate: '2023-05-12',
    bookedBy: 'Test Donations',
    leadGuest: 'Mr Test Donations',
    bookingReference: 'BACR193834',
    historyRecordNumber: '0',
    bookingStatus: 'FUTURE',
    hotelName: 'Alpha2 Manchester Bury',
    noOfNights: '1',
    sourceSystem: 'BART',
    totalCost: {
      amount: 71,
      currency: 'GBP',
    },
    leadGuestSurname: 'Donations',
    hotelCode: 'BURTHY',
  },
  {
    arrivalDate: '2023-06-22',
    bookedBy: 'Test Donations',
    leadGuest: 'Mr Test Donations',
    bookingReference: 'BACR193835',
    historyRecordNumber: '0',
    bookingStatus: 'FUTURE',
    hotelName: 'Alpha2 Manchester Bury',
    noOfNights: '1',
    sourceSystem: 'BART',
    totalCost: {
      amount: 61,
      currency: 'GBP',
    },
    leadGuestSurname: 'Donations',
    hotelCode: 'BURTHY',
  },
  {
    arrivalDate: '2023-04-01',
    bookedBy: 'Test Donations',
    leadGuest: 'Mrs Asd Dsa',
    bookingReference: 'BACR192405',
    historyRecordNumber: '0',
    bookingStatus: 'PAST',
    hotelName: 'Alpha2 Manchester Bury',
    noOfNights: '10',
    sourceSystem: 'BART',
    totalCost: {
      amount: 3586,
      currency: 'GBP',
    },
    leadGuestSurname: 'Dsa',
    hotelCode: 'BURTHY',
  },
  {
    arrivalDate: '2023-04-01',
    bookedBy: 'Test Donations',
    leadGuest: 'Mr Tstunu Tstunu',
    bookingReference: 'BACR192394',
    historyRecordNumber: '0',
    bookingStatus: 'PAST',
    hotelName: 'Alpha2 Manchester Bury',
    noOfNights: '8',
    sourceSystem: 'BART',
    totalCost: {
      amount: 2396,
      currency: 'GBP',
    },
    leadGuestSurname: 'Tstunu',
    hotelCode: 'BURTHY',
  },
  {
    arrivalDate: '2023-04-01',
    bookedBy: 'Test Donations',
    leadGuest: 'Mr Test Donations',
    bookingReference: 'BACR192440',
    historyRecordNumber: '0',
    bookingStatus: 'PAST',
    hotelName: 'Alpha2 Manchester Bury',
    noOfNights: '1',
    sourceSystem: 'BART',
    totalCost: {
      amount: 106,
      currency: 'GBP',
    },
    leadGuestSurname: 'Donations',
    hotelCode: 'BURTHY',
  },
  {
    arrivalDate: '2023-07-01',
    bookedBy: 'Test Donations',
    leadGuest: 'Mr Test Donations',
    bookingReference: 'BACR193765',
    historyRecordNumber: '0',
    bookingStatus: 'CANCELLED',
    hotelName: 'Alpha2 Manchester Bury',
    noOfNights: '1',
    sourceSystem: 'BART',
    totalCost: {
      amount: 117,
      currency: 'GBP',
    },
    leadGuestSurname: 'Donations',
    hotelCode: 'BURTHY',
  },
  {
    arrivalDate: '2023-08-01',
    bookedBy: 'Test Donations',
    leadGuest: 'Mr Test Donations',
    bookingReference: 'BACR192856',
    historyRecordNumber: '0',
    bookingStatus: 'CANCELLED',
    hotelName: 'Alpha2 Manchester Bury',
    noOfNights: '1',
    sourceSystem: 'BART',
    totalCost: {
      amount: 74,
      currency: 'GBP',
    },
    leadGuestSurname: 'Donations',
    hotelCode: 'BURTHY',
  },
  {
    arrivalDate: '2023-08-01',
    bookedBy: 'Test Donations',
    leadGuest: 'Mr Test Donations',
    bookingReference: 'BACR192949',
    historyRecordNumber: '0',
    bookingStatus: 'CANCELLED',
    hotelName: 'Alpha2 Manchester Bury',
    noOfNights: '1',
    sourceSystem: 'BART',
    totalCost: {
      amount: 74,
      currency: 'GBP',
    },
    leadGuestSurname: 'Donations',
    hotelCode: 'BURTHY',
  },
];
