<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>uk.co.whitbread</groupId>
        <artifactId>digital-monorepo-service-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../../../parents/service-parent/pom.xml</relativePath>
    </parent>

    <artifactId>hotel-login-service-opera</artifactId>
    <packaging>jar</packaging>

    <name>hotel-login-service-opera</name>
    <description>Hotel Login MicroService Opera</description>

    <properties>
        <application.port>9028</application.port>
        <sonar.coverage.exclusions>
            **/model/**,
            **/properties/**,
            **HotelLoginApplication*
        </sonar.coverage.exclusions>
    </properties>

    <dependencies>
        <!-- Whitbread -->
        <dependency>
            <groupId>uk.co.whitbread.shared</groupId>
            <artifactId>bart-shared-lib</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>commons-io</groupId>
                    <artifactId>commons-io</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>uk.co.whitbread.shared</groupId>
            <artifactId>commons-exceptions</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.co.whitbread.shared</groupId>
            <artifactId>commons-auth0</artifactId>
        </dependency>

        <!-- Spring/SpringBoot -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web-services</artifactId>
        </dependency>

        <!-- Other Dependencies -->
        <dependency>
            <groupId>commons-validator</groupId>
            <artifactId>commons-validator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.benas</groupId>
            <artifactId>random-beans</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-common</artifactId>
        </dependency>

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-context</artifactId>
        </dependency>

        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-contract-wiremock</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>spring-mock-mvc</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-micrometer-tracing-brave</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-contract-maven-plugin</artifactId>
                <configuration>
                    <baseClassForTests>uk.co.whitbread.hotel.account.controller.ContractVerifierBaseTest
                    </baseClassForTests>
                    <nameSuffixForTests>IT</nameSuffixForTests>
                </configuration>
            </plugin>
            <!--spring-boot-maven-plugin is needed by springdoc-openapi-maven-plugin to generate OpenAPI yaml description -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <jvmArguments>-Dspring.application.admin.enabled=true</jvmArguments>
                </configuration>
                <executions>
                    <execution>
                        <id>pre-integration-test</id>
                        <goals>
                            <goal>start</goal>
                        </goals>
                        <configuration>
                            <profiles>
                                <profile>integration</profile>
                            </profiles>
                        </configuration>
                    </execution>
                    <execution>
                        <id>post-integration-test</id>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!--Used to generate OpenAPI yaml description -->
            <plugin>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>integration-test</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <apiDocsUrl>http://localhost:${application.port}/v3/api-docs.yaml</apiDocsUrl>
                    <outputFileName>${project.name}-openApi.yaml</outputFileName>
                    <outputDir>${basedir}/docs/openApi</outputDir>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>**/uk/co/whitbread/hotel/account/model/*</exclude>
                        <exclude>**/uk/co/whitbread/hotel/account/properties/*</exclude>
                        <exclude>**/HotelLoginApplication*</exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <configuration>
                    <excludedClasses>
                        <param>uk.co.whitbread.hotel.account.HotelLoginApplication</param>
                    </excludedClasses>
                    <excludedTestClasses>
                        <excludedTestClass>
                            uk.co.whitbread.reservation.architecture.ArchUnitTests
                        </excludedTestClass>
                    </excludedTestClasses>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
