//
//  RoomTypesInteractor.swift
//  PremierInn
//
//
//  Created Georgios Aikaterinakis on 06/06/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import SimpleNetwork
import Foundation

private enum RoomTypesFallbackData {
    static let premiumRoomsHotelContentCodes = ["LONHOL", "LONISL"]
    static let accessibleRoomURLString = "https://www.premierinn.com/content/dam/pi/websites/hotelimages/gb/en/non-hotel-specific/Accessible/Accessible-Room-Leeds-Headingley.jpg"
}

class RoomTypesInteractor {
    private let hotel: Hotel
    private var hasAccessibilityCriteria: Bool {
        BookingDetails.sharedInstance.criteria.rooms.contains(where: { $0.type == .accessible }) }
    private let selectedLettingType: String?

    init(with hotel: Hotel, lettingType: String?) {
        self.hotel = hotel
        self.selectedLettingType = lettingType
    }
}

extension RoomTypesInteractor: RoomTypesInteractorProtocol {
    private func roomTypeModel(for tabItem: TabBarItem) -> RoomTypeViewModel? {
        let url: URL? = {
            guard let imagePath = tabItem.renditions?.first else { return nil }
            guard let baseUrl = Constants.imageBaseUrl else { return nil }

            return baseUrl.appendingPathComponent(imagePath)
        }()
        let roomTitle = tabItem.roomTitle
        let roomType = tabItem.roomType
        let description = tabItem.roomDescriptionText
        let characteristics: [RoomTypeCharacteristic]? = tabItem.newFacilities?.compactMap {
            guard let title = $0.facilitiesTitle?.trimmingCharacters(in: .whitespaces),
                  let description = $0.navOptions?.first?.facility else { return nil }
            return (title, description)
        }
        let additionalInfo = tabItem.additionalInfo

        return RoomTypeViewModel(
            url: url,
            roomTitle: roomTitle,
            roomType: roomType,
            description: description,
            characteristics: characteristics,
            additionalInfo: additionalInfo
        )
    }

    private func hotelInformationSegment(with title: String?) -> HotelInformationSegment? {
        let title = title?.capitalized ?? PILocalizedString("Room", comment: "")
        // let title = (tabItem.roomTitle != "Standard room" ? tabItem.roomTitle : tabItem.room?.capitalized) ?? PILocalizedString("Room", comment: "")
        // let roomSuffix = PILocalizedString("room", comment: "")

        return HotelInformationSegment(
            //            title: title.replacingOccurrences(of: " \(roomSuffix)", with: ""),
            title: title,
            content: ""
        )
    }

    var viewModel: RoomTypesViewModel? {
        let screenName = PILocalizedString("hotelDetailsRoomSectionTitle", comment: "Room types title")

        // TODO: This should be coming from hotel-specific content so can be removed when this happens

        let tabGroups = hotel.hotelRoomConfiguration?.tabGroups ?? []
        var tabItems = hotel.hotelRoomConfiguration?.tabItems ?? []
        if hotel.offersPremierPlus == false { // filter out the Premier Plus tab if the hotel doesn't offer it
            tabItems = tabItems.filter { ($0.roomTitle ?? "").contains(LettingType.premierPlus.name) == false }
        }

        let roomTypes = Array(Set(tabItems.compactMap { $0.room }))
        let roomCategoryViewModels: [RoomCategoryViewModel] = roomTypes.compactMap({ roomType in
            let roomTypeTitle = tabGroups.first(where: { $0.groupId == roomType })?.groupTitle ?? roomType

            let filteredTabItems = tabItems.filter({ $0.room == roomType })
            let roomTypeViewModels = filteredTabItems.compactMap { self.roomTypeModel(for: $0) }

            return RoomCategoryViewModel(
                title: roomTypeTitle,
                roomTypeViewModels: roomTypeViewModels
            )
        })

        let sortedRoomCategoryViewModels = roomCategoryViewModels.sorted(by: { a, b in
            let firstIndex = tabGroups.firstIndex(where: { $0.groupTitle == a.title }) ?? -1
            let secondIndex = tabGroups.firstIndex(where: { $0.groupTitle == b.title }) ?? -1

            return firstIndex < secondIndex
        })

        let sectionTitle = SettingsManager.sharedInstance.roomsSectionTitle(for: selectedLettingType, and: hotel.brand)
        // need to compare codes insteads of titles...
        let defaultSegmentIndex = sortedRoomCategoryViewModels
            .firstIndex(where: { ($0.roomTypeViewModels.firstIndex(where: { roomTypeViewModel in
            roomTypeViewModel.roomType?.contains(sectionTitle) == true
        }) ?? -1) != -1 }) ?? 0

        let roomTypeSegmentData = RoomTypeSegmentsViewModel(
            // use standard PI colours
            backgroundColour: .BaseWhite,
            selectorColor: .Tint1,
            normalTextAttributes: HotelBrand.premierInn.segmentedTextNormalAttributes,
            selectedTextAttributes: HotelBrand.premierInn.segmentedTextSelectedAttributes,
            informationSegments: sortedRoomCategoryViewModels.compactMap { self.hotelInformationSegment(with: $0.title) },
            defaultSegmentIndex: defaultSegmentIndex
        )

        return RoomTypesViewModel(
            screenName: screenName,
            roomCategoryViewModels: sortedRoomCategoryViewModels,
            roomTypeSegmentData: roomTypeSegmentData,
            disclaimerText: hotel.disclaimer ?? PILocalizedString("hotelDetailsRoomSectionDisclaimer")
        )
    }
}
