//
//  RoomTypesView.swift
//  PremierInn
//
//  V is for "View" 🌁, and "Vote" 🙋‍♂️
//
//  Created Georgios Aikaterinakis on 06/06/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit
import Formeka

class RoomTypesView: BaseViewController {
    @IBOutlet weak var titleLabel: UILabel! {
        didSet {
            titleLabel.textColor = .TintD1
            titleLabel.font = .Heading2_Bold()
            titleLabel.accessibilityTraits.insert(.header)
        }
    }
    @IBOutlet weak var table: UITableView! {
        didSet {
            table.rowHeight = UITableView.automaticDimension
            table.estimatedRowHeight = 150
            table.backgroundColor = .BaseWhite
            table.separatorStyle = .none
            if #available(iOS 15.0, *) {
                table.sectionHeaderTopPadding = 0.0
            }
            registerNibs()
        }
    }

    @IBOutlet weak var disclaimerLabel: UILabel! {
        didSet {
            disclaimerLabel.textColor = .TintD1
            disclaimerLabel.font = .BodySmall()
        }
    }
    @IBOutlet weak var collectionView: UICollectionView! {
        didSet {
            collectionView.backgroundColor = .BaseWhite
        }
    }

    var currentRoomTypeSectionIndex = 0

    var eventHandler: RoomTypesViewEventHandler?

    private var formekaViewModel: FormekaViewModel?
    private var roomTypesModel: RoomTypesViewModel?

    init() {
        super.init(nibName: "RoomTypesViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func viewDidLoad() {
        super.viewDidLoad()

        collectionView.register(
            UINib(nibName: String(describing: RoomTypeCollectionViewCell.self), bundle: nil),
            forCellWithReuseIdentifier: "RoomTypeCollectionCell"
        )

        let closeModalImage = UIImage(named: "closeModal")

        let closeButton = UIBarButtonItem(
            image: closeModalImage,
            style: .plain,
            target: self,
            action: #selector(closeButtonDidTap)
        )
        closeButton.tintColor = .TintL1
        closeButton.accessibilityIdentifier = AccessibilityIdentifiers.AdditionalInfo.closeButton
        closeButton.accessibilityLabel = PILocalizedString("closeBarButtonTitle", comment: "Close bar button title")

        navigationItem.rightBarButtonItem = closeButton
//        navigationItem.title = "Our rooms"
        view.backgroundColor = .BaseWhite
        eventHandler?.viewNeedsSetup()
        eventHandler?.viewIsReady()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)

        navigationController?.setNavigationBarHidden(false, animated: animated)
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        collectionView.collectionViewLayout.invalidateLayout()
    }

    private func registerNibs() {
        guard table != nil else { return }

        table.registerCellNib(with: HotelInformationSegmentsCell.self)
        table.registerCellNib(with: RoomContentCell.self)
        table.registerCellNib(with: RoomTypeCharacteristicCell.self)
        table.registerCellNib(with: SingleHotelPhotoCell.self)
    }

    @objc func closeButtonDidTap() {
        eventHandler?.closeButtonDidTap()
    }
}

extension RoomTypesView: RoomTypesViewProtocol {
    func setup(with viewModel: RoomTypesViewModel) {
        currentRoomTypeSectionIndex = viewModel.roomTypeSegmentData.defaultSegmentIndex
        disclaimerLabel.text = viewModel.disclaimerText.htmlStripped()
    }

    func update(with viewModel: RoomTypesViewModel) {
        formekaViewModel = roomTypesViewModel(with: viewModel)
        roomTypesModel = viewModel

        titleLabel.text = viewModel.screenName

        table.delegate = formekaViewModel
        table.dataSource = formekaViewModel

        collectionView.delegate = self
        collectionView.dataSource = self

        table.reloadData()
        collectionView.reloadData()
    }

    func updateSegment(with viewModel: RoomTypesViewModel, selectedIndex: Int) {
        collectionView.reloadData()
    }
}

extension RoomTypesView: HotelInformationSegmentsCellDelegate {
    func hotelInformationSegmentsCellSegmentDidChange(cell: HotelInformationSegmentsCell) {
        guard let segmentControl = cell.segmentControl else { return }
        guard let indexPath = table.indexPath(for: cell) else { return }
        guard let row = formekaViewModel!.row(at: indexPath) else { return }

        switch RoomTypeRow(rawValue: row.tag) {
        case .roomTypesSegmentsCell?:
            currentRoomTypeSectionIndex = segmentControl.selectedSegmentIndex

            eventHandler?.segmentChanged(selectedIndex: currentRoomTypeSectionIndex)

        default:
            return
        }
    }
}

extension RoomTypesView: UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        roomTypesModel?.roomCategoryViewModels[safe: currentRoomTypeSectionIndex]?.roomTypeViewModels.count ?? 0
    }

    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        guard let cell = collectionView.dequeueReusableCell(
            withReuseIdentifier: "RoomTypeCollectionCell",
            for: indexPath
        ) as? RoomTypeCollectionViewCell else { return UICollectionViewCell() }

        cell.configure(with: roomTypesModel, currentRoomTypeSectionIndex: currentRoomTypeSectionIndex, indexPath: indexPath)
        return cell
    }
}
