//
//  RoomTypesModule.swift
//  PremierInn
//
//  Created Georgios Aikaterinakis on 06/06/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit
import SimpleNetwork

enum RoomTypesModule {
    static func build(
        with hotel: Hotel,
        lettingType: String?
    ) -> UIViewController {
        let controller = RoomTypesView()

        controller.eventHandler = {
            let presenter = RoomTypesPresenter()

            let router = RoomTypesRouter()
            router.view = controller

            let interactor = RoomTypesInteractor(with: hotel, lettingType: lettingType)

            presenter.view = controller
            presenter.interactor = interactor
            presenter.router = router

            return presenter
        }()

        return controller
    }
}

typealias RoomTypeCharacteristic = (title: String, description: String)

protocol RoomTypesViewProtocol: AnyObject {
    func setup(with viewModel: RoomTypesViewModel)
    func update(with viewModel: RoomTypesViewModel)
    func updateSegment(with viewModel: RoomTypesViewModel, selectedIndex: Int) // or just RoomTypeViewModel
}

protocol RoomTypesViewEventHandler {
    func viewNeedsSetup()
    func viewIsReady()
    func segmentChanged(selectedIndex: Int)
    func closeButtonDidTap()
}

protocol RoomTypesInteractorProtocol {
    var viewModel: RoomTypesViewModel? { get }
}

protocol RoomTypesRouterProtocol {
    func closeButtonDidTap()
}

enum RoomTypeRow: String {
    case roomTypesPhotoCell
    case roomCategorySegmentsCell
    case roomTypesSegmentsCell
    case roomTypeTitleCell
    case roomTypeDescriptionCell
    case roomTypeCharacteristicCell
    case roomTypeAdditionalInfoCell
}

struct RoomTypesViewModel {
    let screenName: String
    let roomCategoryViewModels: [RoomCategoryViewModel]
    let roomTypeSegmentData: RoomTypeSegmentsViewModel
    let disclaimerText: String
}

struct RoomTypeSegmentsViewModel {
    var backgroundColour: UIColor
    var selectorColor: UIColor
    var normalTextAttributes: [NSAttributedString.Key: Any]
    var selectedTextAttributes: [NSAttributedString.Key: Any]
    var informationSegments: [HotelInformationSegment]
    var defaultSegmentIndex: Int
}

struct RoomCategoryViewModel {
    let title: String?
    let roomTypeViewModels: [RoomTypeViewModel]
}

struct RoomTypeViewModel {
    let url: URL?
    let roomTitle: String?
    let roomType: String?
    let description: String?
    let characteristics: [RoomTypeCharacteristic]?
    let additionalInfo: String?
}
