//
//  RoomTypesRouter.swift
//  PremierInn
//
//  R is for "Router" 🚦, and "Rancid" 😷
//
//  Created Georgios Aikaterinakis on 06/06/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import UIKit

class RoomTypesRouter {
    var view: UIViewController?
}

extension RoomTypesRouter: RoomTypesRouterProtocol {
    func closeButtonDidTap() {
        view?.dismiss(animated: true)
    }
}
