//
//  RoomTypesPresenter.swift
//  PremierInn
//
//
//  Created Georgios Aikaterinakis on 06/06/2019.
//  Copyright © 2019 Whitbread. All rights reserved.
//
//  Template generated by VIPER SNIPER (Twisp/Fred) @WBDigi
//

import Foundation

class RoomTypesPresenter {
    weak var view: RoomTypesViewProtocol?

    var interactor: RoomTypesInteractorProtocol?
    var router: RoomTypesRouterProtocol?
}

extension RoomTypesPresenter: RoomTypesViewEventHandler {
    func closeButtonDidTap() {
        router?.closeButtonDidTap()
    }

    func viewNeedsSetup() {
        guard let viewModel = interactor?.viewModel else { return }
        view?.setup(with: viewModel)
    }

    func viewIsReady() {
        guard let viewModel = interactor?.viewModel else { return }
        view?.update(with: viewModel)
    }

    func segmentChanged(selectedIndex: Int) {
        guard let viewModel = interactor?.viewModel else { return }
        view?.updateSegment(with: viewModel, selectedIndex: selectedIndex)
    }
}
