package uk.co.whitbread.basket.domain.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * Errors map.The Error's message is used by the globalTxtErrTemplate.
 */

@RequiredArgsConstructor
@Getter
public enum ErrorCode {
  DIGITAL_INVALID_TOTAL_COST_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 124),
  DIGITAL_PAYMENT_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 125),
  DIGITAL_INVALID_PAYMENT_OPTION_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 126),
  DIGITAL_ECKOH_NOT_LAUCHED_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 127),
  DIGITAL_MISSING_BASKET_REF_OR_HOTEL_ID_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 128),
  DIGITAL_PARTIAL_REFUND_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 129),
  DIGITAL_NO_REFUND_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 130),
  DIGITAL_FORMATTING_BUSINESS_NOTES_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 131),
  DIGITAL_FORMATTING_BA_BUSINESS_NOTES_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 132),
  DIGITAL_FORMATTING_BA_PROV_BUSINESS_NOTES_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 133),
  DIGITAL_NO_PAYMENT_ATTEMPT_EXCEPTION(Constants.ERRORS_PAYMENT_GENERIC, 134),
  DIGITAL_FAILURE_NOT_ACCEPT_EXCEPTION(Constants.FRAUD_CHECK_FAILED, 135),
  DIGITAL_FAILURE_3CP_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 136),
  DIGITAL_UNSUCCESSFULL_PROVIDER_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 137),
  DIGITAL_PAYMENT_FAILURE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 138),
  DIGITAL_UNSUPPORTED_CARD_TYPE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 139),
  DIGITAL_AC_BOOKING_CHANNEL_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 140),
  DIGITAL_AC_NULL_BOOKING_CHANNEL_EXCEPTION(Constants.UNSUPPORTED_CARD_TYPE, 141),
  DIGITAL_INVALID_BASKET_REF_EXCEPTION(Constants.BASKET_INVALID_REFERENCE, 142),
  DIGITAL_INVALID_PAYMENT_OPT_EXCEPTION(Constants.BASKET_INVALID_REFERENCE, 143),
  DIGITAL_NO_LONGER_BASKET_EXCEPTION(Constants.BASKET_INVALID_REFERENCE, 144),
  DIGITAL_INVALID_BASKET_EXCEPTION(Constants.BASKET_INVALID_REFERENCE, 145),
  DIGITAL_INVALID_BASKETREF_EXCEPTION(Constants.BASKET_INVALID_REFERENCE, 146),
  DIGITAL_INVALID_BASKET_PAYPAL_EXCEPTION(Constants.BASKET_INVALID_REFERENCE, 147),
  DIGITAL_INVALID_BASKET_REF_PAYPAL_EXCEPTION(Constants.BASKET_INVALID_REFERENCE, 148),
  DIGITAL_CCUI_INVALID_BASKET_EXCEPTION(Constants.BASKET_INVALID_REFERENCE, 149),
  DIGITAL_CCUI_INVALID_COMPLETED_BASKET_EXCEPTION(Constants.BASKET_INVALID_REFERENCE, 150),
  DIGITAL_EMAIL_BASKET_INVALID_EXCEPTION(Constants.BASKET_INVALID_REFERENCE, 151),
  DIGITAL_CCUI_INVALID_COMPANY_EXCEPTION(Constants.COMPANY_ID_NOT_FOUND, 152),
  DIGITAL_CCUI_PAYMENT_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 153),
  DIGITAL_BASKET_ITEM_FAILURE_EXCEPTION(Constants.BASKET_ITEM_EXCEPTION, 154),
  DIGITAL_BASKET_ITEM_UNKNOWN_ACL_EXCEPTION(Constants.BASKET_ITEM_EXCEPTION, 155),
  DIGITAL_BASKET_ITEM_REFUND_EXCEPTION(Constants.BASKET_ITEM_EXCEPTION, 156),
  DIGITAL_OUT_OF_SYNC_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 157),
  DIGITAL_ITEM_NOT_ADDED_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 158),
  DIGITAL_BASKET_NOT_LONGER_VALID_EXCEPTION(Constants.BASKET_INVALID_REFERENCE, 159),
  DIGITAL_BASKET_MISSING_EXCEPTION(Constants.BASKET_INVALID_REFERENCE, 160),
  DIGITAL_SENDING_ORDER_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 161),
  DIGITAL_COMPRESSION_EXCEPTION(Constants.GENERIC_EXCEPTION, 162),
  DIGITAL_DECOMPRESSION_EXCEPTION(Constants.GENERIC_EXCEPTION, 163),
  DIGITAL_EMAIL_NOTIFICATION_EXCEPTION(Constants.PROCESSING_EXCEPTION, 164),
  DIGITAL_BASKET_ORDER_NO_ITEMS_EXCEPTION(Constants.PROCESSING_EXCEPTION, 165),
  DIGITAL_BASKET_ORDER_EXTRACTS_ITEMS_EXCEPTION(Constants.PROCESSING_EXCEPTION, 166),
  DIGITAL_BASKET_ORDER_EXTRACTS_FIELD_NAME_EXCEPTION(Constants.PROCESSING_EXCEPTION, 167),
  DIGITAL_BASKET_ORDER_EXTRACTS_NULL_EXCEPTION(Constants.PROCESSING_EXCEPTION, 168),
  DIGITAL_BASKET_ORDER_EXTRACTS_FIELD_NULL_EXCEPTION(Constants.PROCESSING_EXCEPTION, 169),
  DIGITAL_BASKET_ORDER_EXTRACTS_MAP_NULL_EXCEPTION(Constants.PROCESSING_EXCEPTION, 170),
  DIGITAL_BASKET_ORDER_EXTRACTS_PATH_NULL_EXCEPTION(Constants.PROCESSING_EXCEPTION, 171),
  DIGITAL_SENDING_ORDER_INVALID_BASKET_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 230),
  DIGITAL_BASKET_NOT_COMPLETED_EXCEPTION(Constants.GENERIC_VALIDATION_EXCEPTION, 243),
  DIGITAL_PROMOTION_ALREADY_USED_EXCEPTION(Constants.INVALID_PROMOTION, 294),
  DIGITAL_PROMOTION_EXPIRED_EXCEPTION(Constants.INVALID_PROMOTION, 295),
  DIGITAL_PROMOTION_INVALID_EXCEPTION(Constants.INVALID_PROMOTION, 297),
  DIGITAL_PROMOTION_UNAVAILABLE_EXCEPTION(Constants.INVALID_PROMOTION, 298),
  DIGITAL_BASKET_CIOL_THIRDPARTY_PAYMENT_VALIDATION_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 310),
  DIGITAL_FAILURE_DATATRANS_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 311),

  GET_PAYMENT_CLIENT_EXCEPTION(Constants.BUSINESS_COMPANY_ERROR, 600),
  GET_PAYMENT_SERVER_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 601),
  CREATE_PAYMENT_CLIENT_EXCEPTION(Constants.BUSINESS_COMPANY_ERROR, 602),
  CREATE_PAYMENT_SERVER_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 603),
  TOKEN_PAYMENT_CLIENT_EXCEPTION(Constants.BUSINESS_COMPANY_ERROR, 604),
  TOKEN_PAYMENT_SERVER_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 605),
  TOKEN_REFUND_CLIENT_EXCEPTION(Constants.BUSINESS_COMPANY_ERROR, 606),
  TOKEN_REFUND_SERVER_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 607),
  PAYMENT_SERVICE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 608),
  UPDATE_BASKET_NOT_FOUND_EXCEPTION(Constants.BASKET_NOT_FOUND, 700),
  UPDATE_STATUS_BASKET_NOT_FOUND_EXCEPTION(Constants.BASKET_NOT_FOUND, 701),
  UPDATE_POLLING_BASKET_NOT_FOUND_EXCEPTION(Constants.BASKET_NOT_FOUND, 702),
  BASKET_REPO_NOT_FOUND_EXCEPTION(Constants.BASKET_NOT_FOUND, 703),
  PREP_BOOKING_CHARGES_EXCEPTION(Constants.BASKET_NOT_FOUND, 704),
  GET_PREP_BOOKING_CHARGES_EXCEPTION(Constants.BASKET_NOT_FOUND, 705),
  BASKET_EXISTS_EXCEPTION(Constants.INVALID_REFERENCE, 706),
  BASKET_NOT_FOUND_EXCEPTION(Constants.INVALID_REFERENCE, 707),
  BASKET_INVALID_EXCEPTION(Constants.INVALID_REFERENCE, 708),
  GENERATED_INVALID_EXCEPTION(Constants.INVALID_REFERENCE, 709),
  BASKET_REF_INVALID_EXCEPTION(Constants.INVALID_REFERENCE, 710),
  BASKET_SORTKEY_INVALID_EXCEPTION(Constants.INVALID_REFERENCE, 711),
  BASKET_GENERATED_INVALID_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 712),
  BASKET_GENERATED_NULL_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 713),
  MARKET_SERVICE_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 504),
  PAYMENT_CONTACT_BANK_EXCEPTION(Constants.PAYMENT_CONTACT_BANK_EXCEPTION, 614),
  PAYMENT_INCORRECT_CARD_EXCEPTION(Constants.PAYMENT_INCORRECT_CARD_EXCEPTION, 615),
  PAYMENT_TRY_AGAIN_EXCEPTION(Constants.PAYMENT_TRY_AGAIN_EXCEPTION, 616),
  PAYPAL_TIMEOUT_EXCEPTION(Constants.PAYPAL_TIMEOUT_EXCEPTION, 617),
  PAYPAL_CREATE_CUSTOMER_EXCEPTION(Constants.PAYPAL_CREATE_CUSTOMER_EXCEPTION, 618),
  PAYPAL_DECLINE_EXCEPTION(Constants.PAYPAL_DECLINE_EXCEPTION, 619),
  PREPAID_CHARGES_EXCEPTION(Constants.INTERNAL_SERVER_EXCEPTION, 714),
  DIGITAL_INVALID_TOKEN(Constants.INVALID_TOKEN, 120),
  DIGITAL_MIT_CC_DEPOSIT_FOLIOS_EXCEPTION(Constants.PAYMENT_MIT_CC_DEPOSIT_FAILED, 307),
  DIGITAL_MIT_CC_NO_THIRD_PARTY_EXCEPTION(Constants.PAYMENT_MIT_CC_NO_THIRD_PARTY, 308),
  DIGITAL_MIT_CC_INVALID_ROUTING_EXCEPTION(Constants.PAYMENT_MIT_CC_INVALID_ROUTING, 309);
  private final String message;
  private final int code;

  public static class Constants {

    public static final String INTERNAL_SERVER_EXCEPTION = "internal.server.exception";
    public static final String BASKET_NOT_FOUND = "basket.not.found.error";
    public static final String BASKET_INVALID_REFERENCE = "basket.invalid.reference.error";
    public static final String BASKET_ITEM_EXCEPTION = "basket.item.error";
    public static final String BUSINESS_COMPANY_ERROR = "business.company.error";
    public static final String FRAUD_CHECK_FAILED = "fraud_check_failed";
    public static final String ERRORS_PAYMENT_GENERIC = "errors.payment.generic";
    public static final String COMPANY_ID_NOT_FOUND = "company.id.not.found.error";
    public static final String UNSUPPORTED_CARD_TYPE = "cardType.option.invalid.error";
    public static final String GENERIC_EXCEPTION = "BSK-1001";
    public static final String PROCESSING_EXCEPTION = "BSK-1002";
    public static final String INVALID_REFERENCE = "basket.invalid.reference.error";
    public static final String GENERIC_VALIDATION_EXCEPTION = "generic.validation.exception";
    public static final String PAYMENT_CONTACT_BANK_EXCEPTION = "PAYMENT_CONTACT_BANK_EXCEPTION_VALUE";
    public static final String PAYMENT_INCORRECT_CARD_EXCEPTION = "PAYMENT_INCORRECT_CARD_EXCEPTION_VALUE";
    public static final String PAYMENT_TRY_AGAIN_EXCEPTION = "PAYMENT_TRY_AGAIN_EXCEPTION_VALUE";
    public static final String PAYPAL_CREATE_CUSTOMER_EXCEPTION = "paypal.create.customer.exception";
    public static final String PAYPAL_DECLINE_EXCEPTION = "paypal.decline.exception";
    public static final String PAYPAL_TIMEOUT_EXCEPTION = "paypal.timeout.exception";
    public static final String INVALID_PROMOTION = "promotion.invalid";
    public static final String INVALID_TOKEN = "invalid.token";
    public static final String PAYMENT_MIT_CC_DEPOSIT_FAILED = "mit.cc.ciol.save.deposit.failed";
    public static final String PAYMENT_MIT_CC_NO_THIRD_PARTY = "mit.cc.ciol.not.third.party";
    public static final String PAYMENT_MIT_CC_INVALID_ROUTING = "mit.cc.ciol.not.prepaired";

    private Constants() {}
  }
}