server:
  port: 9121

logging:
  configuration:
    logger: default

swagger:
  api:
    version: 1.0.0

spring:
  cache:
    type: none
  jackson:
    deserialization:
      fail-on-null-for-primitives: false