openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- description: Generated server url
  url: http://localhost:9031
tags:
- description: Monitor and interact
  externalDocs:
    description: Spring Boot Actuator Web API Documentation
    url: https://docs.spring.io/spring-boot/docs/current/actuator-api/html/
  name: Actuator
paths:
  /countries:
    get:
      deprecated: true
      operationId: retrieveAllCountriesWithHeaders
      parameters:
      - in: header
        name: country
        required: false
        schema:
          type: string
          default: gb
      - in: header
        name: language
        required: false
        schema:
          type: string
          default: en
      - in: query
        name: country
        required: false
        schema:
          type: string
          default: gb
      - in: query
        name: language
        required: false
        schema:
          type: string
          default: en
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CountriesResponse"
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal Server Error
      tags:
      - hotel-countries-controller
  /hotel-countries-service/actuator:
    get:
      operationId: links
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal Server Error
      summary: Actuator root web endpoint
      tags:
      - Actuator
  /hotel-countries-service/actuator/health:
    get:
      operationId: health
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal Server Error
      summary: Actuator web endpoint 'health'
      tags:
      - Actuator
  /hotel-countries-service/actuator/info:
    get:
      operationId: info
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal Server Error
      summary: Actuator web endpoint 'info'
      tags:
      - Actuator
  /hotel-countries-service/actuator/metrics:
    get:
      operationId: listNames
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal Server Error
      summary: Actuator web endpoint 'metrics'
      tags:
      - Actuator
  /hotel-countries-service/actuator/metrics/{requiredMetricName}:
    get:
      operationId: metric
      parameters:
      - in: path
        name: requiredMetricName
        required: true
        schema:
          type: string
      - in: query
        name: tag
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad Request
        "404":
          description: Not Found
        "500":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal Server Error
      summary: Actuator web endpoint 'metrics-requiredMetricName'
      tags:
      - Actuator
  /hotel-countries-service/actuator/prometheus:
    get:
      operationId: scrape
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - CONTENT_TYPE_004
          - CONTENT_TYPE_OPENMETRICS_100
          - CONTENT_TYPE_PROTOBUF
      - in: query
        name: includedNames
        schema:
          type: string
      responses:
        "200":
          content:
            application/openmetrics-text;version=1.0.0;charset=utf-8:
              schema:
                type: object
            application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited:
              schema:
                type: object
            text/plain;version=0.0.4;charset=utf-8:
              schema:
                type: object
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal Server Error
      summary: Actuator web endpoint 'prometheus'
      tags:
      - Actuator
components:
  schemas:
    CountriesResponse:
      type: object
      properties:
        countries:
          type: array
          items:
            $ref: "#/components/schemas/Country"
    Country:
      type: object
      properties:
        countryCode:
          type: string
        countryCodeISO:
          type: string
        countryLegend:
          type: string
        dialingCode:
          type: string
        flagImg:
          type: string
        passportRequired:
          type: boolean
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          example: "001"
          minLength: 1
        details:
          type: array
          example:
          - Error message
          items:
            type: string
      required:
      - code
      - details
    Link:
      type: object
      properties:
        href:
          type: string
        templated:
          type: boolean
