import AncillariesLayout from './layouts/AncillariesLayout/AncillariesLayout';
import BookingsLayout from './layouts/BookingsLayout';
import ConfirmationLayout from './layouts/ConfirmationLayout';
import DefaultLayout from './layouts/DefaultLayout';
import GraphQLPageLayout from './layouts/GraphQLPageLayout';
import GuestDetailsLayout from './layouts/GuestDetailsLayout';
import PaymentLayout from './layouts/PaymentLayout';
import PriceFinderLayout from './layouts/PriceFinderLayout';
import SecondaryHDPLayout from './layouts/SecondaryHDPLayout';

export { ConfirmationLayout };
export { DefaultLayout };
export { GraphQLPageLayout };
export { BookingsLayout };
export { SecondaryHDPLayout };
export { AncillariesLayout };
export { GuestDetailsLayout };
export { PaymentLayout };
export { PriceFinderLayout };
