package uk.co.whitbread.ohip.infrastructure.rest.controller.reservation.model.in;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotEmpty;
import java.util.Set;
import lombok.Data;


@Data
@Schema(requiredProperties = {"reservationIds", "hotelId", "customerAccountId"})
public class LinkReservationToLeisureCustomerRequestDto {

  @NotEmpty
  @Valid
  @Schema(description = "List of Reservation IDs to link to the customer account")
  private Set<String> reservationIds;

  @NotEmpty
  @Valid
  @Schema(example = "LONEUS")
  private String hotelId;

  @NotEmpty
  @Valid
  @Schema(description = "Customer Account ID generated by CDH")
  private String customerAccountId;
}
