server:
  port: "@application.port@"
  shutdown: graceful

swagger:
  api:
    version: "@project.version@"

info:
  build:
    groupId: "@project.groupId@"
    artifact: "@project.artifactId@"
    description: "@project.description@"
    version: "@project.version@"
    git:
      originUrl: "@git.remote.origin.url@"
      branch: "@git.branch@"
      commit:
        id: "@git.commit.id@"
        time: "@git.commit.time@"
        message: "@git.commit.message.short@"
springdoc:
  show-actuator: true
  writer-with-order-by-keys: true

irsa:
  enabled: true

aws:
  s3:
    maxRetry: ${AWS_S3_MAX_RETRY:2}
    #endpoint: http://localhost.localstack.cloud:4566
    validForMinutes: ${AWS_S3_VALID_FOR_MINUTES:5}
    bucket:
      miReportName: ${AWS_S3_MI_BUCKET_NAME:business-booker-tm-mi-report-dev}
      emergencyReportName: ${AWS_S3_EMERGENCY_BUCKET_NAME:business-booker-tm-emergency-report-dev}
      region: ${AWS_REGION:eu-west-1}
      #accessKey: foo
      #secretAccessKey: bar

management:
  tracing:
    propagation:
      type: w3c
    baggage:
      correlation:
        fields:
          - x-amzn-trace-id
          - flow-code
        enabled: true
      enabled: true
      remote-fields:
        - x-amzn-trace-id
        - flow-code
  endpoints:
    web:
      base-path: /v1/company-reports/actuator
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  configuration:
    debug:
      enabled: true
      exclusions:
        - .*/actuator.*
  level:
      brave: WARN
  pattern:
    # Logging pattern containing traceId and spanId; no longer provided through Sleuth by default
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

config:
  service:
    cdh:
      host: http://${CDH_ADAPTER_HOST:localhost:9119}
      companyMiReportEndpoint: "/v1/cdh/companies/{companyId}/reports/management-information"
      emergencyReportEndpoint: "/v1/cdh/companies/{companyId}/reports/emergency-report"
      accessContext: "Reporting Microservice"
      accessedBy: "reporting@whitbread.com"

  reports:
    allowed-record-count: ${MI_REPORT_ALLOWED_RECORD_COUNT:50000}
    emergencyStatusItems: ${EMERGENCY_REPORT_STATUS_ITEMS:Reserved,Arrival,In house}
    managementInformationStatusItems: ${MI_REPORT_STATUS_ITEMS:NoShow,CheckedOut}
auth:
  tenants:
    - name: "CCUI Tenant"
      audience: ${CCUI_TENANT_AUDIENCE}
      namespace:  ${CCUI_TENANT_NAMESPACE}
      issuer:  ${CCUI_TENANT_ISSUER}
      jwkUri:  ${CCUI_TENANT_JWK_URI}
    - name: "PI BB Tenant"
      audience:  ${PI_BB_TENANT_AUDIENCE}
      namespace:  ${PI_BB_TENANT_NAMESPACE}
      issuer:  ${PI_BB_TENANT_ISSUER}
      jwkUri:  ${PI_BB_TENANT_JWK_URI}

---
spring:
  config:
    activate:
      on-profile:
        - opera-perf
        - opera-dev
        - opera-qa
        - local

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
---
spring:
  config:
    activate:
      on-profile:
        - local
        - opera-qa

logging:
  level:
    uk:
      co:
        whitbread: DEBUG;

auth:
  rulesEngineHost: rules-agent-entity-service
  isAllowedAccessForRoleIdsEndpoint: /v1/rules/ccui/rbac
  tenants:
    - name: "CCUI Tenant"
      audience: dummy
      namespace: dummy
      issuer: dummy
      jwkUri:  https://dummy/.well-known/jwks.json
    - name: "PI BB Tenant"
      audience: dummy
      namespace: dummy
      issuer: dummy
      jwkUri: https://dummy/.well-known/jwks.json

---
spring:
  config:
    activate:
      on-profile:
        - opera-prod

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
